### ISSUE TITLE
Streams not always closed when reading in dex files

### ISSUE THREAD

**Issue by StevenArzt** [JesusFreke/smali#102]
When reading in dex files using the DexFileFactory.loadDexFileMethods(), a FileInputStream gets constructed and used, but never closed:

```
InputStream inputStream = new BufferedInputStream(new FileInputStream(dexFile));
```

This stream is kept dangling, leaving the file locked on Windows systems until the JVM finally terminates. If you want to use Dexlib and then move away the dex file when you're done, this will fail due to the retained lock on the file.

Proposed solution: Put this stream access into a try/finally block and close the stream in any case.

**Comment by JesusFreke** [comment]
SGTM, thanks for reporting! I'll get it fixed shortly.

**Comment by JesusFreke** [comment]
Fixed in https://github.com/JesusFreke/smali/commit/abd113eb3b0c564745c423b3c6460154ea0cda62
