### ISSUE TITLE
Strange file names when trying to baksmali classes

### ISSUE THREAD

**Issue by Max-Stern** [JesusFreke/smali#147]
I'm trying to get smali code from .dex file.
But I get files with strange Unicode names, for example:
![268](https://cloud.githubusercontent.com/assets/7532709/6946701/e26beddc-d8aa-11e4-8f07-5530130a689d.png)

Can you help?

And here is my apk: https://drive.google.com/file/d/0B545ZWMuoTjPQVMzS3pVTER2dk0/view?usp=sharing

**Comment by JesusFreke** [comment]
This looks pretty typical of various types of obfuscation. As far as rebuilding goes, smali should be able to reassemble the classes back into a dex file. But it looks like your problem might be with apktool instead - it handles packaging the manifest and resources.

**Comment by strazzere** [comment]
Just saw this one on my feed. It's also likely that this form of obfuscation is messing with the way Windows handles file names -- it's handled fine on *nix for the most part though.

**Comment by JesusFreke** [comment]
baksmali actually tries to detect if it's on a windows machine and/or on a case-insensitive filesystem, and it will append a '#' and/or a numeric suffix respectively. E.g. the "AUX#.smali" file in the screenshot would have been for a class named AUX. Based on the filenames in the screenshot, this functionality is working as expected.

**Comment by strazzere** [comment]
Oh neat, thanks for the information. I'd never run any of the tools on windows and assumed it would break there. Thanks!

**Comment by Max-Stern** [comment]
@JesusFreke @strazzere understood, thanks.
