### ISSUE TITLE
Deodexing android L preview framework files issue

### ISSUE THREAD

**Issue by JesusFreke** [JesusFreke/smali#269]
Original [issue 225](https://code.google.com/p/smali/issues/detail?id=225) created by JesusFreke on 2014-10-24T14:48:24.000Z:

I've extracted the dex files from oat and i'm trying to deodex them.
I'm encountering this issue with packet switch that prevents it to recompile successfully:

    .line 217
    .packed-switch 0x2bd0222
        +455938160
        +40435714
        +924766
        +1441792
        +196611
        -1779040253
        +21954681
        +24510464
        +1308295
        +1376264
        +1245448
        +476844123
        +1376264
        +646120020
        +582549876
        +151781396
        +270141458
        +565335
        +812515344
        +9578366
        +137955340
        +270663727
        +286923224
        +41314361
        +1113272
        +67964967
        +433590306
        +410521890
        -150994570
        +303693841
        +41192747
        +1177355
        +542380300
        +302523066
        +41156608
        +1177355
        +24383756
        +1177366
        +41292044
        +1113272
        +269291559
        +329784
        +797708402
        +270991368
        +581574740
        +4104
        +1048584
        +731783278
        +185335817
        -1293021071
        +51118088
        +798036082

**Comment by BMc08GT** [comment]
So far this has been working very well deodexing Android Lollipop applications
https://github.com/BMc08GT/scripts/blob/master/deodex-lollipop/README.md

**Comment by JesusFreke** [comment]
The dex2oat tool used there doesn't appear to be open source, so I can't comment on the validity of it. I have my doubts whether it will actually handle field offsets appropriately in all cases.

**Comment by Lekensteyn** [comment]
The source for the oat2dex tool seems available at:
https://github.com/testwhat/SmaliEx/tree/master/smaliex/src/main/java/org/rh/smaliex (in case that goes away, a copy is available at https://github.com/Lekensteyn/SmaliEx). (oh, testwhat = R.H = Riddle Hsu, the author?)

**Comment by testwhat** [comment]
Share latest version which has included stable sort.
https://github.com/testwhat/SmaliEx/commit/a1c1a004efeadd65c6a0e0abea25f0d1f72c91be

**Comment by JesusFreke** [comment]
baksmali now supports ART oat files for M+ devices. Older oat files with the unstable sorting issues will remain unsupported.

**Comment by ale5000-git** [comment]
@JesusFreke
Isn't possible to do in this way?
Run a command through adb shell to get how sorting is done on the phone and then add a parameter to baksmali to get the ordering (maybe from a file created on the phone with the first adb shell command).

You need to do only the last part then the user could do manually the first part (that can be scripted I think).

**Comment by JesusFreke** [comment]
@ale5000-git See my comment [here](https://github.com/JesusFreke/smali/issues/269#issuecomment-88567826)
