### ISSUE TITLE
Can't build on Windows using JDK 1.6/1.7/1.8

### ISSUE THREAD

**Issue by JesusFreke** [JesusFreke/smali#276]
Original [issue 232](https://code.google.com/p/smali/issues/detail?id=232) created by JesusFreke on 2014-12-21T08:24:08.000Z:

<b>What seems to be the problem?</b>
Can't build on Windows using JDK 1.6/1.7/1.8

<b>What is the exact smali/baksmali command that you ran?</b>
gradlew.bat build

<b>What version of smali/baksmali are you using? What rom are you working</b>
<b>from?</b>
2.0.3

<b>What is the airspeed velocity of an unladen swallow?</b>

<b>Please provide any additional information below: error messages, symptoms,</b>
<b>etc.</b>
I have tried jdk1.8.0_25(64 bit)/jdk1.7.0_65(64 bit)/jdk1.6.0_45(32 bit), but all of them give me the same error message like below
E:\code\android\smali&gt;gradlew.bat build
:util:compileJava UP-TO-DATE
:util:processResources UP-TO-DATE
:util:classes UP-TO-DATE
:util:jar UP-TO-DATE
:dexlib2:compileJava
E:\code\android\smali\dexlib2\src\main\java\org\jf\dexlib2\writer\builder\BuilderClassDef.java:83: e
rror: no suitable method found for copyOf(Iterable&lt;CAP#&nbsp;1&gt;)
        this.staticFields = ImmutableSortedSet.copyOf(Iterables.filter(fields, FieldUtil.FIELD_IS_ST
ATIC));
                                              ^
    method ImmutableSet.&lt;E#&nbsp;1&gt;copyOf(E#&nbsp;1[]) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to E#&nbsp;1[])
    method ImmutableSet.&lt;E#&nbsp;2&gt;copyOf(Iterable&lt;? extends E#&nbsp;2&gt;) is not applicable
      (cannot infer type-variable(s) E#&nbsp;2,T
        (argument mismatch; Iterable&lt;CAP#&nbsp;2&gt; cannot be converted to Iterable&lt;? extends CAP#&nbsp;2&gt;))
    method ImmutableSet.&lt;E#&nbsp;3&gt;copyOf(Iterator&lt;? extends E#&nbsp;3&gt;) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to Iterator&lt;? extends
 E#&nbsp;3&gt;)
    method ImmutableSet.&lt;E#&nbsp;4&gt;copyOf(Collection&lt;? extends E#&nbsp;4&gt;) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to Collection&lt;? exten
ds E#&nbsp;4&gt;)
    method ImmutableSortedSetFauxverideShim.&lt;E#&nbsp;5&gt;copyOf(E#&nbsp;5[]) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to E#&nbsp;5[])
    method ImmutableSortedSet.&lt;E#&nbsp;6&gt;copyOf(E#&nbsp;6[]) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to E#&nbsp;6[])
    method ImmutableSortedSet.&lt;E#&nbsp;7&gt;copyOf(Iterable&lt;? extends E#&nbsp;7&gt;) is not applicable
      (cannot infer type-variable(s) E#&nbsp;7,T
        (argument mismatch; Iterable&lt;CAP#&nbsp;3&gt; cannot be converted to Iterable&lt;? extends CAP#&nbsp;3&gt;))
    method ImmutableSortedSet.&lt;E#&nbsp;8&gt;copyOf(Collection&lt;? extends E#&nbsp;8&gt;) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to Collection&lt;? exten
ds E#&nbsp;8&gt;)
    method ImmutableSortedSet.&lt;E#&nbsp;9&gt;copyOf(Iterator&lt;? extends E#&nbsp;9&gt;) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to Iterator&lt;? extends
 E#&nbsp;9&gt;)
    method ImmutableSortedSet.&lt;E#&nbsp;10&gt;copyOf(Comparator&lt;? super E#&nbsp;10&gt;,Iterator&lt;? extends E#&nbsp;10&gt;) is not
 applicable
      (cannot infer type-variable(s) E#&nbsp;10
        (actual and formal argument lists differ in length))
    method ImmutableSortedSet.&lt;E#&nbsp;11&gt;copyOf(Comparator&lt;? super E#&nbsp;11&gt;,Iterable&lt;? extends E#&nbsp;11&gt;) is not
 applicable
      (cannot infer type-variable(s) E#&nbsp;11
        (actual and formal argument lists differ in length))
    method ImmutableSortedSet.&lt;E#&nbsp;12&gt;copyOf(Comparator&lt;? super E#&nbsp;12&gt;,Collection&lt;? extends E#&nbsp;12&gt;) is n
ot applicable
      (cannot infer type-variable(s) E#&nbsp;12
        (actual and formal argument lists differ in length))
  where E#&nbsp;1,T,E#&nbsp;2,E#&nbsp;3,E#&nbsp;4,E#&nbsp;5,E#&nbsp;6,E#&nbsp;7,E#&nbsp;8,E#&nbsp;9,E#&nbsp;10,E#&nbsp;11,E#&nbsp;12 are type-variables:
    E#&nbsp;1 extends Object declared in method &lt;E#&nbsp;1&gt;copyOf(E#&nbsp;1[])
    T extends Object declared in method &lt;T&gt;filter(Iterable&lt;T&gt;,Predicate&lt;? super T&gt;)
    E#&nbsp;2 extends Object declared in method &lt;E#&nbsp;2&gt;copyOf(Iterable&lt;? extends E#&nbsp;2&gt;)
    E#&nbsp;3 extends Object declared in method &lt;E#&nbsp;3&gt;copyOf(Iterator&lt;? extends E#&nbsp;3&gt;)
    E#&nbsp;4 extends Object declared in method &lt;E#&nbsp;4&gt;copyOf(Collection&lt;? extends E#&nbsp;4&gt;)
    E#&nbsp;5 extends Object declared in method &lt;E#&nbsp;5&gt;copyOf(E#&nbsp;5[])
    E#&nbsp;6 extends Comparable&lt;? super E#&nbsp;6&gt; declared in method &lt;E#&nbsp;6&gt;copyOf(E#&nbsp;6[])
    E#&nbsp;7 extends Object declared in method &lt;E#&nbsp;7&gt;copyOf(Iterable&lt;? extends E#&nbsp;7&gt;)
    E#&nbsp;8 extends Object declared in method &lt;E#&nbsp;8&gt;copyOf(Collection&lt;? extends E#&nbsp;8&gt;)
    E#&nbsp;9 extends Object declared in method &lt;E#&nbsp;9&gt;copyOf(Iterator&lt;? extends E#&nbsp;9&gt;)
    E#&nbsp;10 extends Object declared in method &lt;E#&nbsp;10&gt;copyOf(Comparator&lt;? super E#&nbsp;10&gt;,Iterator&lt;? extends
E#&nbsp;10&gt;)
    E#&nbsp;11 extends Object declared in method &lt;E#&nbsp;11&gt;copyOf(Comparator&lt;? super E#&nbsp;11&gt;,Iterable&lt;? extends
E#&nbsp;11&gt;)
    E#&nbsp;12 extends Object declared in method &lt;E#&nbsp;12&gt;copyOf(Comparator&lt;? super E#&nbsp;12&gt;,Collection&lt;? extend
s E#&nbsp;12&gt;)
  where CAP#&nbsp;1,CAP#&nbsp;2,CAP#&nbsp;3 are fresh type-variables:
    CAP#&nbsp;1 extends BuilderField from capture of ? extends BuilderField
    CAP#&nbsp;2 extends BuilderField from capture of ? extends BuilderField
    CAP#&nbsp;3 extends BuilderField from capture of ? extends BuilderField
E:\code\android\smali\dexlib2\src\main\java\org\jf\dexlib2\writer\builder\BuilderClassDef.java:84: e
rror: no suitable method found for copyOf(Iterable&lt;CAP#&nbsp;1&gt;)
        this.instanceFields = ImmutableSortedSet.copyOf(Iterables.filter(fields, FieldUtil.FIELD_IS_
INSTANCE));
                                                ^
    method ImmutableSet.&lt;E#&nbsp;1&gt;copyOf(E#&nbsp;1[]) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to E#&nbsp;1[])
    method ImmutableSet.&lt;E#&nbsp;2&gt;copyOf(Iterable&lt;? extends E#&nbsp;2&gt;) is not applicable
      (cannot infer type-variable(s) E#&nbsp;2,T
        (argument mismatch; Iterable&lt;CAP#&nbsp;2&gt; cannot be converted to Iterable&lt;? extends CAP#&nbsp;2&gt;))
    method ImmutableSet.&lt;E#&nbsp;3&gt;copyOf(Iterator&lt;? extends E#&nbsp;3&gt;) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to Iterator&lt;? extends
 E#&nbsp;3&gt;)
    method ImmutableSet.&lt;E#&nbsp;4&gt;copyOf(Collection&lt;? extends E#&nbsp;4&gt;) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to Collection&lt;? exten
ds E#&nbsp;4&gt;)
    method ImmutableSortedSetFauxverideShim.&lt;E#&nbsp;5&gt;copyOf(E#&nbsp;5[]) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to E#&nbsp;5[])
    method ImmutableSortedSet.&lt;E#&nbsp;6&gt;copyOf(E#&nbsp;6[]) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to E#&nbsp;6[])
    method ImmutableSortedSet.&lt;E#&nbsp;7&gt;copyOf(Iterable&lt;? extends E#&nbsp;7&gt;) is not applicable
      (cannot infer type-variable(s) E#&nbsp;7,T
        (argument mismatch; Iterable&lt;CAP#&nbsp;3&gt; cannot be converted to Iterable&lt;? extends CAP#&nbsp;3&gt;))
    method ImmutableSortedSet.&lt;E#&nbsp;8&gt;copyOf(Collection&lt;? extends E#&nbsp;8&gt;) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to Collection&lt;? exten
ds E#&nbsp;8&gt;)
    method ImmutableSortedSet.&lt;E#&nbsp;9&gt;copyOf(Iterator&lt;? extends E#&nbsp;9&gt;) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to Iterator&lt;? extends
 E#&nbsp;9&gt;)
    method ImmutableSortedSet.&lt;E#&nbsp;10&gt;copyOf(Comparator&lt;? super E#&nbsp;10&gt;,Iterator&lt;? extends E#&nbsp;10&gt;) is not
 applicable
      (cannot infer type-variable(s) E#&nbsp;10
        (actual and formal argument lists differ in length))
    method ImmutableSortedSet.&lt;E#&nbsp;11&gt;copyOf(Comparator&lt;? super E#&nbsp;11&gt;,Iterable&lt;? extends E#&nbsp;11&gt;) is not
 applicable
      (cannot infer type-variable(s) E#&nbsp;11
        (actual and formal argument lists differ in length))
    method ImmutableSortedSet.&lt;E#&nbsp;12&gt;copyOf(Comparator&lt;? super E#&nbsp;12&gt;,Collection&lt;? extends E#&nbsp;12&gt;) is n
ot applicable
      (cannot infer type-variable(s) E#&nbsp;12
        (actual and formal argument lists differ in length))
  where E#&nbsp;1,T,E#&nbsp;2,E#&nbsp;3,E#&nbsp;4,E#&nbsp;5,E#&nbsp;6,E#&nbsp;7,E#&nbsp;8,E#&nbsp;9,E#&nbsp;10,E#&nbsp;11,E#&nbsp;12 are type-variables:
    E#&nbsp;1 extends Object declared in method &lt;E#&nbsp;1&gt;copyOf(E#&nbsp;1[])
    T extends Object declared in method &lt;T&gt;filter(Iterable&lt;T&gt;,Predicate&lt;? super T&gt;)
    E#&nbsp;2 extends Object declared in method &lt;E#&nbsp;2&gt;copyOf(Iterable&lt;? extends E#&nbsp;2&gt;)
    E#&nbsp;3 extends Object declared in method &lt;E#&nbsp;3&gt;copyOf(Iterator&lt;? extends E#&nbsp;3&gt;)
    E#&nbsp;4 extends Object declared in method &lt;E#&nbsp;4&gt;copyOf(Collection&lt;? extends E#&nbsp;4&gt;)
    E#&nbsp;5 extends Object declared in method &lt;E#&nbsp;5&gt;copyOf(E#&nbsp;5[])
    E#&nbsp;6 extends Comparable&lt;? super E#&nbsp;6&gt; declared in method &lt;E#&nbsp;6&gt;copyOf(E#&nbsp;6[])
    E#&nbsp;7 extends Object declared in method &lt;E#&nbsp;7&gt;copyOf(Iterable&lt;? extends E#&nbsp;7&gt;)
    E#&nbsp;8 extends Object declared in method &lt;E#&nbsp;8&gt;copyOf(Collection&lt;? extends E#&nbsp;8&gt;)
    E#&nbsp;9 extends Object declared in method &lt;E#&nbsp;9&gt;copyOf(Iterator&lt;? extends E#&nbsp;9&gt;)
    E#&nbsp;10 extends Object declared in method &lt;E#&nbsp;10&gt;copyOf(Comparator&lt;? super E#&nbsp;10&gt;,Iterator&lt;? extends
E#&nbsp;10&gt;)
    E#&nbsp;11 extends Object declared in method &lt;E#&nbsp;11&gt;copyOf(Comparator&lt;? super E#&nbsp;11&gt;,Iterable&lt;? extends
E#&nbsp;11&gt;)
    E#&nbsp;12 extends Object declared in method &lt;E#&nbsp;12&gt;copyOf(Comparator&lt;? super E#&nbsp;12&gt;,Collection&lt;? extend
s E#&nbsp;12&gt;)
  where CAP#&nbsp;1,CAP#&nbsp;2,CAP#&nbsp;3 are fresh type-variables:
    CAP#&nbsp;1 extends BuilderField from capture of ? extends BuilderField
    CAP#&nbsp;2 extends BuilderField from capture of ? extends BuilderField
    CAP#&nbsp;3 extends BuilderField from capture of ? extends BuilderField
E:\code\android\smali\dexlib2\src\main\java\org\jf\dexlib2\writer\builder\BuilderClassDef.java:85: e
rror: no suitable method found for copyOf(Iterable&lt;CAP#&nbsp;1&gt;)
        this.directMethods = ImmutableSortedSet.copyOf(Iterables.filter(methods, MethodUtil.METHOD_I
S_DIRECT));
                                               ^
    method ImmutableSet.&lt;E#&nbsp;1&gt;copyOf(E#&nbsp;1[]) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to E#&nbsp;1[])
    method ImmutableSet.&lt;E#&nbsp;2&gt;copyOf(Iterable&lt;? extends E#&nbsp;2&gt;) is not applicable
      (cannot infer type-variable(s) E#&nbsp;2,T
        (argument mismatch; Iterable&lt;CAP#&nbsp;2&gt; cannot be converted to Iterable&lt;? extends CAP#&nbsp;2&gt;))
    method ImmutableSet.&lt;E#&nbsp;3&gt;copyOf(Iterator&lt;? extends E#&nbsp;3&gt;) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to Iterator&lt;? extends
 E#&nbsp;3&gt;)
    method ImmutableSet.&lt;E#&nbsp;4&gt;copyOf(Collection&lt;? extends E#&nbsp;4&gt;) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to Collection&lt;? exten
ds E#&nbsp;4&gt;)
    method ImmutableSortedSetFauxverideShim.&lt;E#&nbsp;5&gt;copyOf(E#&nbsp;5[]) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to E#&nbsp;5[])
    method ImmutableSortedSet.&lt;E#&nbsp;6&gt;copyOf(E#&nbsp;6[]) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to E#&nbsp;6[])
    method ImmutableSortedSet.&lt;E#&nbsp;7&gt;copyOf(Iterable&lt;? extends E#&nbsp;7&gt;) is not applicable
      (cannot infer type-variable(s) E#&nbsp;7,T
        (argument mismatch; Iterable&lt;CAP#&nbsp;3&gt; cannot be converted to Iterable&lt;? extends CAP#&nbsp;3&gt;))
    method ImmutableSortedSet.&lt;E#&nbsp;8&gt;copyOf(Collection&lt;? extends E#&nbsp;8&gt;) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to Collection&lt;? exten
ds E#&nbsp;8&gt;)
    method ImmutableSortedSet.&lt;E#&nbsp;9&gt;copyOf(Iterator&lt;? extends E#&nbsp;9&gt;) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to Iterator&lt;? extends
 E#&nbsp;9&gt;)
    method ImmutableSortedSet.&lt;E#&nbsp;10&gt;copyOf(Comparator&lt;? super E#&nbsp;10&gt;,Iterator&lt;? extends E#&nbsp;10&gt;) is not
 applicable
      (cannot infer type-variable(s) E#&nbsp;10
        (actual and formal argument lists differ in length))
    method ImmutableSortedSet.&lt;E#&nbsp;11&gt;copyOf(Comparator&lt;? super E#&nbsp;11&gt;,Iterable&lt;? extends E#&nbsp;11&gt;) is not
 applicable
      (cannot infer type-variable(s) E#&nbsp;11
        (actual and formal argument lists differ in length))
    method ImmutableSortedSet.&lt;E#&nbsp;12&gt;copyOf(Comparator&lt;? super E#&nbsp;12&gt;,Collection&lt;? extends E#&nbsp;12&gt;) is n
ot applicable
      (cannot infer type-variable(s) E#&nbsp;12
        (actual and formal argument lists differ in length))
  where E#&nbsp;1,T,E#&nbsp;2,E#&nbsp;3,E#&nbsp;4,E#&nbsp;5,E#&nbsp;6,E#&nbsp;7,E#&nbsp;8,E#&nbsp;9,E#&nbsp;10,E#&nbsp;11,E#&nbsp;12 are type-variables:
    E#&nbsp;1 extends Object declared in method &lt;E#&nbsp;1&gt;copyOf(E#&nbsp;1[])
    T extends Object declared in method &lt;T&gt;filter(Iterable&lt;T&gt;,Predicate&lt;? super T&gt;)
    E#&nbsp;2 extends Object declared in method &lt;E#&nbsp;2&gt;copyOf(Iterable&lt;? extends E#&nbsp;2&gt;)
    E#&nbsp;3 extends Object declared in method &lt;E#&nbsp;3&gt;copyOf(Iterator&lt;? extends E#&nbsp;3&gt;)
    E#&nbsp;4 extends Object declared in method &lt;E#&nbsp;4&gt;copyOf(Collection&lt;? extends E#&nbsp;4&gt;)
    E#&nbsp;5 extends Object declared in method &lt;E#&nbsp;5&gt;copyOf(E#&nbsp;5[])
    E#&nbsp;6 extends Comparable&lt;? super E#&nbsp;6&gt; declared in method &lt;E#&nbsp;6&gt;copyOf(E#&nbsp;6[])
    E#&nbsp;7 extends Object declared in method &lt;E#&nbsp;7&gt;copyOf(Iterable&lt;? extends E#&nbsp;7&gt;)
    E#&nbsp;8 extends Object declared in method &lt;E#&nbsp;8&gt;copyOf(Collection&lt;? extends E#&nbsp;8&gt;)
    E#&nbsp;9 extends Object declared in method &lt;E#&nbsp;9&gt;copyOf(Iterator&lt;? extends E#&nbsp;9&gt;)
    E#&nbsp;10 extends Object declared in method &lt;E#&nbsp;10&gt;copyOf(Comparator&lt;? super E#&nbsp;10&gt;,Iterator&lt;? extends
E#&nbsp;10&gt;)
    E#&nbsp;11 extends Object declared in method &lt;E#&nbsp;11&gt;copyOf(Comparator&lt;? super E#&nbsp;11&gt;,Iterable&lt;? extends
E#&nbsp;11&gt;)
    E#&nbsp;12 extends Object declared in method &lt;E#&nbsp;12&gt;copyOf(Comparator&lt;? super E#&nbsp;12&gt;,Collection&lt;? extend
s E#&nbsp;12&gt;)
  where CAP#&nbsp;1,CAP#&nbsp;2,CAP#&nbsp;3 are fresh type-variables:
    CAP#&nbsp;1 extends BuilderMethod from capture of ? extends BuilderMethod
    CAP#&nbsp;2 extends BuilderMethod from capture of ? extends BuilderMethod
    CAP#&nbsp;3 extends BuilderMethod from capture of ? extends BuilderMethod
E:\code\android\smali\dexlib2\src\main\java\org\jf\dexlib2\writer\builder\BuilderClassDef.java:86: e
rror: no suitable method found for copyOf(Iterable&lt;CAP#&nbsp;1&gt;)
        this.virtualMethods = ImmutableSortedSet.copyOf(Iterables.filter(methods, MethodUtil.METHOD_
IS_VIRTUAL));
                                                ^
    method ImmutableSet.&lt;E#&nbsp;1&gt;copyOf(E#&nbsp;1[]) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to E#&nbsp;1[])
    method ImmutableSet.&lt;E#&nbsp;2&gt;copyOf(Iterable&lt;? extends E#&nbsp;2&gt;) is not applicable
      (cannot infer type-variable(s) E#&nbsp;2,T
        (argument mismatch; Iterable&lt;CAP#&nbsp;2&gt; cannot be converted to Iterable&lt;? extends CAP#&nbsp;2&gt;))
    method ImmutableSet.&lt;E#&nbsp;3&gt;copyOf(Iterator&lt;? extends E#&nbsp;3&gt;) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to Iterator&lt;? extends
 E#&nbsp;3&gt;)
    method ImmutableSet.&lt;E#&nbsp;4&gt;copyOf(Collection&lt;? extends E#&nbsp;4&gt;) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to Collection&lt;? exten
ds E#&nbsp;4&gt;)
    method ImmutableSortedSetFauxverideShim.&lt;E#&nbsp;5&gt;copyOf(E#&nbsp;5[]) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to E#&nbsp;5[])
    method ImmutableSortedSet.&lt;E#&nbsp;6&gt;copyOf(E#&nbsp;6[]) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to E#&nbsp;6[])
    method ImmutableSortedSet.&lt;E#&nbsp;7&gt;copyOf(Iterable&lt;? extends E#&nbsp;7&gt;) is not applicable
      (cannot infer type-variable(s) E#&nbsp;7,T
        (argument mismatch; Iterable&lt;CAP#&nbsp;3&gt; cannot be converted to Iterable&lt;? extends CAP#&nbsp;3&gt;))
    method ImmutableSortedSet.&lt;E#&nbsp;8&gt;copyOf(Collection&lt;? extends E#&nbsp;8&gt;) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to Collection&lt;? exten
ds E#&nbsp;8&gt;)
    method ImmutableSortedSet.&lt;E#&nbsp;9&gt;copyOf(Iterator&lt;? extends E#&nbsp;9&gt;) is not applicable
      (no instance(s) of type variable(s) T exist so that Iterable&lt;T&gt; conforms to Iterator&lt;? extends
 E#&nbsp;9&gt;)
    method ImmutableSortedSet.&lt;E#&nbsp;10&gt;copyOf(Comparator&lt;? super E#&nbsp;10&gt;,Iterator&lt;? extends E#&nbsp;10&gt;) is not
 applicable
      (cannot infer type-variable(s) E#&nbsp;10
        (actual and formal argument lists differ in length))
    method ImmutableSortedSet.&lt;E#&nbsp;11&gt;copyOf(Comparator&lt;? super E#&nbsp;11&gt;,Iterable&lt;? extends E#&nbsp;11&gt;) is not
 applicable
      (cannot infer type-variable(s) E#&nbsp;11
        (actual and formal argument lists differ in length))
    method ImmutableSortedSet.&lt;E#&nbsp;12&gt;copyOf(Comparator&lt;? super E#&nbsp;12&gt;,Collection&lt;? extends E#&nbsp;12&gt;) is n
ot applicable
      (cannot infer type-variable(s) E#&nbsp;12
        (actual and formal argument lists differ in length))
  where E#&nbsp;1,T,E#&nbsp;2,E#&nbsp;3,E#&nbsp;4,E#&nbsp;5,E#&nbsp;6,E#&nbsp;7,E#&nbsp;8,E#&nbsp;9,E#&nbsp;10,E#&nbsp;11,E#&nbsp;12 are type-variables:
    E#&nbsp;1 extends Object declared in method &lt;E#&nbsp;1&gt;copyOf(E#&nbsp;1[])
    T extends Object declared in method &lt;T&gt;filter(Iterable&lt;T&gt;,Predicate&lt;? super T&gt;)
    E#&nbsp;2 extends Object declared in method &lt;E#&nbsp;2&gt;copyOf(Iterable&lt;? extends E#&nbsp;2&gt;)
    E#&nbsp;3 extends Object declared in method &lt;E#&nbsp;3&gt;copyOf(Iterator&lt;? extends E#&nbsp;3&gt;)
    E#&nbsp;4 extends Object declared in method &lt;E#&nbsp;4&gt;copyOf(Collection&lt;? extends E#&nbsp;4&gt;)
    E#&nbsp;5 extends Object declared in method &lt;E#&nbsp;5&gt;copyOf(E#&nbsp;5[])
    E#&nbsp;6 extends Comparable&lt;? super E#&nbsp;6&gt; declared in method &lt;E#&nbsp;6&gt;copyOf(E#&nbsp;6[])
    E#&nbsp;7 extends Object declared in method &lt;E#&nbsp;7&gt;copyOf(Iterable&lt;? extends E#&nbsp;7&gt;)
    E#&nbsp;8 extends Object declared in method &lt;E#&nbsp;8&gt;copyOf(Collection&lt;? extends E#&nbsp;8&gt;)
    E#&nbsp;9 extends Object declared in method &lt;E#&nbsp;9&gt;copyOf(Iterator&lt;? extends E#&nbsp;9&gt;)
    E#&nbsp;10 extends Object declared in method &lt;E#&nbsp;10&gt;copyOf(Comparator&lt;? super E#&nbsp;10&gt;,Iterator&lt;? extends
E#&nbsp;10&gt;)
    E#&nbsp;11 extends Object declared in method &lt;E#&nbsp;11&gt;copyOf(Comparator&lt;? super E#&nbsp;11&gt;,Iterable&lt;? extends
E#&nbsp;11&gt;)
    E#&nbsp;12 extends Object declared in method &lt;E#&nbsp;12&gt;copyOf(Comparator&lt;? super E#&nbsp;12&gt;,Collection&lt;? extend
s E#&nbsp;12&gt;)
  where CAP#&nbsp;1,CAP#&nbsp;2,CAP#&nbsp;3 are fresh type-variables:
    CAP#&nbsp;1 extends BuilderMethod from capture of ? extends BuilderMethod
    CAP#&nbsp;2 extends BuilderMethod from capture of ? extends BuilderMethod
    CAP#&nbsp;3 extends BuilderMethod from capture of ? extends BuilderMethod
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors
:dexlib2:compileJava FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':dexlib2:compileJava'.
  &gt; Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more l
  og output.

BUILD FAILED

Total time: 23.252 secs

E:\code\android\smali&gt;

**Comment by Aaahh** [comment]
Hitting this bug again, this time on Ubuntu

**Comment by Aaahh** [comment]
works if I use trusty instead of precise

**Comment by ApatheticsAnonymous** [comment]
I think this is a JDK bug or related issue. I had the exact same issue and resolved it w/ updating my Java8 from update 30 to update > 80
