### ISSUE TITLE
OS X 10.10.3 decode files issue

### ISSUE THREAD

**Issue by pwelyn** [JesusFreke/smali#288]
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

OS X 10.10.3

java -Xmx512m -jar smali-2.0.6.jar classes -o classes.dex

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Cannot find file or directory "classes"
	at org.jf.smali.main.main(main.java:179)

java -Xmx512m -jar smali-2.0.6.jar out -o classes.dex

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Cannot find file or directory "out"
	at org.jf.smali.main.main(main.java:179)
 
smali -JXmx512m out -o classes.dex 

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Cannot find file or directory "out"
	at org.jf.smali.main.main(main.java:179)

**Comment by CalebFenton** [comment]
The title of your issue says you're trying to decode things. In that case, you want to use baksmali, which is for decompiling. The smali jar is for compiling smali files.

`java -jar baksmali-2.0.6.jar classes.dex`

And for more help,
`java -jar baksmali-2.0.6.jar -h`

**Comment by pwelyn** [comment]
Thanks!
