### ISSUE TITLE
"gradlew.bat":Line 35: the "set JAVA_HOME=%JAVA_HOME:"=%", the cmd do what

### ISSUE THREAD

**Issue by enali** [JesusFreke/smali#294]
I want to run `gradle clean build`, but I see the file `gradlew.bat` file.
when I build the `apktool` util, I run the `gradlew.bat build fatJar` according the official guide. 
So I think the `gradlew.bat` file is important, and is the right cmd to build `smail` util. 
But I open it, and read the `bat` cmd, until line 35. 
It's strange, I can't understant it. I can't find any info about it by google or baidu.
Can you tell me?

**Comment by JesusFreke** [comment]
gradlew.bat is the standard gradle wrapper. See e.g. https://docs.gradle.org/current/userguide/gradle_wrapper.html

On windows, you use gradlew.bat batch file, on anything else, you use the gradlew shell script.
