### ISSUE TITLE
Deodexed Samsung TW Roms (OFJ) 5.1.1 causes FC on NfcNci

### ISSUE THREAD

**Issue by wanam** [JesusFreke/smali#295]
I'm sorry to duplicate this bug (https://github.com/testwhat/SmaliEx/issues/1), but i tough this should be the correct place:

Deodexed with no errors using @svadev tool (http://forum.xda-developers.com/galaxy-s5/general/tool-deodex-tool-android-l-t2972025/post57471606#post57471606) against your master branch, 0.81 and 0.7 version of https://github.com/testwhat/SmaliEx, but all of them causes many hangs at boot resulting on a continuous NfcNci FC.

NfcNci (odexed + deodexed) can be downloaded here: https://www.dropbox.com/sh/eroyj74t559w8qi/AABwEeSVEnCV83uYwMRjzLoia?dl=0

It seems to be a wrong type issue on the result of dex2oat on NfcNci and framework.jar:
_________________________________________________
I/dex2oat ( 6112): /system/bin/dex2oat --zip-fd=11 --zip-location=/system/app/NfcNci/NfcNci.apk --oat-fd=12 --art-fd=13 --compress-image --oat-location=/data/dalvik-cache/arm64/system@app@NfcNci@NfcNci.apk@classes.dex --instruction-set=arm64 --instruction-set-features=default --runtime-arg -Xms64m --runtime-arg -Xmx512m --swap-fd=15

I/dex2oat ( 6112): Decided to run without swap.

I/dex2oat ( 6112): Verification error in void com.android.nfc.beam.SendUi.(android.content.Context, com.android.nfc.beam.SendUi$Callback)

I/dex2oat ( 6112): void com.android.nfc.beam.SendUi.(android.content.Context, com.android.nfc.beam.SendUi$Callback) failed to verify: void com.android.nfc.beam.SendUi.(android.content.Context, com.android.nfc.beam.SendUi$Callback): [0xF7] register v3 has type Float but expected Integer

E/dex2oat ( 6112): Verification failed on class com.android.nfc.beam.SendUi in /system/app/NfcNci/NfcNci.apk because: Verifier rejected class com.android.nfc.beam.SendUi due to bad method void com.android.nfc.beam.SendUi.(android.content.Context, com.android.nfc.beam.SendUi$Callback)
_________________________________________________
06-29 13:40:11.140 3725 3727 I dex2oat : Verification error in void android.widget.NumberPicker.(android.content.Context, android.util.AttributeSet, int, int)
06-29 13:40:11.140 3725 3727 I dex2oat : void android.widget.NumberPicker.(android.content.Context, android.util.AttributeSet, int, int) failed to verify: void android.widget.NumberPicker.(android.content.Context, android.util.AttributeSet, int, int): [0x176] unexpected value in v0 of type Integer but expected Float for put
06-29 13:40:11.160 3725 3727 E dex2oat : Verification failed on class android.widget.NumberPicker in /system/framework/framework.jar:classes2.dex because: Verifier rejected class android.widget.NumberPicker due to bad method void android.widget.NumberPicker.(android.content.Context, android.util.AttributeSet, int, int)

**Comment by JesusFreke** [comment]
baksmali doesn't currently support deodexing art odexs/oats :)
