### ISSUE TITLE
how to compile the smalidea plugin from the Source Code

### ISSUE THREAD

**Issue by czfree** [JesusFreke/smali#299]
I want to compile the smalidea plugin from the Source Code . What should I do ?
the smalidea\build.gradle say:
// We can't actually compile the plugin with gradle, so we just disable everything
// except the tasks related to generating the IDEA module and ANTLR parser

**Comment by JesusFreke** [comment]
You have to make an IDEA project using "gradle idea" from the root smali project directory, open it in IDEA and build the plugin from within IDEA

**Comment by Spainman** [comment]
I'm trying to build smalidea from source too. Is the information on running the 'idea' task and then loading the project in IDEA still current? I tried just that using IDEA 2016.2.3 (loaded the resulting smali.ipr) and Smalidea does not seem to be marked as a module (bold in project structure tree) and isn't build either.

I would really appreciate some help on how to actually successfully build smalidea. What's the reference setup (IDEA version, JDK, any other dependencies) and what are the steps? Thanks a lot!

**Comment by JesusFreke** [comment]
You should be able to do a "gr build" from within the smalidea directory to build it. And if you want to open the project in IDEA, run "gr idea" from within the smalidea directory.

Make sure you do both gr build and gr idea from within the smalidea directory. I have the gradle build set up to skip the smalidea directory unless you're actually running a gradle command in that directory.

**Comment by Spainman** [comment]
Great. Building worked just fine and the plugin zip file was successfully generated. Will try the idea task later... Thank you!

**Comment by bakrehsan** [comment]
@Spainman please can you give us a link for the plugin zip file?

**Comment by Spainman** [comment]
Assuming you are asking for the path: Building with gradlew puts the plugin zip in ..../smalidea/build/distributions

**Comment by bakrehsan** [comment]
thanks a lot but i just started learning gradle and tried to build smalidea with gradlew and also with gradle which i installed but non of them worked with me either build fails with exception or smalidea is skipped 
can you tell me please how did you do it?  thank you again #@Spainman

**Comment by JesusFreke** [comment]
It should be as easy as

    cd smali/smalidea
    gr build

**Comment by bakrehsan** [comment]
thanks a lot but when i do this it says gradlew is not recognized as an internal or external command
because there is no gradlew files inside smalidea , and those gradlew files outside skips the build of smalidea thank you again @JesusFreke

**Comment by JesusFreke** [comment]
Sorry, it should be "../gradlew build"

**Comment by candledragle** [comment]
@JesusFreke 
cd smali/smalidea
../gradlew build

I get the error 

`error(5):  directory not found: /home/sym/Documents/github/smali/smalidea/build/tokens/org/jf/smali
error(3):  cannot find tokens file /home/sym/Documents/github/smali/smalidea/build/generated-src/antlr/main/org/jf/smalidea/smaliParser.tokens
:smalidea:generateGrammarSource FAILED
`

**Comment by thejunkjon** [comment]
@candledragle , try this from the root of the project.

`./gradlew :smaliidea:clean :smaliidea:build`
