### ISSUE TITLE
Unsigned short value out of range

### ISSUE THREAD

**Issue by joesecurity** [JesusFreke/smali#301]
We are using smali 2.0.6 and are having an issue with generating dex code:

UNEXPECTED TOP-LEVEL EXCEPTION:
org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65716
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:315)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:997)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:773)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:222)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:200)
	at org.jf.smali.main.main(main.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at joeboxutils.common.utils.ProcessUtils$1.run(ProcessUtils.java:148)
	at java.lang.Thread.run(Thread.java:745)

It seems this is not related to the maximal number of methods, but rather a method index issue:

public void write(Instruction35c instruction)
  {
    try
    {
      this.writer.write(instruction.getOpcode().value);
      this.writer.write(packNibbles(instruction.getRegisterG(), instruction.getRegisterCount()));
-->      this.writer.writeUshort(getReferenceIndex(instruction));
      this.writer.write(packNibbles(instruction.getRegisterC(), instruction.getRegisterD()));
      this.writer.write(packNibbles(instruction.getRegisterE(), instruction.getRegisterF()));
    }
    catch (IOException ex)
    {
      throw new RuntimeException(ex);
    }
  }

  private int getReferenceIndex(ReferenceInstruction referenceInstruction)
  {
    switch (referenceInstruction.getOpcode().referenceType)
    {
    case 2: 
      return this.fieldSection.getItemIndex((FieldReference)referenceInstruction.getReference());
    case 3: 
      return this.methodSection.getItemIndex((MethodReference)referenceInstruction.getReference());
    case 0: 
      return this.stringSection.getItemIndex((StringReference)referenceInstruction.getReference());
    case 1: 
      return this.typeSection.getItemIndex((TypeReference)referenceInstruction.getReference());
    }
    throw new ExceptionWithContext("Unknown reference type: %d", new Object[] { Integer.valueOf(referenceInstruction.getOpcode().referenceType) });
  }

Any idea what could be problem and how we could fix it?

**Comment by JesusFreke** [comment]
A "method index problem" is exactly what having too many methods will cause :). If you have too many methods, then the method index can't fit into an unsigned 16-bit value, and this is the error that you get.

**Comment by joesecurity** [comment]
Is there some way to measure this? E.g. my current APK has 52387 methods and generates an error.

**Comment by CalebFenton** [comment]
Are you counting methods from Java or Smali? Source code doesn't include
synthetic methods, but smali does. That might account for some methods, but
10 thousand seems like a lot.

**Comment by JesusFreke** [comment]
I could add in a preemptive check for the counts of the indexed items before writing out a dex file, and print a warning with, e.g. the actual number of methods.

**Comment by JesusFreke** [comment]
Actually, I guess it might be useful to have the actual list of methods, in order to be able to do some analysis on where they're coming from. I might be able to add something to smali to write out the list of methods/fields/etc. to a file.

You can also try my solution here: http://stackoverflow.com/a/17098651

**Comment by joesecurity** [comment]
Here is an example, not sure why smali blows it up that much:

 find * -type d -print -exec sh -c "java -jar ../smali-2.0.6.jar {} -o {}/classes.dex && sh -c \"/opt/adt-bundle-linux-x86_64/sdk/platform-tools/dexdump -f {}/classes.dex | grep method_ids_size\"" \;
com.cleanmaster.mguard.apk.smali.patched

UNEXPECTED TOP-LEVEL EXCEPTION:
org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65765
        at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:315)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:997)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:773)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:222)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:200)
        at org.jf.smali.main.main(main.java:235)

com.cleanmaster.mguard.apk.smali.patched/android
method_ids_size     : 1638
com.cleanmaster.mguard.apk.smali.patched/android/content
method_ids_size     : 35
com.cleanmaster.mguard.apk.smali.patched/android/content/pm
method_ids_size     : 35
com.cleanmaster.mguard.apk.smali.patched/android/support
method_ids_size     : 1608
com.cleanmaster.mguard.apk.smali.patched/android/support/v4
method_ids_size     : 1608
com.cleanmaster.mguard.apk.smali.patched/android/support/v4/app
method_ids_size     : 735
com.cleanmaster.mguard.apk.smali.patched/android/support/v4/provider
method_ids_size     : 14
com.cleanmaster.mguard.apk.smali.patched/android/support/v4/content
method_ids_size     : 112
com.cleanmaster.mguard.apk.smali.patched/android/support/v4/view
method_ids_size     : 317
com.cleanmaster.mguard.apk.smali.patched/android/support/v4/util
method_ids_size     : 278
com.cleanmaster.mguard.apk.smali.patched/android/support/v4/widget
method_ids_size     : 320
com.cleanmaster.mguard.apk.smali.patched/client
method_ids_size     : 158
com.cleanmaster.mguard.apk.smali.patched/client/core
method_ids_size     : 158
com.cleanmaster.mguard.apk.smali.patched/client/core/model
method_ids_size     : 97
com.cleanmaster.mguard.apk.smali.patched/com
method_ids_size     : 63992
com.cleanmaster.mguard.apk.smali.patched/com/android
method_ids_size     : 82
com.cleanmaster.mguard.apk.smali.patched/com/android/volley
method_ids_size     : 82
com.cleanmaster.mguard.apk.smali.patched/com/android/volley/toolbox
method_ids_size     : 1
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan
method_ids_size     : 2774
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/a
method_ids_size     : 0
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/a/a
method_ids_size     : 0
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/screensavershared
method_ids_size     : 445
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/screensavershared/base
method_ids_size     : 188
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/screensavershared/base/event
method_ids_size     : 13
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/screensavershared/a
method_ids_size     : 58
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/screensavershared/b
method_ids_size     : 51
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/screensavershared/mutual
method_ids_size     : 237
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/rt
method_ids_size     : 190
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/rt/common
method_ids_size     : 190
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/cloudconfig
method_ids_size     : 201
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/cloudconfig/a
method_ids_size     : 11
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/cloudconfig/ipc
method_ids_size     : 38
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/cloudconfig/deepcloudconfig
method_ids_size     : 152
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/cloudconfig/c
method_ids_size     : 16
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/screensaverold
method_ids_size     : 7
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/screensaverold/base
method_ids_size     : 3
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/screensaverold/mutual
method_ids_size     : 3
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/screensavernew
method_ids_size     : 302
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/screensavernew/a
method_ids_size     : 18
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/screensavernew/util
method_ids_size     : 91
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/locker
method_ids_size     : 34
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user
method_ids_size     : 451
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/a
method_ids_size     : 8
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/a/a
method_ids_size     : 8
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/a/a/a
method_ids_size     : 8
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/core
method_ids_size     : 446
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/core/a
method_ids_size     : 16
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/core/a/a
method_ids_size     : 16
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/core/b
method_ids_size     : 55
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/core/b/a
method_ids_size     : 55
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/core/sdk
method_ids_size     : 101
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/core/sdk/a
method_ids_size     : 33
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/core/sdk/ssologin
method_ids_size     : 71
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/core/net
method_ids_size     : 320
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/core/net/a
method_ids_size     : 16
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/core/net/a/a
method_ids_size     : 16
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/core/net/d
method_ids_size     : 5
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/core/net/e
method_ids_size     : 211
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/core/net/c
method_ids_size     : 99
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/user/core/net/utils
method_ids_size     : 14
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/notificationlib
method_ids_size     : 154
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/notificationlib/notificationhelper
method_ids_size     : 154
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/notificationlib/notificationhelper/ui
method_ids_size     : 32
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/cleaner
method_ids_size     : 1342
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/cleaner/a
method_ids_size     : 26
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/cleaner/receiver
method_ids_size     : 533
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/cleaner/b
method_ids_size     : 17
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/cleaner/bean
method_ids_size     : 596
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/cleaner/model
method_ids_size     : 271
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/cleaner/model/a
method_ids_size     : 149
com.cleanmaster.mguard.apk.smali.patched/com/ijinshan/cleaner/adapter
method_ids_size     : 2
com.cleanmaster.mguard.apk.smali.patched/com/mopub
method_ids_size     : 828
com.cleanmaster.mguard.apk.smali.patched/com/mopub/volley
method_ids_size     : 88
com.cleanmaster.mguard.apk.smali.patched/com/mopub/network
method_ids_size     : 17
com.cleanmaster.mguard.apk.smali.patched/com/mopub/mobileads
method_ids_size     : 383
com.cleanmaster.mguard.apk.smali.patched/com/mopub/mobileads/factories
method_ids_size     : 77
com.cleanmaster.mguard.apk.smali.patched/com/mopub/nativeads
method_ids_size     : 191
com.cleanmaster.mguard.apk.smali.patched/com/mopub/nativeads/factories
method_ids_size     : 13
com.cleanmaster.mguard.apk.smali.patched/com/mopub/common
method_ids_size     : 213
com.cleanmaster.mguard.apk.smali.patched/com/mopub/common/factories
method_ids_size     : 7
com.cleanmaster.mguard.apk.smali.patched/com/mopub/common/util
method_ids_size     : 22
com.cleanmaster.mguard.apk.smali.patched/com/lock
method_ids_size     : 470
com.cleanmaster.mguard.apk.smali.patched/com/lock/cover
method_ids_size     : 124
com.cleanmaster.mguard.apk.smali.patched/com/lock/cover/data
method_ids_size     : 109
com.cleanmaster.mguard.apk.smali.patched/com/lock/a
method_ids_size     : 6
com.cleanmaster.mguard.apk.smali.patched/com/lock/ui
method_ids_size     : 268
com.cleanmaster.mguard.apk.smali.patched/com/lock/ui/cover
method_ids_size     : 268
com.cleanmaster.mguard.apk.smali.patched/com/lock/ui/cover/a
method_ids_size     : 4
com.cleanmaster.mguard.apk.smali.patched/com/lock/ui/cover/animationlist
method_ids_size     : 181
com.cleanmaster.mguard.apk.smali.patched/com/lock/ui/cover/animationlist/widget
method_ids_size     : 181
com.cleanmaster.mguard.apk.smali.patched/com/lock/ui/cover/c
method_ids_size     : 46
com.cleanmaster.mguard.apk.smali.patched/com/lock/ui/cover/widget
method_ids_size     : 4
com.cleanmaster.mguard.apk.smali.patched/com/lock/b
method_ids_size     : 92
com.cleanmaster.mguard.apk.smali.patched/com/lock/blur
method_ids_size     : 25
com.cleanmaster.mguard.apk.smali.patched/com/cmnow
method_ids_size     : 470
com.cleanmaster.mguard.apk.smali.patched/com/cmnow/weather
method_ids_size     : 470
com.cleanmaster.mguard.apk.smali.patched/com/cmnow/weather/a
method_ids_size     : 69
com.cleanmaster.mguard.apk.smali.patched/com/cmnow/weather/receiver
method_ids_size     : 28
com.cleanmaster.mguard.apk.smali.patched/com/cmnow/weather/d
method_ids_size     : 2
com.cleanmaster.mguard.apk.smali.patched/com/cmnow/weather/b
method_ids_size     : 57
com.cleanmaster.mguard.apk.smali.patched/com/cmnow/weather/internal
method_ids_size     : 264
com.cleanmaster.mguard.apk.smali.patched/com/cmnow/weather/internal/a
method_ids_size     : 13
com.cleanmaster.mguard.apk.smali.patched/com/cmnow/weather/internal/ui
method_ids_size     : 208
com.cleanmaster.mguard.apk.smali.patched/com/cmnow/weather/internal/logic
method_ids_size     : 58
com.cleanmaster.mguard.apk.smali.patched/com/cmnow/weather/e
method_ids_size     : 9
com.cleanmaster.mguard.apk.smali.patched/com/cmnow/weather/f
method_ids_size     : 41
com.cleanmaster.mguard.apk.smali.patched/com/cmnow/weather/config
method_ids_size     : 80
com.cleanmaster.mguard.apk.smali.patched/com/cleanmaster
method_ids_size     : 57256
com.cleanmaster.mguard.apk.smali.patched/com/cleanmaster/dialog
method_ids_size     : 56
com.cleanmaster.mguard.apk.smali.patched/com/cleanmaster/dialog/a
method_ids_size     : 10
com.cleanmaster.mguard.apk.smali.patched/com/cleanmaster/dialog/server
method_ids_size     : 16
com.cleanmaster.mguard.apk.smali.patched/com/cleanmaster/dialog/common
method_ids_size     : 40
com.cleanmaster.mguard.apk.smali.patched/com/cleanmaster/kinfoc
method_ids_size     : 594
com.cleanmaster.mguard.apk.smali.patched/com/cleanmaster/kinfoc/base
method_ids_size     : 152
com.cleanmaster.mguard.apk.smali.patched/com/cleanmaster/base
method_ids_size     : 5600
com.cleanmaster.mguard.apk.smali.patched/com/cleanmaster/base/dialog
method_ids_size     : 184
com.cleanmaster.mguard.apk.smali.patched/com/cleanmaster/base/dialog/a
method_ids_size     : 104
com.cleanmaster.mguard.apk.smali.patched/com/cleanmaster/base/a
method_ids_size     : 75
com.cleanmaster.mguard.apk.smali.patched/com/cleanmaster/base/ipc
method_ids_size     : 136
com.cleanmaster.mguard.apk.smali.patched/com/cleanmaster/base/ipc/a
method_ids_size     : 60
com.cleanmaster.mguard.apk.smali.patched/com/cleanmaster/base/d
method_ids_size     : 76
com.cleanmaster.mguard.apk.smali.patched/com/cleanmaster/base/b

**Comment by JesusFreke** [comment]
smali faithfully assembles whatever you give it :) If you have too many methods, it's because you've added too many methods.

I can't do anything with that output, I was suggesting it to you for you to be able to investigate where the methods are yourself.

**Comment by JesusFreke** [comment]
I've added some utilities to smali that might help. You'll need to grab the latest source and build smali, and then something like

smali out -o classes.dex -m

And then a list of all the method references will be written to classes.dex.methods. You should be able to use this to compare the method reference list in the original apk with that from the patched smali files that you're trying to assemble, in order to determine what (and how many) method references are in the patched smali files, but not in the original.

**Comment by joesecurity** [comment]
Cool thank you. Could you describe the method index shortly? Is it global or per package? I also found this answer from another post:

Assuming so, then this is likely due to the fact that while deodexing, it can resolve an odexed method using any of several different equivalent overrides of the method.

e.g. it could use either Lcom/blah/Class;->toString()Ljava/lang/String; or Ljava/lang/Object;->toString()Ljava/lang/String; to refer to the toString method on the com.blah.Class class.

And in some cases, this might inflate the method count slightly, if it uses a different override than was present in the original dex file. And if the original dex file was close to the limit, this might be enough to push it over the limit.

Could you also explain shortly?

**Comment by JesusFreke** [comment]
The method index is global per dex file. The method list contains every unique method reference (type + method name + args/return value).

Correct, deodexing could potentially alter the number of method references from the original, for the reason you describe. However, I've never seen a case when it adds a significant number of new method references. And certainly not 10k new methods.
