### ISSUE TITLE
printTokens in smali's main works inproperly

### ISSUE THREAD

**Issue by yzygitzh** [JesusFreke/smali#303]
Hello,
I switched the bool value "printTokens" in smali's main function to get token information but it turned out that nothing was printed. I added a print statement to get the size of "tokens", and it's always zero when RUNNING. I mean, when DEBUGGING the program by set a breakpoint in assembleSmaliFile function, the size was correct and the sentences for printing tokens worked very well.
Tried removing concurrent modules but didnt work.
btw, the JDK version was 1.7 and 1.8.

**Comment by JesusFreke** [comment]
I don't even remember what I added that option for. I thought maybe it was for testing, but I don't see any of the current tests using it. I'll probably just remove the option then :)

**Comment by yzygitzh** [comment]
@JesusFreke 
I just found that the CommonTokenStream provides tokens "on demand" so a fill() call before print the tokens is needed :)
