### ISSUE TITLE
syntax error  in smaliParser.g 

### ISSUE THREAD

**Issue by saurabhsinghmaurya** [JesusFreke/smali#311]
Hi
i am not able to generate smali parser by using  smaliParser.g 
i am using 
"java -jar antlr-4.1-complete.jar -o out smaliParser.g ".
please tell  me right way to generate smali parser.
error.....................
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1082:37: syntax error: '$start, "I_STATEMENT_FORMAT3rc_METHOD"' came as a complete surprise to me while looking for rule element
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1094:4: syntax error: '->' came as a complete surprise to me while looking for rule element
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1094:7: syntax error: '^' came as a complete surprise to me
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1094:35: syntax error: '$start, "I_STATEMENT_FORMAT3rc_TYPE"' came as a complete surprise to me while looking for rule element
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1113:4: syntax error: '->' came as a complete surprise to me while looking for rule element
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1113:7: syntax error: '^' came as a complete surprise to me
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1113:30: syntax error: '$start, "I_STATEMENT_FORMAT51l"' came as a complete surprise to me while looking for rule element
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1126:4: syntax error: '->' came as a complete surprise to me while looking for rule element
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1126:7: syntax error: '^' came as a complete surprise to me
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1126:31: syntax error: '$start, "I_STATEMENT_ARRAY_DATA"' came as a complete surprise to me while looking for rule element
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1126:66: syntax error: '^' came as a complete surprise to me
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1127:7: syntax error: '^' came as a complete surprise to me
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1134:4: syntax error: '->' came as a complete surprise to me while looking for rule element
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1134:7: syntax error: '^' came as a complete surprise to me
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1134:34: syntax error: '$start, "I_STATEMENT_PACKED_SWITCH"' came as a complete surprise to me while looking for rule element
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1135:9: syntax error: '^' came as a complete surprise to me
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1135:36: syntax error: '$start, "I_PACKED_SWITCH_START_KEY"' came as a complete surprise to me while looking for rule element
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1136:9: syntax error: '^' came as a complete surprise to me
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1136:35: syntax error: '$start, "I_PACKED_SWITCH_ELEMENTS"' came as a complete surprise to me while looking for rule element
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1144:4: syntax error: '->' came as a complete surprise to me while looking for rule element
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1144:7: syntax error: '^' came as a complete surprise to me
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1144:34: syntax error: '$start, "I_STATEMENT_SPARSE_SWITCH"' came as a complete surprise to me while looking for rule element
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1145:7: syntax error: '^' came as a complete surprise to me
error(50): /home/saurabh/Downloads/smaliParser/smaliParser.g:1145:33: syntax error: '$start, "I_SPARSE_SWITCH_ELEMENTS"' came as a complete surprise to me while looking for rule element

**Comment by JesusFreke** [comment]
It's an ANTLR 3 grammar, not ANTLR 4. Smali is currently using ANTLR 3.5.2 to generate the parser.

**Comment by saurabhsinghmaurya** [comment]
thank you

**Comment by nemanjan00** [comment]
Will this ever change? 

Building a tool for analyzing smali code and wanted to make sure I do not have to rewrite it in 2 weeks :D

BTW, thanks for smali! :D

**Comment by JesusFreke** [comment]
I generally recommend against trying to parse the smali files directly.

Instead, have you considered using dexlib2 to load the dex file and get the information you need that way?

**Comment by nemanjan00** [comment]
As weird as this sounds, I am writing my tool in javascript, so, I am attempting to avoid using dexlib2

**Comment by JesusFreke** [comment]
Ah, fair enough :). You're modifying the ANTLR grammar to output a javascript parser then?

The answer to your question is no, there are no plans atm to switch the grammar to ANTLR v4

**Comment by nemanjan00** [comment]
This is first time I am doing something like this, so, I really have no idea what I am doing :D

I am assuming I can get antlr to give me a tree generated from smali code, based off your grammar in some format I can use it...

I am attempting to create call graph on very big smali code, to figure out interconnections... 

Final goal is to have simplified approximation of what is working with which other components and to maybe create correlation between functions from 2 versions of obfuscated program...

**Comment by JesusFreke** [comment]
I'm honestly not sure whether it would be easier to try to use the existing ANTLR grammar or just write a dex parser in javascript, haha :)

The dex format really isn't too bad to parse (although writing it is a bit more of a pain).

**Comment by JesusFreke** [comment]
I do have some unpublished code for converting a dex file into a protobuf representation, which is useful when you need to read a dex file from a different language. But in that case, you would still need to run the java program to convert the dex file to protobuf before you could interact with the protobuf representation in javascript - which may not be all that useful if you're trying to do this on a webpage or something.

**Comment by nemanjan00** [comment]
I think I am ok with some preprocessing... 

I made a decision to use javascript since most of the system I am working on is javascript (Node.JS), but, I guess I could create pipeline to do something with apk/dex before it gets to javascript

**Comment by JesusFreke** [comment]
Gotcha. I've kinda been meaning to open source that thing anyway. I'll see if I can make some progress on that.

**Comment by nemanjan00** [comment]
Thanks a lot. 

I will just start parsing smali for now, and, if you ever release it, will look into migrating to that. Thanks a lot! :D
