### ISSUE TITLE
what kind of apps when classes.dex spillted i guess ?

### ISSUE THREAD

**Issue by JaspreetSinghXDA** [JesusFreke/smali#318]
i fixed it it was kind of obfuscation :)
So please close this problem coming from apktool not from smali :)
regards

**Comment by JaspreetSinghXDA** [comment]
i fixed it it was kind of obfuscation :)

regards

**Comment by CunningLogic** [comment]
It was DexGuard, and also an apktool issue not a smali issue

**Comment by JaspreetSinghXDA** [comment]
yes i reported him but i only needs classes.dex somehow but dex manager gonna help here cus even if u use -r to stop decoding apk it still shows error in resources cus resources are splitted :)

**Comment by CunningLogic** [comment]
Then just extract the classes from the apk, and ignore the aXML

**Comment by JaspreetSinghXDA** [comment]
yes thats why i am saying i will use dex manager cus it only need classes.dex to hook up

**Comment by JaspreetSinghXDA** [comment]
oh justin case its you :P i cud not understand CunningLogic
i just saw email it showed ur name and yes thats dexgaurd 7.0 still classes.dex can be retrieved but without resources it becomes hard plus they also added protection to check xposed hooks 

regards
jasi2169

**Comment by CunningLogic** [comment]
Can you share this example?

**Comment by JaspreetSinghXDA** [comment]
commercial stuff brother

**Comment by CunningLogic** [comment]
Please do, and if you can link me to the commercial stuff I can purchase it

**Comment by JaspreetSinghXDA** [comment]
wait someone in the scene talked regarding that app with dexguard 7.0 enterprise packed i just want to ask him for apk i dont have it
i will ping u up in xda if i got that apk i am doing it to underground man if this request gets close

regards
