### ISSUE TITLE
Verification errors deodexing new HTC android 6.0 roms

### ISSUE THREAD

**Issue by ivicask** [JesusFreke/smali#351]
Trying to deodex latest HTC 6.0 roms like this one for example 
http://forum.xda-developers.com/one-a9/development/dump-hiaaerouhlhtceurope1-10-401-7-t3229782

Causes verificaiton errors and messed up code in framework, like for example below services.jar

Sorry dont have much more info or logs from deodexing than this for now.

11-24 20:58:34.609  3642  3642 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
11-24 20:58:34.609  3642  3642 E AndroidRuntime: java.lang.VerifyError: Rejecting class com.android.server.SystemServer because it failed compile-time verification (declaration of 'com.android.server.SystemServer' appears in /system/framework/services.jar)
11-24 20:58:34.609  3642  3642 E AndroidRuntime:        at java.lang.Class.classForName(Native Method)
11-24 20:58:34.609  3642  3642 E AndroidRuntime:        at java.lang.Class.forName(Class.java:324)
11-24 20:58:34.609  3642  3642 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.invokeStaticMain(RuntimeInit.java:216)
11-24 20:58:34.609  3642  3642 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.applicationInit(RuntimeInit.java:339)
11-24 20:58:34.609  3642  3642 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.zygoteInit(RuntimeInit.java:291)
11-24 20:58:34.609  3642  3642 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.handleSystemServerProcess(ZygoteInit.java:501)
11-24 20:58:34.609  3642  3642 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.startSystemServer(ZygoteInit.java:588)
11-24 20:58:34.609  3642  3642 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
11-24 20:58:34.612  3642  3642 E AndroidRuntime: Error reporting crash
11-24 20:58:34.612  3642  3642 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IActivityManager.handleApplicationCrash(android.os.IBinder, android.app.ApplicationErrorReport$CrashInfo)' on a null object reference
11-24 20:58:34.612  3642  3642 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:103)
11-24 20:58:34.612  3642  3642 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
11-24 20:58:34.612  3642  3642 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
11-24 20:58:34.666  3312  3312 E Zygote  : Exit zygote because system server (3642) has terminated

**Comment by JesusFreke** [comment]
Can you try this again with v2.2b1? If you're still getting the same error, I can take a closer look.

**Comment by ivicask** [comment]
Hey, it seams this was some error in early bases from HTC which caused the issue, with later bases i didint notice the error anymore without changing updating smali binaries.

So i guess we can forget about this issue, if i do notice any errors again ill report back.

Thanks.
