### ISSUE TITLE
Error missing EOF when regeneration dex

### ISSUE THREAD

**Issue by hieunp8x** [JesusFreke/smali#353]
Dear you,
When i try decode to smali then **regeneration dex file from smali, I gave error missing EOF...** . <br>
Original classes.dex file locate at https://drive.google.com/open?id=0BzD1w7jyro1_SlFHUC14cm5XWnc
#### My Environment
+ CentOS 64 bit (kernel 6.7)
+ Java: 1.7.0_25 (64 bit)
+ Smali version 2.1.0

### I did via 2 steps
1. **Step1**: Decode to smali no problem <br>
` baksmali -o classes_smali classes.dex `
2. **Step2**: Generate dex from decoded smali source <br>
` smali classes_smali -o classes.dex `<br>
error detail as<br>
` classes_smali/o/?.smali[859,1] missing EOF at '290'
classes_smali/o/coN$?.smali[68,4] missing EOF at 'iget'
classes_smali/o/aI$?.smali[7053,17] Error for input ';': Invalid text
classes_smali/o/aI$?.smali[7053,16] mismatched input '?' expecting REGISTER
classes_smali/o/aI$?.smali[7053,22] no viable alternative at input 'Lo/aI;'
classes_smali/o/aI$?.smali[14501,0] missing EOF at 'Lo/aI$?;'
classes_smali/com/fsecure/browser/AddBookmarkPage$?.smali[115,0] Error for input ';': Invalid text
classes_smali/com/fsecure/browser/AddBookmarkPage$?.smali[115,1] missing EOF at '->'
`<br><br>
Thanks!

**Comment by sk284525908** [comment]
i got this too, but from another dex'regeneration

**Comment by JesusFreke** [comment]
I'm not able to reproduce on v2.1.2

**Comment by iasceri** [comment]
smali/org/mobile/activity/SiloContainer.smali[3014,0] missing EOF at '.class'
line 3014:
.class Lorg/jw/jwlibrary/mobile/activity/SiloContainer$ScrollListener;
.super Landroidx/recyclerview/widget/RecyclerView$OnScrollListener;
