### ISSUE TITLE
BuilderClassDef's public getAnnotations returns package-private BuilderAnnotationSet

### ISSUE THREAD

**Issue by CalebFenton** [JesusFreke/smali#359]
Sorry if this is a stupid question, but I'm having trouble using [`BuilderClassDef#getAnnotations()`](https://github.com/JesusFreke/smali/blob/master/dexlib2/src/main/java/org/jf/dexlib2/writer/builder/BuilderClassDef.java#L98). It's a public method but it returns a package-private `BuilderAnnotationSet`. This seems awkward. Also, `BuilderAnnotation` is package-private. This is the best I can think of:

        for (BaseAnnotation annotation : classDef.getAnnotations()) {

        }

Am I doing it wrong? In case you're curious, I'm using a bytecode generation library to convert dexlib2 class definitions into actual JVM class objects and I want to make the classes look as real as possible. I built a special purpose virtual machine for executing dalvik and I think it would be easier to try and pass around actual class objects.

**Comment by JesusFreke** [comment]
Right, you don't need access to the concrete class to be able to use it. BuilderClassDef implements ClassDef, which is defined to return a `Set<? extends Annotation>`. You don't need to know about BuilderAnnotationSet or BuilderAnnotation, just treat it as a `Set<Annotation>`.

So, for your code snippet, I would actually recommend

    for (Annotation annotation: classDef.getAnnotations()) {
    }

**Comment by strazzere** [comment]
I ran into the same issue and just ended up using reflection to solve it;

    public static Iterator getAnnotationIterator(Object annotationSet) {
        try {
            Class<?> clazz = Class.forName("org.jf.dexlib2.writer.builder.BuilderAnnotationSet");
            Method method = clazz.getDeclaredMethod("iterator");
            method.setAccessible(true);
            return (Iterator) method.invoke(annotationSet);
        } catch (Exception exception) {
            exception.printStackTrace();
        }
        return Iterators.empty();
    }

    public static String getAnnotationType(Object annotation) {
        try {
            Class<?> clazz = Class.forName("org.jf.dexlib2.writer.builder.BuilderAnnotation");
            Method method = clazz.getDeclaredMethod("getType");
            method.setAccessible(true);
            return (String) method.invoke(annotation);
        } catch (Exception exception) {
            exception.printStackTrace();
        }
        return "unknown";
    }

**Comment by JesusFreke** [comment]
Tim: maybe I'm missing something, but can't you just do the following?

    for (Annotation annotation: builderClassDef.getAnnotations()) {
        String type = annotation.getType();
    }

**Comment by strazzere** [comment]
While that works Java syntactically, you'll get a run time error similar to;

> Error:(132, 64) java: iterator() in org.jf.dexlib2.writer.builder.BuilderAnnotationSet is defined in an inaccessible class or interface

Which is why I resorted to reflection for the fix.

**Comment by JesusFreke** [comment]
Ahhhh, ok. It's because the iterator method is returning a more specific type (which I believe is actually a different method at the bytecode level), and that more specific type is not accessible.


I believe this should work:

    for (Annotation annotation: ((ClassDef)builderClassDef).getAnnotations()) {
        String type = annotation.getType();
    }

This forces it to use the original iterator() method from the interface - the one that returns a Set<? extends Annotation>.

Regardless, this *is* a problem with the api that should be fixed :)

**Comment by strazzere** [comment]
Ah, that does work -- I could have sworn I tried that before. Oh well - it was on an old bit of code. Time to go back and refactor some of it now. Thanks!

**Comment by JesusFreke** [comment]
Fixed in fd8a1b4adc409f4c6d3271cf3dbda26ac598d8dc
