### ISSUE TITLE
Zip64 files support

### ISSUE THREAD

**Issue by iBotPeaches** [JesusFreke/smali#372]
I might be completely wrong on this, but all started with this report: https://github.com/iBotPeaches/Apktool/issues/1105

In short, I thought that APK was a Zip64 format. My local zip applications could handle unzipping the application in addition surprisingly Android post Android M supported this as well.

This led to a nasty error as apktool couldn't read the zip.

```
Caused by: java.util.zip.ZipException: invalid CEN header (bad signature)
```

So I moved the entire `ZipFile` class to Apache Commons Compress `ZipFile`. This allowed the unzip to work fine, but left us with.

```
I: Baksmaling classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: xytools_v1.1_public.apk is not an apk, dex, odex or oat file.
    at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:186)
    at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:78)
    at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:74)
    at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:37)
    at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:93)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:131)
    at brut.apktool.Main.cmdDecode(Main.java:163)
    at brut.apktool.Main.main(Main.java:81)

➜  Bug1105 
```
(When I pass the `dex` file off)

I figured I have two solutions

1) Extract the dex files myself and feed them directly to you vs passing you the file and having baksmali extract the dex files.

2) Patch smali to use a different `ZipFile` library. This should be relatively easy, because I believe the `DexFileFactory` is the only location where `ZipFile` is used. This would mean a very easy move to a new ZipFile dependency.

So before I did either of those options, I thought I would get your opinion. If number 2 sounds fine, I'll be happy to throw a PR in.

**Comment by rob-X1** [comment]
AFAIK the built in java.util.zip.ZipFile supports files in ZIP64 format, at least for Oracle JDK version 7 or newer. 
For OpenJDK you may need version 1.8.0_20 according to this feature request: https://bugs.openjdk.java.net/browse/JDK-8032680

**Comment by JesusFreke** [comment]
I'll look into bumping up the minimum java version to 1.8, to get zip64 support. My only concern is about baksmali in AOSP. It's used a bit for ART tests, and I'm not sure what the minumum java version is in the latest AOSP. I know it was 1.6 for a long time, but I think it's at least 1.7 now - maybe 1.8.

**Comment by rob-X1** [comment]
According to the documentation Java 8 is required for AOSP:
https://source.android.com/source/initializing.html#installing-the-jdk

**Comment by JesusFreke** [comment]
Nice, that should work well then.

**Comment by iBotPeaches** [comment]
Sweet. thanks for finding that @rob-X1 

This is definitely better than a dependency.
