### ISSUE TITLE
Cannot unpack android N's (preview) services.odex.

### ISSUE THREAD

**Issue by liudongmiao** [JesusFreke/smali#386]
should i upload the boot.oat and services.odex ?

**Comment by JesusFreke** [comment]
Yes, there were some changes to the oat format in N, which I'll need to add support for in baksmali. See #378

**Comment by JesusFreke** [comment]
And no, I don't need the oat files. But thanks!

**Comment by rvceboy** [comment]
Hi,
Please Add support for deodex Android N at soon as possible.
