### ISSUE TITLE
Unable To Deodex Framework Jar In MM boot.oat

### ISSUE THREAD

**Issue by Ticklefish** [JesusFreke/smali#389]
I'm unable to deodex a framework file from a Marshmallow boot.oat. 

I've created a temp folder, placed boot.oat in "c:\temp\tmp\framework\", copied the latest baksmali.jar to "c:|temp\", navigated to that folder and entered the following code:

"**java -jar baksmali.jar -x -c boot.oat -d /tmp/framework -e /system/framework/framework.jar /tmp/framework/boot.oat -o framework**"

(I'm just trying to replicate the example given in the Wiki)

I get this message as a result:

"**Can't find the file /tmp/framework/boot.oat**"

This is in Windows 7. The boot.oat is available here:

https://www.mediafire.com/?kxh14xd870nrary

It's entirely possible that I'm being stupid but I just can't see where the issue is.

**Comment by JesusFreke** [comment]
Well, does your windows machine have a /tmp path? I suspect not :)

**Comment by Ticklefish** [comment]
Hmm.. It's the work PC, so possibly not. I used some different folder names and got partial success.

This is with a boot.oat sent to me by somebody on xda. I think I'm better waiting for an odexed stock MM rom to be released on my phone before I try experimenting with this again.

Thanks for your reply, but I think this is worth closing for now.
