### ISSUE TITLE
smalidea is not compatible with IDEA 2016.1

### ISSUE THREAD

**Issue by gorrus** [JesusFreke/smali#390]
StepOverActionHandler class was removed from IDEA sources but still used in smalidea sources,
so on startup we have java.lang.NoClassDefFoundError: com/intellij/debugger/actions/StepOverActionHandler

**Comment by JesusFreke** [comment]
Great, thanks for letting me know. I'll look into it and get it fixed.

**Comment by colede** [comment]
Is this fixed yet? I only ask because I am using IDEA 2016.1.2 and I have noticed that I am able to stop the debugger within the Main Activity onCreate, but if I try to Step Over, it says waiting for last debugger  command and never returns.

**Comment by JesusFreke** [comment]
Not fixed yet. I just looked into this a bit, and this will likely require a bit of work to get working again. It looks like whole sections of the debugging implementation in IDEA were changed/removed. e.g. https://github.com/JetBrains/intellij-community/commit/20e25fb002f1f89d142a61ed5b53f80fbb32ec6b

**Comment by colede** [comment]
I may have mis-spoke..not sure. I have noticed that I had to change the default breakpoint to stop thread instead of  all, and i was able to start stepping. However, this was after downgrading to IDEA 2014.7 I think it was. I can try later with 2016.

**Comment by JesusFreke** [comment]
Fixed in f8f4e3224062c583a7d41c26c4ffe81f7143bd6f
