### ISSUE TITLE
Trying to run baksmali on Samsung Knox app .odex file results in "unsupported oat version: 45" exception

### ISSUE THREAD

**Issue by galapogos** [JesusFreke/smali#392]
I'm trying to run baksmali 2.1.1 on a Samsung Galaxy S6 KnoxAttestationAgent.odex file as part of the process to get to the source, but it's throwing a "unsupported oat version: 45" exception.

**Comment by JesusFreke** [comment]
Yep, that's an unsupported oat version all right :)

The first version that is supported is 56, which was used in the Marshmallow release.
