### ISSUE TITLE
How can I use baksmali to get APIS

### ISSUE THREAD

**Issue by dinasaif** [JesusFreke/smali#397]
I want to make static analysis for android app I make the next steps:
 1- unzip apk file with 7 zip 
2- convert androidmanifest.xml to readable file. 
3- covert classes.dex by baksmali.jar to out folder that contains .smali files by this command:

Java -jar baksmali-2.1.2.jar  classes.dex
Know I want to know which API functions are called I can't understand any thing from the out folder

**Comment by CunningLogic** [comment]
For the manifest you can use aapt or apktool

For the smali files, you are going to have to learn the "smali language", i suggest writing a simple app that you know how works, and then comparing source with the smali output, as well as reading up on the wiki.

**Comment by dinasaif** [comment]
oh it's very difficult way , I want to get API from java source code .
Do you have any way to do that?

**Comment by JesusFreke** [comment]
Rather than trying to parse the smali language, I would recommend using dexlib2 (the library that smali/baksmali use to read/write dex files) to load/read/inspect the dex file.

**Comment by dinasaif** [comment]
I used dex2jar then used jd - gui now I get source code but I want to make static analysis so I want to know all APIS that the application uses , I don't know how can I get them?can you help me

**Comment by CunningLogic** [comment]
I would also suggest

> Rather than trying to parse the smali language, I would recommend using dexlib2 (the library that smali/baksmali use to read/write dex files) to load/read/inspect the dex file.

s/smali language/smali language or pseudo java from a decompiler that is likely to be incorrect/

**Comment by JesusFreke** [comment]
Yeah, It should be relatively easy to get all the method calls in a dex file using dexlib2. Much easier than trying to parse smali and/or pseudo-java ;)

**Comment by dinasaif** [comment]
ok how can I get API from java code or from classes.dex  . the most papers talk about extract Api function calls from static analysis but I don't know how ???

**Comment by CunningLogic** [comment]
Hate to be that guy but... read the source and documentation. I needed to do some automated stuff and was left in the same position.

**Comment by dinasaif** [comment]
Thanks for helping me , How to get all the method calls and API in a dex file using dexlib2?
Please tell me in some details because I waste alot of time to find API to complete static analysis without reach to result

**Comment by JesusFreke** [comment]
Here's a quick example to help get you started with dexlib2 https://gist.github.com/JesusFreke/3f51278a7a32c1614e4a73e5b964f140

**Comment by dinasaif** [comment]
thank you
