### ISSUE TITLE
Where can I get the stable version of source code.

### ISSUE THREAD

**Issue by ziminlin** [JesusFreke/smali#401]
I am a newcomer and try to compile the source code in Android Studio.

However, some compile errors are thrown. For instance, "the smaliFlexLexer class  is not decleared" is thrown in the file  smali/smali/src/main/java/org/jf/smali/main.java.

The source code is obtained from https://github.com/JesusFreke/smali/releases.

Maybe I get the unstable versions of source code?

Thank you very much.

**Comment by JesusFreke** [comment]
smali and baksmali are built using gradle. You can also use "./gradlew idea" to generate an IDEA project. I haven't specifically tried using AS, but I suspect it should be able to open/use the generate IDEA project as well.

**Comment by JesusFreke** [comment]
Also, see https://github.com/JesusFreke/smali/wiki/BuildProcedure for build instructions

**Comment by ziminlin** [comment]
Thank you very much
