### ISSUE TITLE
get all api from classes.dex

### ISSUE THREAD

**Issue by dinasaif** [JesusFreke/smali#403]
I would like to thank you but I want to get all api with dexlib2 but when I write the code you write to me 
`public class GetCalledMethods {
    public static void main(String[] args) throws IOException {
        DexFile dexFile = DexFileFactory.loadDexFile(args[0], 15);

        Set<MethodReference> calledMethods = Sets.newHashSet();

        for (ClassDef classDef: dexFile.getClasses()) {
            for (Method method: classDef.getMethods()) {
                MethodImplementation implementation = method.getImplementation();
                if (implementation != null) {
                    for (Instruction instruction: implementation.getInstructions()) {
                        if (instruction.getOpcode().referenceType == ReferenceType.METHOD) {
                            calledMethods.add((MethodReference)((ReferenceInstruction)instruction).getReference());
                        }
                    }
                }
            }
        }

        for (MethodReference methodReference: calledMethods) {
            System.out.println(ReferenceUtil.getReferenceString(methodReference));
        }
    }
}
`
there is only one error 
The method getReference() is undefined for the type Instruction
the error in the next line:
calledMethods.add((MethodReference)((ReferenceInstruction)instruction).getReference());
can you help me please , I'm really tired to get all api and I google alot without any result

**Comment by JesusFreke** [comment]
That error doesn't match the code you pasted.

    ((ReferenceInstruction)instruction).getReference()

In that code, instruction is being cast to ReferenceInstruction, and getReference() *is* a valid method on a ReferenceInstruction. Your error indicates that you're trying to call getReference() on an Instruction, not on a ReferenceInstruction.

**Comment by dinasaif** [comment]
how can I fix this error please , I don't know how to do that
