### ISSUE TITLE
Is there any way to view registers?

### ISSUE THREAD

**Issue by Rumata888** [JesusFreke/smali#412]
Is there any way to view registers?

**Comment by JesusFreke** [comment]
You mean with the smalidea plugin?

**Comment by Rumata888** [comment]
Yes

**Comment by JesusFreke** [comment]
You should be able to add the register to the watches window, like you would a normal variable when debugging java.

**Comment by Quiark** [comment]
Can I add a register manually? I don't have access to .smali method bodies (must be some kind of RE protection in the app). When I try to add `v0`, `r0`, `p0` to Watches, it "Cannot find local variable"

**Comment by JesusFreke** [comment]
I'm not sure what you mean by "I don't have access to .smali method bodies". You mean you just have smali method stubs with no implementation? That's not going to work for debugging.
