### ISSUE TITLE
Caused by: java.lang.ArrayIndexOutOfBoundsException---when i used baksmali  

### ISSUE THREAD

**Issue by jackeyprince** [JesusFreke/smali#415]
Error occurred while disassembling class Lfreemarker.template.compiler.StandardTemplateParser$22; - skipping class
org.jf.util.ExceptionWithContext
	at org.jf.util.ExceptionWithContext.withContext(ExceptionWithContext.java:54)
	at org.jf.baksmali.Adaptors.MethodDefinition.<init>(MethodDefinition.java:161)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:326)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:113)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$0(baksmali.java:176)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException

**Comment by jackeyprince** [comment]
private DebugInfo getDebugInfo() {
        int debugOffset = dexFile.readInt(codeOffset + CodeItem.DEBUG_INFO_OFFSET);
         @if(String.valueOf(debugOffset).length()>8)
        {
        	debugOffset = dexFile.readInt(codeOffset + CodeItem.DEBUG_INFO_OFFSET);
        	System.out.println(String.valueOf(debugOffset)+"---------"+ String.valueOf(codeOffset)+"--------"+String.valueOf(CodeItem.DEBUG_INFO_OFFSET));
        }
       
        if (debugOffset == -1 || debugOffset == 0) {
            return DebugInfo.newOrEmpty(dexFile, 0, this);
        }
        if (debugOffset < 0) {
            System.err.println("%s: Invalid debug offset");
            return DebugInfo.newOrEmpty(dexFile, 0, this);
        }
        return DebugInfo.newOrEmpty(dexFile, debugOffset, this);
    }

**Comment by JesusFreke** [comment]
I need the full stack trace. You cut off the stack trace for the inner exception, which is where the error actually occurred.

**Comment by jackeyprince** [comment]
public void skipUleb128() {
        int end = dexBuf.baseOffset + offset;
        byte currentByteValue;
        byte[] buf = dexBuf.buf;
       
	  
//		if (end > buf.length) {
//			System.err.println(String.valueOf(end) + "--------" + String.valueOf(buf.length));
//			System.err.println(String.valueOf(dexBuf.baseOffset) + "--------" + String.valueOf(offset));
//		}
     //this  currentByteValue = buf[end++]; 
        if (currentByteValue < 0) { // if the MSB is set
            currentByteValue = buf[end++];
            if (currentByteValue < 0) { // if the MSB is set
                currentByteValue = buf[end++];
                if (currentByteValue < 0) { // if the MSB is set
                    currentByteValue = buf[end++];
                    if (currentByteValue < 0) { // if the MSB is set
                        currentByteValue = buf[end++];
                        if (currentByteValue < 0) {
                            throw new ExceptionWithContext(
                                    "Invalid uleb128 integer encountered at offset 0x%x", offset);
                        }
                    }
                }
            }
        }

        offset = end - dexBuf.baseOffset;
    }

**Comment by jackeyprince** [comment]
org.eclipse.debug.core.DebugException: com.sun.jdi.ClassNotLoadedException: Type has not been loaded occurred while retrieving component type of array.
java.lang.ArrayIndexOutOfBoundsException: 536870912

**Comment by jackeyprince** [comment]
I can upload the dex file that caused the error.
[errorclasses.zip](https://github.com/JesusFreke/smali/files/380693/errorclasses.zip)

**Comment by JesusFreke** [comment]
Fixed in 384161e0
