### ISSUE TITLE
Java version required for compiling.

### ISSUE THREAD

**Issue by anantshri** [JesusFreke/smali#416]
Is it just me or the default java version required to compile this has changed from version 7 to version 8.

**Comment by bursoft-git** [comment]
Yes, it seems to compile now need Java 8
JesusFreke, can you merge latest changes with 2.2_WIP branch?
And fix this regression? https://github.com/JesusFreke/smali/issues/381#issuecomment-222607947

Thanks!

**Comment by JesusFreke** [comment]
It shouldn't require java 8. Are you compiling master or 2.2_WIP?

2.2_WIP is still... WIP :)

**Comment by bursoft-git** [comment]
I compiling latest master commit https://github.com/JesusFreke/smali/commit/a5d82813f1519197ffb5471be75cd915564ffacb

```
c:\smali>java -version
java version "1.7.0_101"
Java(TM) SE Runtime Environment (build 1.7.0_101-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.101-b14, mixed mode)

c:\smali>gradlew proguard
Parallel execution is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\smali\smali\build.gradle' line: 33

* What went wrong:
A problem occurred evaluating project ':smali'.
> java.lang.UnsupportedClassVersionError: org/xbib/gradle/plugin/JFlexPlugin : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.116 secs
```

**Comment by JesusFreke** [comment]
java 8 is now required to compile, due to one of the gradle plugins using in the build.

**Comment by Lanchon** [comment]
it should be possible to use gradle's fork option to fork javac to jdk6 or 7, even when gradle (and plugin) are running under java8.

**Comment by JesusFreke** [comment]
But why? If you have to have java 8 anyway, you might as well just compile using it.

**Comment by Lanchon** [comment]
you used to enforce JDK6 was building the project for release builds, presumably to assure compatibility with java6. i don't know how valuable that is now, but IMHO it sure is valuable to build for java7. clients of dexlib can be used in embedded platforms running obscure JVM implementations, and most do not support java8. in fact, i am using dexpatcher (client of dexlib2) in such a setup.

to ensure previous java compatibility you can either:
- compile using the older JDK
- or set sourceCompatibility in gradle and point the compiler to the runtime classes from the older JRE to compile against (even so, you are still using the new javac, for better or for worse).

either way you need stuff that is not bundled with java8 to do it right.

i was under the impression that you wanted to maintain compatibility. may i suggest that at least you set sourceCompatibility to 1.7 to avoid using java8 language and bytecode features (such as interface defaults) and apis that depend on them (even though you might end up using libraries added to java8 that don't depend on those features anyway).

**Comment by JesusFreke** [comment]
You mean like this? https://github.com/JesusFreke/smali/blob/master/build.gradle#L85  ;)

**Comment by Lanchon** [comment]
lol, exactly like that

**Comment by anantshri** [comment]
any chance you are adding a section for JAVA7 in it.

**Comment by ale5000-git** [comment]
Compiling require java8 but is it required also for executing?

A user get this:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/beust/jcommander/JCommander : Unsupported major.minor version 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java :803)
at java.security.SecureClassLoader.defineClass(Secure ClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader .java:442)
at java.net.URLClassLoader.access$100(URLClassLoader. java:64)
at java.net.URLClassLoader$1.run(URLClassLoader.java: 354)
at java.net.URLClassLoader$1.run(URLClassLoader.java: 348)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.j ava:347)
at java.lang.ClassLoader.loadClass(ClassLoader.java:4 25)
at sun.misc.Launcher$AppClassLoader.loadClass(Launche r.java:312)
at java.lang.ClassLoader.loadClass(ClassLoader.java:3 58)
at org.jf.baksmali.Main.main(Main.java:78)
```

**Comment by Lanchon** [comment]
> com/beust/jcommander/JCommander : Unsupported major.minor version 52.0

so the linked JCommander binary requires java 8.
the source too? maybe you can rebuild JCommander?

JF hasn't been too responsive lately, i supposed he must be overwhelmed with real life.
do you want to try fix this yourself or are you simply reporting it?

**Comment by ale5000-git** [comment]
Apparently the latest version of jcommander no longer support Java 7.
I hate apps that that break compatibility.
