### ISSUE TITLE
use .source attribute as class and file name

### ISSUE THREAD

**Issue by ohadcn** [JesusFreke/smali#419]
apologies if such option exists, I can't find it in the help pages.
when baksmali-ing an APK, each .smali file has a .source attribute attached to it, this might look like:

file: android/support/v7/a/a.smali
```
.class public abstract Landroid/support/v7/a/a;
.super Ljava/lang/Object;
.source "ActionBar.java"
...
```
can baksmali create it as a file named ActionBar.smali - and rename all class references to it's (probably) original name (ActionBar in that case)?

**Comment by JesusFreke** [comment]
The source filename does not always match the class name. A simple example is an inner class. Both the outer and inner class with have the same source file. Also, the source filename can be any arbitrary string. e.g. 2 completely unrelated classes could have the source filename set to the same thing, etc.

This isn't something that I would add to baksmali, but you might be able to modify the dex file in such a way using dexlib2.
