### ISSUE TITLE
Missing version

### ISSUE THREAD

**Issue by ale5000-git** [JesusFreke/smali#422]
Hi,
I have downloaded smali / baksmali 2.1.3 from: https://bitbucket.org/JesusFreke/smali/downloads

When I run `java -jar smali.jar -v` I get `smali [unknown version] (http://smali.googlecode.com)`.
Same for `java -jar baksmali.jar -v`.

Is it possible to show the version?

**Comment by ale5000-git** [comment]
I have discovered the cause, it is caused by the path.
To replicate the problem put it in this path: `C:\!\smali.jar`

On Windows it is a perfectly valid path.

**Comment by JesusFreke** [comment]
This sounds like an issue with the jvm itself. Smali just uses the normal resource loading provided by java's ClassLoader. e.g. https://github.com/JesusFreke/smali/blob/master/baksmali/src/main/java/org/jf/baksmali/main.java#L65.

There's nothing there that deals with the path to the containing jar itself.

**Comment by ale5000-git** [comment]
I have submitted a bug report to Java, I hope they fix it in a short time.
