### ISSUE TITLE
FAILURE: Build failed with an exception when run gradlew

### ISSUE THREAD

**Issue by amirbijani** [JesusFreke/smali#428]
* What went wrong:
A problem occurred evaluating project ':smali'.
> java.lang.UnsupportedClassVersionError: org/xbib/gradle/plugin/JFlexPlugin : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by JesusFreke** [comment]
Yeah, right now the build requires java 8 due to the jflex plugin
