### ISSUE TITLE
Small code cleanup

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#437]
more of a code cleanup issue than a bug.

according to these lines:
https://github.com/JesusFreke/smali/blob/master/dexlib2/src/main/java/org/jf/dexlib2/DexFileFactory.java#L91
https://github.com/JesusFreke/smali/blob/master/dexlib2/src/main/java/org/jf/dexlib2/DexFileFactory.java#L72

the `"classes.dex"` literal in this line:
https://github.com/JesusFreke/smali/blob/master/dexlib2/src/main/java/org/jf/dexlib2/DexFileFactory.java#L61
should probably replaced by `null`.

**Comment by JesusFreke** [comment]
Thanks. This class is actually being mostly refactored for v2.2 (just local changes atm, not up on github yet).

**Comment by Lanchon** [comment]
thanks!

**Comment by Lanchon** [comment]
this turned out to be a bug, considering the following line:
https://github.com/JesusFreke/smali/blob/master/dexlib2/src/main/java/org/jf/dexlib2/DexFileFactory.java#L156

non-null "classes.dex" value disables the autodetection of DEX file within an OAT file.
