### ISSUE TITLE
[Q] Multidex support in dexlib2

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#438]
hi JF,

say you have a potentially big fat DexFile in memory. you want to write it to disk and potentially need to write it as a multidex.

a naive way to write it would be:

- attempt to write a dex file.
- if it fails because it is too big, split the DexFile and recursively attempt to write the parts.

needless to say, this is very inefficient. is there any way to incrementally process a DexFile and stop short of exceeding dex file limits, then switch to a new dex? or is there any other more efficient solution than the naive version above?

while on the topic, is there any support for multidex at all in dexlib2?
the only mildly relevant commit i found is https://github.com/JesusFreke/smali/commit/0c7e7b7ffcc11946a64b3c870c7d4b8c86bf06ca

any info is welcome. thanks so much!

**Comment by JesusFreke** [comment]
Using dexlib2, you should be able to split up the classes into multiple dex files and write them out independently.

I believe there may be some class ordering and dependency constraints when deciding which classes to put in the primany dex file vs. the secondary dex files. e.g. if you're using multidex on older api levels, I believe in needs to be able to load the Application class (including all its dependencies) from the primary dex file.

baksmali/dexlib2 have no concept of higher level android application concepts, like which class is the main Application class, and so it does not have the information necessary to make decisions about which classes should go in which dex file.

I think the best way to do this would be to use a DexPool object and manually intern classes into it until it throws an exception when one of the constant pools becomes full. I believe it currently generates a pretty generic exception in this case, so it could be improved to throw a more specific exception that could be caught and handled.

However, the tricky thing will be recovering from the exception in the DexPool, because it's likely some items from the last class will have already been interned before the constant pool overflow, and there's no good way currently to roll back the interned items.

**Comment by Lanchon** [comment]
yes, dexlib2 does not have the info of where to put each type. but it doesn't have the info of what types to write either, or what methods or what code, unless/until you feed it that info. the point is that it doesn't have the split info because there is no API or model for it in dexlib2. but there could be. 

one solution (not that i thought about it much, i'm just mentioning it as an example) is to have multidex read and write methods that present all types in a unified DexFile to clients (this is necessary so that clients can benefit from multidex mostly automatically), yet keep a 'tag' field on each type keeping track of which dex file the type originated from/will be written to (min value of tag is 1). the DexFile itself will also have a field with the number N of the highest dex file read (min value of N when reading is 1).

with this setup, you can read a multidex and then write it, and it will be an exact copy. (and it can handle holes in the dex file numbering, but only if such wholes are accepted by ART in real life.) 

but before writing one can alter the value of N (N=0 is a valid write value). and some types can be missing the tag field too (missing tags could be represented by either of these values: 0 or null). in these cases, the write method behaves like this:

- all types whose tags are less than or equal N will be written in the dex file specified by the tag.
- all dex files up to N will have the exact contents specified in the DexFile, no more and no less, and dexlib will throw an exception if any such dexfile overflows. (the exception will have an informative field with the dex file number).
- all types whose tags are greater than N, or are missing the tag altogether, -if they exist at all- will be written to dex file N+1 and if necessary overflow to N+2, N+3... etc.
- the write method returns the highest dex file number written.

this allows several uses:
- it can copycat a multidex by default.
- it can take care of class distribution automatically 95% of the time: in lollipop and above you never care about class distribution, so just set N to 0 before writing your modded DexFile and dexlib will take care of everything.
- for cases where compatibility with older androids is needed, dexlib needs to know what types to put in the first dex file (but can take care of splitting all the other by itself). for this you set N = 1 and tag the important classes with tag value 1. all other classes (untagged or tagged > 1) will be distributed automatically by dexlib in dex files 2, 3 etc.

with this support in dexlibe, smali and bak could be extended to take care of multidex too: a few command line switches and an extra smali directive to record the tag of each type, and you are set.

there would be a switch in baksmali to inhibit the generation of this tag directive for compatibility with previous smali syntax; after all, 95% of the use cases will be for android 5+, so smali could handle class distribution automatically most of the time.

smali would take the number N as a command line parameter, and if missing would automatically set it to the largest directive-tagged type in the smali source files. so by default it would rebuild the dex files in copycat fashion, and untagged added classes (if any) would be placed in extra added dex file(s). passing N0 and N1 to it would also make sense in specific situations.

-----

these changes would bring full multidex support to smali, a missing important piece. but they are 'ambitious'. now rolling back to my original post...

at a minimum dexlib should support a method of partially writing 'all that fits' in a dex, and returning the unwritten part to the client to handle. with the current implementation, it seems that the client has to do trial an error to find if/where DexFile objects should be split to be written. this is very inefficient. also -as you mention- an specific exception type should signal overflows in standard writes.

**Comment by Lanchon** [comment]
hi again,

i'm working to support multidex. i was surprised by this piece of code, which might be hiding issues in DexPatcher, a client of dexlib2 that i maintain:

https://github.com/JesusFreke/smali/blob/master/dexlib2/src/main/java/org/jf/dexlib2/util/MethodUtil.java#L90-L91

why are you checking only the first character of the parameter type? is it an optimization to avoid invoking String.equals()? or can the type be followed by more information here? what would that info be?

thanks for your help!

**Comment by Lanchon** [comment]
and back on track,

working on the multidex thing, by analyzing your code i've come to some preliminary conclusions. please help me by reviewing them and tell me if you agree. i want to avoid starting to code in the wrong direction.

here we go...

when writing a dex file from a DexFile, several fields might overflow. this means that the DexFile cannot be written as is due to limitations of the dex file format. some overflows can be avoided by nothing more than splitting the types you want to write in several DexFiles before writing. lets call these types of overflows "split-fixable".

preliminary conclusions:

1. all split-fixable overflows during writes in dexlib2 end up throwing an ExceptionWithContext in this method of DexDataWriter :
```
    public void writeUshort(int value) throws IOException {
        if (value < 0 || value > 0xFFFF) {
            throw new ExceptionWithContext("Unsigned short value out of range: %d", value);
        }
        write(value);
        write(value >> 8);
    }
```

2. in all such cases, the `value` parameter used to invoke writeUshort() is always the value returned by one of these methods:

  - fieldSection.getItemIndex((FieldRefKey) reference)
  - methodSection.getItemIndex((MethodRefKey) reference)
  - stringSection.getItemIndex((StringRef) reference)
  - typeSection.getItemIndex((TypeRef) reference)
  - protoSection.getItemIndex((ProtoRefKey) reference)

3. which means that all split-fixable overflows are caused by the overflow of one or more of these sections:

  - fieldSection
  - methodSection
  - stringSection
  - typeSection
  - protoSection

4. but your code seems to look for Opcode.CONST_STRING instances in dalvik code and replace them with Opcode.CONST_STRING_JUMBO if the associated stringSection.getItemIndex(reference) would overflow the writeUshort() call. which means that a jumbo stringSection will never cause overflows from Opcode.CONST_STRING references.

5. other opcodes could potentially trigger a stringSection-related overflow by writing their string references through `private int getReferenceIndex(int referenceType, Reference reference)`. but none can because in the Opcode enum the only opcodes that have references of ReferenceType.STRING are CONST_STRING and CONST_STRING_JUMBO.

6. which means that stringSection-related split-fixable overflows can never happen, reducing the potential causes to these sections:

  - fieldSection
  - methodSection
  - typeSection
  - protoSection

7. and finally, if the above sections are not overflowing, then any overflow errors that might happen during writing are guaranteed to be non-split-fixable. ie, they cannot not be fixed by any possible splitting of types over DexFiles.

thanks so much for your help!

**Comment by JesusFreke** [comment]
The first character of a type is all you need to determine whether it's 32 bit or 64 bit. All primitive types are only 1 character. J (long) and D (double) are the only types that are 64 bit. Arrays always start with at least one [, and Classes always start with an L, so the first character is all you need to determine the basic type.

**Comment by JesusFreke** [comment]
Yes, that sounds correct overall. A few points:

4) Correct. There are no other instruction that have a string reference, only the 2 const-string instructions. All other cases of string references in a dex file (e.g. in the type id item) are 4 bytes, so you don't have to worry about them overflowing.

6) There are other places an overflow can happen. Basically, anywhere there is a 16-bit reference to one of those 4 sections. e.g. the field_id_item structure has some 16-bit references to a type that could cause an overflow.

**Comment by Lanchon** [comment]
thanks so much!

**Comment by Lanchon** [comment]
FYI, DexBuilder has this public method:
```
    @Nonnull public BuilderMethodProtoReference internMethodProtoReference(@Nonnull MethodProtoReference methodProto) {
        return context.protoPool.internMethodProto(methodProto);
    }
```

so i believe it cannot be assured that this is always true:

protoSection size <= methodSection size

**Comment by Lanchon** [comment]
ok...

this simple commit looks like the minimum support needed to efficiently write multidex with dexlib2:
https://github.com/Lanchon/DexPatcher-tool-dexlib2/commit/ced726a0120d3d0c4d13c328b78f0dd43cff7ce2

and this adds a specific pool overflow exception and fail-fast:
https://github.com/Lanchon/DexPatcher-tool-dexlib2/commit/387838e35d523ddf881bdb8c10144ea0670a5067

i'll be using a forked 2.1.3 until 2.2 and hope to get back to official then. thanks again!

**Comment by JesusFreke** [comment]
I was thinking it should throw an exception when it's interning a class, so you can stop interning new classes into that dex file and start on the new one.

**Comment by JesusFreke** [comment]
It's worth pointing out that writing the dex file isn't necessarily the slow part of the process - it's interning all the items. So your change allows you notice the problem after you've interned all the items but before writing it out, which means you'll have to re-intern all the items into a new dex pool. So it's not going to save you much time.

**Comment by Lanchon** [comment]
a couple of things...

throwing an exception would be too late. unless you can undo the last partial intern, which would require extreme changes. and i guess the changes would make everything slower anyway.

there is no need to throw an exception. the multidex-writing client can intern each class and test if overflow; it would be the same thing as you throwing but much better (see bellow). so the client can find out about the error if it happens early and not after interning all the classes.

if the overflow happens, the client will have to discard the DexPool and start interning everything again, but partial writes of files will never happen: the multidex-capable client is expected to have successfully interned the complete dex it wants to write before even opening the file.

finally, these changes absolutely allow a client to write multidex efficiently, although the client is slightly more complex than you picture. this is the algorithm:

- there's a configurable threshold value. my tool will have a command line option for it, defaulting to -say- 0xF000.
- to write a big fat DexFile, the client will start with a fresh DexPool and begin to intern classes into it.
- after interning each class it will invoke getPoolUsage(), and if usage is below the threshold, it will keep on interning classes.
- if classes to intern run out, only then open a file, write it, and we are done!
- otherwise we are over the threshold; but most likely not above 0x10000.
- if not above 0x10000, then open a file, write it, get a fresh DexPool instance, and continue interning classes as described above.
- otherwise the last type we interned was huge: it took us from below the threshold to overflow in a single interning. no problem, do as follows:
  - discard the DexPool and get a fresh one.
  - now intern N-1 classes (we counted the N classes that lead to the overflow).
  - now we are guaranteed to be below 0x10000 (we are actually below threshold) so a write will succeed.
  - output a warning stating that the threshold is too high and proposing the user lower it to getPoolUsage() for better performance.
  - open a file, write it, get a fresh DexPool instance, and continue interning classes as described above.

(actually, the hard maximum of 0x10000 will also be configurable (as it is in dx) to allow some obscure use cases (such as the amazon market).)

you could say the client code is "complex", but somebody has to do the work, and if you don't do it in dexlib (you said it exceeded its scope) then i have to do it in the client. i'll have decoupled classes that others can reuse to read and write multidex.

of course you can later reconsider and include the functionality in dexlib. but this is a very basic solution, and better ones should be considered for inclusion in dexlib. (like the one i proposed earlier; or at least supporting at the very minimum configuration of the contents of the first dex file.) the important point is that by providing the very simple hooks i propose here you will be allowing efficient writes. afterwards you can integrate my code or treat it as a basis to develop a better solution or roll your own or whatever, but i suggest you concentrate on your current 2.2 roadmap and dont delay it for a cool implementation of multidex if clients can manage on their own.

**Comment by testwhat** [comment]
Share my implementation which copies the concept from dx.
https://github.com/testwhat/SmaliEx/commit/26064dfb5a1d3ffa035a016f4f8010a4c54b230d#diff-44f751e9d7ddf11cc6bc322bddc3f6cdR285

**Comment by Lanchon** [comment]
hi, thank you!

i'm working on releasing dexpatcher 1.1 now. as soon as i do that i'll start working on 1.2 which will implement multidex. i've got everything sorted out on the multidex front, in my mind at least, so i think i might go for my own implementation because:
- i want to stay as close to official dexlib2 as possible. JF will surely provide the hooks needed for multidex in the dexlib 2.2 and i'm hoping to get back to official then.
- my preliminary tests show that the most costly operation of my tool in usual cases is writing dex. optimizing dexlib is beyond my scope (though i did try a few changes but didn't result in massive gains). instead, my plan is to implement multithreaded multidex writing which will increase performance by a notable factor with very little work.

anyway, still working on 1.1 for now. thanks again!

**Comment by JesusFreke** [comment]
Let me know what you think :)

https://github.com/JesusFreke/smali/commit/68e9c34d7aa98202e5b2b35c15a25489a96b8429 :)

**Comment by Lanchon** [comment]
cool! i left some comments. i think the keySet copying is an issue. my solution of walking the list is much better, but i still hate it. inside LinkedHashMap there must be a doubly linked list and the last items are right there available to be removed! we just need a reverse-ordered iterator

**Comment by Lanchon** [comment]
apache commons has a linked map that works:

http://commons.apache.org/proper/commons-collections/javadocs/api-release/org/apache/commons/collections4/map/LinkedMap.html

**Comment by Lanchon** [comment]
still the most important comment is that you please make sure that i can query the usage level of the pools as a client of the writer.

i will implement multithreaded writing for performance, and the trade-off will be variably used-up dex files. so still trying to keep the files used to the max with the roll back mechanism is not justified in my case, where so many files as there are worker threads will end up half-full.

**Comment by JesusFreke** [comment]
The DexPool is now subclassable, so you can override hasOverflow, and can access the various sections

**Comment by Lanchon** [comment]
cool thanks!

**Comment by sriteja777** [comment]
Hey @Lanchon can you please  share the solution you implemented (if it's open source), Or can can you share the gist of the solution?
I have similar use case

**Comment by Lanchon** [comment]
search for multidexlib2.

**Comment by sriteja777** [comment]
thanks!
