### ISSUE TITLE
cannot write a dex file specifying api level and experimental flag

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#439]
smali passes 'Opcodes' instance to DexWriter via DexBuilder constructor. DexWriter has an 'Opcodes' member. so pressumably it is important to write dex files.

DexPool static writeTo methods do not take an 'Opcodes'; api level 20 is assumed instead. DexFileFactory is missing writeDexFile methods exposing 'Opcodes' or api level and experimental (but it does provide those variants for loadDexFile).

workaround: replicate DexBuilder's code in caller; pretty ugly!

**Comment by JesusFreke** [comment]
In v2.2, DexFile will have a getOpcodes method (https://github.com/JesusFreke/smali/blob/v2.2_WIP/dexlib2/src/main/java/org/jf/dexlib2/iface/DexFile.java).

I'll fix up DexPool.writeTo to use the Opcodes instance associated with the dex file when making the DexPool

**Comment by Lanchon** [comment]
for now this is the extremely ugly workaround needed. it uses reflection to access a private field meaning it potentially breaks compatibility with a SecurityManager.

```
	private static void writeDexWorkaround(String path, DexFile input, int apiLevel, boolean experimental) throws IOException {
		DexPool dexPool = DexPool.makeDexPool(apiLevel);
		ClassSection classSection;
		try {
			Field classSectionField = DexWriter.class.getDeclaredField("classSection");
			classSectionField.setAccessible(true);
			classSection = (ClassSection) classSectionField.get(dexPool);
		} catch (ReflectiveOperationException e) {
			throw new Error(e);
		}
		ClassPool classPool = (ClassPool) classSection;
		for (ClassDef classDef: input.getClasses()) {
			classPool.intern(classDef);
		}
		dexPool.writeTo(new FileDataStore(new File(path)));
	}
```

**Comment by JesusFreke** [comment]
Hmm. I guess I didn't realize there wasn't an accessible way to intern a class into a DexPool, other than via writeTo. I should probably add that too.

**Comment by Lanchon** [comment]
this was complicated further because DexPool constructor is private. the class section field is protected, but i cannot get at it anyway because i cannot extend the class in any way.

this a Java language issue: it could be legal to extend DexPool with a non-instantiable class that does not define constructors, and that provides access to the protected field. i am willing to be that such class when defined in java bytecode is legal. however there is no way to define it in java text, no way to make the java compiler not generate any constructors (no constructor and private constructor is not really the same thing; c++ now has syntax to delete automatic constructors).

another possibility for java would be to allow abstract final classes: this would be a natural way to define non-instantiable classes (they have real uses) and would not generate constructors, but it is forbidden for apparently no good reason.

**Comment by JesusFreke** [comment]
No, that wouldn't be possible even in bytecode. You would still have to call DexPool's constructor from a subclass's constructor, otherwise it will fail verification.

Even if you could create a subclass of DexPool with no constructors, if you can't instantiate it, then it's useless for this. It's not like you can cast an already created DexPool object to MyNonInstantiableDexPoolSubclass. Ditto for creating an abstract final subclass (if java allowed that).

The issue is with the design of the class (i.e. my fault). Not some fault of the language.

**Comment by Lanchon** [comment]
yes, the idea was never instantiate it of course. couldn't you put a static method there that takes a reference to an instance of the superclass, DexPool, and access the protected field in question, then return its value? sort of a getter method implemented as a static with an explicitly defined this parameter.

**Comment by JesusFreke** [comment]
Ah, I see what you mean. A static method could access the field in that case.

**Comment by Lanchon** [comment]
this 'private constructors with protected members and accessing bytecode class' business is an interesting ingredient for anti-reversing obfuscation. there seems to be no way to express that valid bytecode in java text; you need to make reflection-visible changes to the structure of the program.

**Comment by JesusFreke** [comment]
heh. reminds me of https://github.com/JesusFreke/smali/blob/master/examples/RecursiveExceptionHandler/Main.smali. I'd love to see that in java :)

**Comment by Lanchon** [comment]
> yes, the idea was never instantiate it of course. couldn't you put a static method there that takes a reference to an instance of the superclass, DexPool, and access the protected field in question, then return its value? sort of a getter method implemented as a static with an explicitly defined this parameter.

nope! this wouldnt work.

according to the dalvik constraints:
https://source.android.com/devices/tech/dalvik/constraints.html

> B12 	When accessing protected members of a superclass, the actual type of the instance being accessed must be either the current class or one of its subclasses. 

i suspect the same restriction applies to java bytecode too.

**Comment by JesusFreke** [comment]
I think everything mentioned here is in v2.2_WIP now
