### ISSUE TITLE
Typo in parameter name

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#441]
https://github.com/JesusFreke/smali/blob/v2.2_WIP/dexlib2/src/main/java/org/jf/dexlib2/util/TypeUtils.java#L63

accesse**{e}**ClassDef

**Comment by JesusFreke** [comment]
That spelling (accessee) looks correct to me. e.g. https://en.wiktionary.org/wiki/-ee

**Comment by Lanchon** [comment]
lol sorry, i thought you meant accessed!
