### ISSUE TITLE
[RFE] ZipDexContainer

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#443]
hi! please make these methods 'protected' in ZipDexContainer:

- boolean isDex(@Nonnull ZipFile zipFile, @Nonnull ZipEntry zipEntry)
- ZipDexFile loadEntry(@Nonnull ZipFile zipFile, @Nonnull ZipEntry zipEntry)

this way a filter of files can be implemented cleanly an efficiently. (eg: only try files in the root directory of the zip which are named "classes([2-9]|([1-9][0-9]+))?.dex".) right now filters are inefficient: you only have access to filter after the class decompressed the start of each and every file in the zip, which can be very wasteful.

(while on the subject, getZipFile() could be made protected too allow different factories of ZipFile if there ever is such a need, IDK.)

**Comment by Lanchon** [comment]
you can even add an empty filter method that gets called before decompressing each file to see if it has a dex header to avoid the wasteful overhead of trying every file in the zip if the client is only interested in one or a few files.

then you can subclass and implement this method in DexFileFactory.loadDexEntry.

**Comment by JesusFreke** [comment]
SGTM. I'll have to think about adding the filtering, or just making them protected and letting a subclass deal with filtering if it wants to.

**Comment by Lanchon** [comment]
you can add a `protected boolean isDexCandidate(@Nonnull ZipEntry zipEntry) { return true; }` and call it from isDex() and loadEntry() before operating on the zip file. even so, i'd suggest you also make those two methods protected.

but just making the methods protected is good enough.

**Comment by JesusFreke** [comment]
Implemented in 615d3833
