### ISSUE TITLE
[RFE] MultiDexContainer should have a getOpcodes() method

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#444]
the info is always available when creating implementing classes of this interface, but it is not passes to the constructors. the result is:

- to get the opcodes one needs to open the file and read one of the dexes, a very expensive operation. (there is also the issue of why choose the first file for instance.)
- more importantly, the case where a MultiDexContainer contains no dex files cannot be handled at all, and opcodes are lost. in my usage, i need to always pass around the MultiDexContainer and the Opcodes instances together because of this issue, when the MultiDexContainer is supposed to embed the opcodes.

if you need a more detailed use case, let me know.

thanks!

**Comment by JesusFreke** [comment]
SGTM

**Comment by JesusFreke** [comment]
Implemented in 29967666
