### ISSUE TITLE
[RFE] subclassing DexPool is horrible right now

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#448]
and only possible by cut and pasting a big blob of code (which btw might change in the future).

the constructor exposes a lot of implementation detail and shouldn't. please fix it by providing a public or protected constructor like this: `protected DexPool(@Nonnull Opcodes opcodes)`

you can do this like in my commit: https://github.com/DexPatcher/dexlib2-fork-for-dexpatcher/commit/016974069308fe67f17069e2b040749b6640c593

thanks!

**Comment by JesusFreke** [comment]
Take a look at #463

**Comment by Lanchon** [comment]
this is a nice cleanup of the code.

unfortunately it doesn't fix this issue. to subclass DexPool one needs to copy and paste this blob of code:
https://github.com/JesusFreke/smali/blob/master/dexlib2/src/main/java/org/jf/dexlib2/writer/pool/DexPool.java#L65-L87

this blob is a DexPool implementation detail and derived classes should not be forcefully exposed to it. your blob of code might change in the future, introducing regression bugs on derived classes that were made before your changes. and these bugs might not even be caught by the compiler, making it even more problematic.

DexPool should provide a public or protected constructor like this: `DexPool(@Nonnull Opcodes opcodes)` if it is supposed to be subclassed at all (yes it should IMHO).

(btw, if the constructor is public, and i don't see why not, then you can remove the static factory method.)

due to super() invocations being necessarily the first statement in java's constructors and the way DexPool members are interconnected, implementing `DexPool(@Nonnull Opcodes opcodes)` is not absolutely trivial and a new intermediate 'context' type must be introduced. here is one solution:
https://github.com/DexPatcher/dexlib2-fork-for-dexpatcher/commit/016974069308fe67f17069e2b040749b6640c593

if you want, the new context type could be a nested static private type inside DexWriter, and the DexWriter's constructor taking it as a parameter should also be private then.

in it's present form, DexWriter can't be safely subclassed. please tell me if you want a pull request. thanks!

**Comment by JesusFreke** [comment]
Uh, what blob of code? :)

https://github.com/JesusFreke/smali/blob/0a20bca924c9fe0327088bbfcd8e06921d46d0e7/dexlib2/src/main/java/org/jf/dexlib2/writer/pool/DexPool.java#L65

**Comment by Lanchon** [comment]
sorry my github we interface switched me to master unwittingly at some point and i ended up looking at the old code. it is perfect as it is!
