### ISSUE TITLE
[RFE] DexWriter (...again...)

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#450]
please, please, PLEASE provide this:
```
    public boolean hasOverflowed(int maxPoolItems) {
        return methodSection.getItemCount() > (maxPoolItems) ||
                typeSection.getItemCount() > (maxPoolItems) ||
                fieldSection.getItemCount() > (maxPoolItems);
    }
```

of course i would also take a `int getPoolUsage()` but you don't like it. either change is necessary to limit the number of items to less than 64Ki. otherwise you need to subclass DexPool and subclassing DexPool involves a horrible constructor and copying and pasting code that should be really be part of the constructor.

please don't force sublcassing just to change the pool limit. limiting items to less than 64Ki is a requirement sometimes, eg:

> https://developer.amazon.com/public/community/post/Tx291UO6WP91P9Z/Too-Many-Methods-How-to-Avoid-Compile-Errors-on-Submission

> When you compile your code and are short of the 65K limit, you may reasonably believe you don’t need to worry about this problem. That is, until you submit it to an Appstore. Most appstores, (the Amazon Appstore included), add additional method references as part of the ingestion process. If your code is ”too close” to the limit when submitted, your code may fail upon submitting to an Appstore after the additional references are added.

> [...] What is “too close”? [...] Google sets max methods to 60K if Multidex is used, so you can be pretty sure that 60K methods is a safe number for newer Android devices.

> [...] if you are using studio 0.9.0+ gradle 0.14.2 and let the build tools automatically limit the dx.additionalParameters parameter to 60,000.

there are problems with too many items on old devices. Google has the `--set-max-idx-number` option to handle this. from Google's code:

https://android.googlesource.com/platform/tools/base/+/9fba95348ef762fd9a7c82ac332d119684a74bcb%5E1..9fba95348ef762fd9a7c82ac332d119684a74bcb/

```
+                // This sets the method ref count threshold at which dex overflow
+                // occurs.  On the one hand, we want this number to be as large as
+                // possible, to provide maximum room for code which must reside in
+                // the primary dex.  On the other hand, making this number too big
+                // results in LinearAlloc capacity being exceeded on Gingerbread
+                // devices.  (Experience has shown that a value of 65100 yields
+                // LinearAlloc failures on a large percentage of GB devices.)
+                // Basically, making this number smaller can break builds, while
+                // making it bigger can break devices.  THINK VERY HARD BEFORE
+                // CHANGING THIS VALUE!
+                command.add("--set-max-idx-number=60000");
```

once `public boolean hasOverflowed(int maxPoolItems)` is available, in DexPool you could add as convenience methods:

- `public void internClassDefs(@Nonnull Iterable<? extends ClassDef> classDefs)`
- `public int internClassDefs(@Nonnull Iterable<? extends ClassDef> classDefs, int maxPoolItems)`

the second version would use mark/rollback and return the number of interned classes.

**Comment by Lanchon** [comment]
actually the method `public int internClassDefs(@Nonnull Iterable<? extends ClassDef> classDefs, int maxPoolItems)` is total crap, because you can't pass a start index and so you can't continue writing. please ignore that last part about the two methods.

**Comment by JesusFreke** [comment]
Take a look at https://github.com/JesusFreke/smali/pull/463

**Comment by JesusFreke** [comment]
Take a look at #463. It doesn't expose such a method, but the sections are public now, so you can easily write a simple utility method to do what you want.

**Comment by Lanchon** [comment]
well, the commit doesn't provide `hasOverflowed(int maxPoolItems)` or `int getPoolUsage()`, and it doesn't make DexPool subclassable either, so it doesn't apply to this issue.

(DexPool *is* subclassable, in the sense that it can be done, but subclassing DexPool right now is a dangerous hack more than planned API.)

**Comment by JesusFreke** [comment]
... whut?  Are you sure you're looking at the right version? :)

Yes, it doesn't add hasOverflowed/getPoolUsage, as I stated. But it does make the sections publicly accessible, so you can write your own utility for that trivially.

And yes, it does make DexPool more easily subclassable.

The link in your previous comment is to the existing code in master, not the code in the pull request that I linked to.

**Comment by Lanchon** [comment]
yes absolutely, i was looking at the wrong code. the change is totally ok, sorry. thanks!
