### ISSUE TITLE
[BUG] MultiDexContainer

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#451]
currently is:
`public interface MultiDexContainer<T extends DexFile>`

should be:
`public interface MultiDexContainer<T extends MultiDexContainer.MultiDexFile>`

**Comment by JesusFreke** [comment]
This is intentional. See, e.g. SingletonMultiDexContainer.

**Comment by Lanchon** [comment]
thanks! btw i won't bug you with any more RFEs :) there's initial support for multidex in my tool and everything seems to be working. if you want to take a look...
https://github.com/DexPatcher/dexpatcher-tool/releases

**Comment by Lanchon** [comment]
i still think it's unfortunate that MultiDexContainer is not defined more like this so that callers of getContainer don't need to cast the result:
```
public interface MultiDexContainer<F extends MultiDexFile> {
// ...
    interface MultiDexFile<C extends MultiDexContainer> extends DexFile {
// ...
        @Nonnull T getContainer();
    }
}
```

much more important is this:
`public class ZipDexContainer implements MultiDexContainer<ZipDexFile>`
should really be:
`public class ZipDexContainer implements MultiDexContainer<MultiDexFile<ZipDexContainer>>`

ZipDexFile doesn't add any useful interface to MultiDexFile (except for the casting of the return type in getContainer, which should really be handled by generics) and should not be a public type. (if it exists at all. in my implementations ZipDexFile equivalents don't exist and are implemented by a common BasicMultiDexFile<> wrapper. besides avoiding code repetition, i favor containment over extension.)

the fact that ZipDexContainer implements MultiDexContainer<ZipDexFile> gratuitously forces me to return DexFiles derived from ZipDexFile when i extend ZipDexContainer, which is something that i don't want to do. in all, i'll probably just reimplement ZipDexContainer from scratch -even though i would reuse 95% of its code- because ZipDexContainer's interface is not amenable to extension.

(the case of SingletonMultiDexContainer that you mention above is trivially handled by wrapping the returned DexFile in an instance of the same BasicMultiDexFile<SingletonMultiDexContainer>.)

**Comment by Lanchon** [comment]
the previous message wasnt readable because github was eating up the `<...>` in types as if they were HTML tags. edited now.

------

FYI: in the end it made sense to write zip container from scratch. now i'm using my implementations of the 3 dex containers i use, so i might as well just switch to a redefined MultiDexContainer interface, to solve:
- nullable getOpcodes to allow for the case when autodetection based on dex version can't return an Opcodes (eg, the dex container is empty)
- getEntryNames return Set instead of List
- what i mention in the post above (proper return type of getContainer, etc)

but i don't like to break up with dexlib so much

**Comment by Lanchon** [comment]
and i also have a problem with getOpcodes not throwing IOException for detection. that can be solved by eagerly loading and computing everything on dex containers on construction instead of on getter invocation. i've been bothered by the lazy processing there anyway, it means that files are loaded several times. that is not so bad for me because i fixed [this] (https://github.com/google/guava/issues/2616) with a workaround but it is still bothersome.

**Comment by Lanchon** [comment]
ok, i pushed the thing.

the part that starts with "Includes multidexlib2, a reusable GPLv3+ library" might interest you:
https://github.com/DexPatcher/dexpatcher-tool/releases/tag/v1.2.0

**Comment by JesusFreke** [comment]
nice :)
