### ISSUE TITLE
suspicious behavior in dexlib2

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#453]
test:
- let 'A' be some dex file.
- baksmali A; call the result 'bak(A)'.
- with dexlib2, read A using DexBackedDexFile, then write it using DexPool; call the new dex file 'B'.
- baksmali B; call the result 'bak(B)'
- compare bak(A) and bak(B).

expectation: no differences.
reality: one difference found in the whole of framework.jar from a cyanogenmod build.

file: android/security/keystore/AndroidKeyStoreKeyPairGeneratorSpi.smali

A version (original):
```
    .line 203
    :try_start_a3
    invoke-static {v11}, Landroid/security/keystore/KeyProperties$KeyAlgorithm;->toKeymasterAsymmetricKeyAlgorithm(Ljava/lang/String;)I
    :try_end_a6
    .catch Ljava/lang/IllegalArgumentException; {:try_start_a3 .. :try_end_a6} :catch_cf
    .catch Ljava/lang/NullPointerException; {:try_start_a3 .. :try_end_a6} :catch_c8
(*) .catch Ljava/lang/IllegalArgumentException; {:try_start_a3 .. :try_end_a6} :catch_c8
    .catchall {:try_start_a3 .. :try_end_a6} :catchall_37

    move-result v6
```

note the line marked with (*). it seems to be a redundant catch specification, i have no idead why it is there. see: https://github.com/CyanogenMod/android_frameworks_base/blob/cm-13.0/keystore/java/android/security/keystore/AndroidKeyStoreKeyPairGeneratorSpi.java#L203

the rewritten version lacks the catch:

B version (rewritten by dexlib2):
```
    .line 203
    :try_start_a3
    invoke-static {v11}, Landroid/security/keystore/KeyProperties$KeyAlgorithm;->toKeymasterAsymmetricKeyAlgorithm(Ljava/lang/String;)I
    :try_end_a6
    .catch Ljava/lang/IllegalArgumentException; {:try_start_a3 .. :try_end_a6} :catch_cf
    .catch Ljava/lang/NullPointerException; {:try_start_a3 .. :try_end_a6} :catch_c8
    .catchall {:try_start_a3 .. :try_end_a6} :catchall_37

    move-result v6
```

even if it were redundant, wouldn't it be better to keep it? it seems like somehow DexPool is removing it.

**Comment by JesusFreke** [comment]
Yep, this is a known side effect of how dexlib2 represents catch blocks internally. This is a "safe" change, in the sense that it only ever removes a catch statement that could never be used, and thus doesn't affect the semantics of the bytecode.

**Comment by Lanchon** [comment]
i see, thanks! i still don't know how come baksmali even outputs it if dexlib2 can't handle the redundancy. probably an issue with DexWriter/DexPool rather than the representation i guess. thanks again!
