### ISSUE TITLE
Not closing smali files again in 2.2

### ISSUE THREAD

**Issue by agorski3** [JesusFreke/smali#454]
This is the same issue I made a pull request for and was fixed in 2.1.3. The function assembleSmaliFile needs to look like it did before. I.e. the following:

```
private static boolean assembleSmaliFile(File smaliFile, DexBuilder dexBuilder, SmaliOptions options)
            throws Exception {
    FileInputStream fis = null;
    try {
        fis = new FileInputStream(smaliFile);
        InputStreamReader reader = new InputStreamReader(fis, "UTF-8");
        
        LexerErrorInterface lexer = new smaliFlexLexer(reader);
        ((smaliFlexLexer)lexer).setSourceFile(smaliFile);
        CommonTokenStream tokens = new CommonTokenStream((TokenSource)lexer);
        
        //Everything else the same up to and including the return
    } finally {
        if (fis != null)
            fis.close();
    }
}
```

**Comment by agorski3** [comment]
You kept the change in class org.jf.dexlib2.analysis.ClassProto related to Joiner so that is something at least :)

**Comment by JesusFreke** [comment]
Oops, sorry about that. I had move that logic in v2.2 and didn't cross-merge your patch to the new location in v2.2 after merging it back into master.

I had already indepedently fixed the ClassProto Joiner thing in v2.2 :)  (4254a207)

**Comment by agorski3** [comment]
Yep I figured it was something like that. ;)

**Comment by agorski3** [comment]
I created a pull request with the fix here.

https://github.com/JesusFreke/smali/pull/461
