### ISSUE TITLE
baksmali can't resolve odex dependencies when only jar is present

### ISSUE THREAD

**Issue by JesusFreke** [JesusFreke/smali#464]
@bursoft-git [wrote](https://github.com/JesusFreke/smali/issues/449#issuecomment-254342532)
> My deodexing script delete *.odex files after proper deodexing.
> This is not a problem when using baksmali-2.1.3 (maybe, it loads classpath entry from *.jar files?), but with 2.2b4 i got many errors after deleting *.odex files from bootclasspath dir
> 
> ```
> Error occurred while loading class path files. Aborting.
> org.jf.dexlib2.analysis.ClassPathResolver$ResolveException: org.jf.dexlib2.analysis.ClassPathResolver$NotFoundException: Could not find classpath entry /system/framework/android.policy.odex
> 	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:136)
> 	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:106)
> 	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:134)
> 	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:91)
> 	at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:204)
> 	at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
> 	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:178)
> 	at org.jf.baksmali.Main.main(Main.java:102)
> Caused by: org.jf.dexlib2.analysis.ClassPathResolver$NotFoundException: Could not find classpath entry /system/framework/android.policy.odex
> 	at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalOrDeviceBootClassPathEntry(ClassPathResolver.java:207)
> 	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:121)
> 	... 7 more
> ```
> 
> so, now i need always keep all *.odex files during deodexing?
> thanks!

**Comment by JesusFreke** [comment]
Hmm, looks like a regression with the new ClasspathResolver logic. I'll see if I can improve that.

**Comment by JesusFreke** [comment]
This is fixed in 8fa96e2fcd1fb6df11638dfbe8be329f499288bf

**Comment by bursoft-git** [comment]
thanks, latest commit solved this bug!
from now, v2.2 passes all my test suites
