### ISSUE TITLE
Copyright year not updated

### ISSUE THREAD

**Issue by ale5000-git** [JesusFreke/smali#465]
Under `java -jar smali.jar -v` it say `Copyright (C) 2010 Ben Gruver (JesusFreke@JesusFreke.com)`.
The year isn't updated.

**Comment by JesusFreke** [comment]
From: http://www.copyright.gov/title17/92chap4.html

> (b) Form of Notice. — If a notice appears on the copies, it shall consist of the following three elements:
> 
> (1) the symbol © (the letter C in a circle), or the word “Copyright”, or the abbreviation “Copr.”; and
> 
> (2) the year of first publication of the work; in the case of compilations or derivative works incorporating previously published material, the year date of first publication of the compilation or derivative work is sufficient. The year date may be omitted where a pictorial, graphic, or sculptural work, with accompanying text matter, if any, is reproduced in or on greeting cards, postcards, stationery, jewelry, dolls, toys, or any useful articles; and
> 
> (3) the name of the owner of copyright in the work, or an abbreviation by which the name can be recognized, or a generally known alternative designation of the owner.

In the case of smali/baksmali, the year of first publication is 2010.

**Comment by ale5000-git** [comment]
Sorry, I thought all licenses were similar in this regards.
On GPL you have to list all years.

**Comment by JesusFreke** [comment]
It's not based on the license you're using. That page I linked gives the requirements for any copyright notice (in the US, of course).

There's nothing in the GPL says you must list all years in a copyright notice. Go read it - https://www.gnu.org/licenses/gpl-3.0.en.html :)

**Comment by ale5000-git** [comment]
It is in the page `How to use GNU licenses for your own software`, it say:

> The copyright notice should include the year in which you finished preparing the release (so if you finished it in 1998 but didn't post it until 1999, use 1998). You should add the proper year for each release; for example, “Copyright 1998, 1999 Terry Jones” if some versions were finished in 1998 and some were finished in 1999. If several people helped write the code, use all their names.

For software with several releases over multiple years, it's okay to use a range (“2008-2010”) instead of listing individual years (“2008, 2009, 2010”) if and only if every year in the range, inclusive, really is a “copyrightable” year that would be listed individually; and you make an explicit statement in your documentation about this usage.

**Comment by JesusFreke** [comment]
"should" != "must" :) And besides, that's just auxiliary usage information. The only legally binding part of the GPL is the license text itself.

**Comment by JesusFreke** [comment]
Basically, it boils down to
- Me being lazy and not wanting to have to update the copyright notice every year
- The first year being sufficient, per the actual requirements I mentioned earlier

**Comment by ale5000-git** [comment]
Well, now I know that is optional; I didn't know before :)
