### ISSUE TITLE
dexlib2 cannot "refactor" generic-type field correctly

### ISSUE THREAD

**Issue by shizhx** [JesusFreke/smali#471]
I am using dexlib2(2.2b4) to "refactor" dex, but it cannot refactor generic-type filed.
here is my java code to generate sample dex:
```java
package com.example.dexsample;

public class GenericType<T> {
    public T value;
}
```
```java
package com.example.dexsample;

public class TestGeneric {
    public GenericType<String> type;
    public MainActivity activity;
}
```

here is my java code to refactor dex's class name:
```java
            DexRewriter dexRewriter = new DexRewriter(new RewriterModule() {
                @Nonnull
                @Override
                public Rewriter<String> getTypeRewriter(@Nonnull Rewriters rewriters) {
                    return new Rewriter<String>() {
                        @Nonnull
                        public String rewrite(@Nonnull String value) {
                            final String prefix = "Lcom/example/dexsample/";
                            if (!value.startsWith(prefix)) {
                                return value;
                            }

                            return prefix + "Renamed_" + value.substring(prefix.length());
                        }
                    };
                }
            });
```

here is the decompiled dex code(using [jadx](https://github.com/skylot/jadx)):
```java
package com.example.dexsample;

/* compiled from: GenericType */
public class Renamed_GenericType<T> {
    public T value;
}
```

```java
package com.example.dexsample;

/* compiled from: TestGeneric */
public class Renamed_TestGeneric {
    public Renamed_MainActivity activity;
    public GenericType<String> type;
}
```

as you see, non generic-type field's type has been renamed, but generic-type filed has not.

**Is it a bug or my mistake?**

**Comment by JesusFreke** [comment]
You probably need to change the value of the dalvik.annotation.Signature annotation associated with the generic field. The specific format of this annotation isn't defined by the dex format. I don't know if/where it is specified.

**Comment by shizhx** [comment]
@JesusFreke I watched logs of jadx and searching in jadx's sources, it looks like that signature of a field come from corresponding `DebugItem` of `START_LOCAL_EXTENDED` type. But even though I override the `getDebugItemRewriter()`, I can't meet an `DebugItem` of` START_LOCAL_EXTENDED` type, `START_LOCAL` at most.

does dexlib2 support parsing `START_LOCAL_EXTENDED` item?

**Comment by shizhx** [comment]
@JesusFreke I modified my codes to change  that annotation, then it works!
`DebugItem`s still not changed, I will change it next time.
Thank you very much!

**Comment by JesusFreke** [comment]
START_LOCAL_EXTENDED would be for local variables, not fields. And yes, it's supported.
