### ISSUE TITLE
incorrect register type derivation

### ISSUE THREAD

**Issue by stiv-yakovenko** [JesusFreke/smali#483]
I'm disassembling correct DEX file with this line

>         System.out.println(-0.0f);

and get this code:

>     #v0=(Reference,Ljava/io/PrintStream;);v1=(Uninit);v2=(Null);p0=(Reference,[Ljava/lang/String;);
>     const/high16 v1, -0x80000000
>     #v0=(Reference,Ljava/io/PrintStream;);v1=(Integer);v2=(Null);p0=(Reference,[Ljava/lang/String;);
> 
>     #v0=(Reference,Ljava/io/PrintStream;);v1=(Integer);v2=(Null);p0=(Reference,[Ljava/lang/String;);
>     invoke-virtual {v0, v1}, Ljava/io/PrintStream;->println(F)V
>     #v0=(Reference,Ljava/io/PrintStream;);v1=(Integer);v2=(Null);p0=(Reference,[Ljava/lang/String;);
> 

v1 is Integer, but should be Float, shouldn't it?

**Comment by JesusFreke** [comment]
Integer is actually correct here. As far as register types are concerned, integers and floats are largely interchangeable.

**Comment by stiv-yakovenko** [comment]
well, i can't agree:

> .method public static sum(III)V 
>   .registers 3 
>   add-float p0, p2, p2 // this gives VerifyException
>   ...
> .end method

Verifier rejected class: void MyClass.test(int,int, int) failed to verify: void MyClass.test(int, int, int): [0x6] register v2 has type Integer but expected Float

Am I wrong?

**Comment by stiv-yakovenko** [comment]
Also davlik bytecode instruction table says:

> 1500 2041 - const/high16 v0, #float 10.0 // #41200000
> Moves the floating literal of 10.0 into v0. The 16 bit literal in the instruction carries the top 16 bits of the floating point number.

**Comment by JesusFreke** [comment]
No it doesn't :)

"Move the given literal value (right-zero-extended to 32 bits) into the specified register."  (https://source.android.com/devices/tech/dalvik/dalvik-bytecode.html)

I believe your quote is from http://pallergabor.uw.hu/androidblog/dalvik_opcodes.html, which is an oooooold reference that was based on his reverse engineering of the dex format back before android was released and open sourced.

https://source.android.com/devices/tech/dalvik/dalvik-bytecode.html is the canonical reference you should be using.

Also relevant is https://android.googlesource.com/platform/art/+/5ea54a33a81ce48156fbb2685e9a61d0748644dc/runtime/verifier/method_verifier.cc#2282, which is the logic for the register type analysis of const/high16 in the ART codebase. As you can see, it calls into DetermineCat1Constant (https://android.googlesource.com/platform/art/+/5ea54a33a81ce48156fbb2685e9a61d0748644dc/runtime/verifier/method_verifier.cc#5216), which returns one of the integral types based on the value of the constant. Notably, it never returns the float type.

**Comment by stiv-yakovenko** [comment]
Ok, as I understand, your point is: 

const/high16 v1, -0x80000000  gives Integer value which can be safely used later for passing as float parameter.  

But for my own purposes (I need to extract method) I'd like to patch backsmali to be smart enough to distinguish between int and float consts. Is it hard to do it with its current architecture?

Thanx

**Comment by JesusFreke** [comment]
How would your proposed analysis handle the following method?

```
.method public static main([Ljava/lang/String;)V
    .registers 3

    sget-object v0, Ljava/lang/System;->out:Ljava/io/PrintStream;

    const/high16 v1, 0x12340000

    invoke-virtual {v0, v1}, Ljava/io/PrintStream;->println(F)V
    invoke-virtual {v0, v1}, Ljava/io/PrintStream;->println(I)V

    return-void
.end method
```

**Comment by stiv-yakovenko** [comment]
Well, you have almost pointed out a bug in https://github.com/skylot/jadx, this is how its dissasembled:

> public class FloatOp {
>     public static void main(String[] strArr) {
>         PrintStream printStream = System.out;
>         int i = 305397760;
>         printStream.println(i);
>         printStream.println(i);
>     }
> }

I've added extra register to avoid inlining. What I need is following:

    const/high16 v1, 0x12340000
    #v1=(Float);
    invoke-virtual {v0, v1}, Ljava/io/PrintStream;->println(F)V
    #v1=(Float);

   #v1=(Integer);
   invoke-virtual {v0, v1}, Ljava/io/PrintStream;->println(I)V
   #v1=(Integer);

which is a bit crazy, I see, but it is what I need for my purposes. I'm learning your architecture, but its not clear yet, how hard it is to patch your code to behave like this.
