### ISSUE TITLE
Baksmali fails to decode this .apk file

### ISSUE THREAD

**Issue by stiv-yakovenko** [JesusFreke/smali#485]
https://www.dropbox.com/s/2rcjnp0fwkmr8fh/app-debug.apk?dl=0

this file is disassembled incorrectly, jadx does its job right. it contains only~30 classes of 100 in com.example.steve.hugeapk.

**Comment by JesusFreke** [comment]
This apk contains multiple dex files. You have to run baksmali on each dex file.

    >baksmali list dex app-debug.apk
    classes.dex
    classes2.dex
    classes3.dex
    classes4.dex

    >baksmali d app-debug.apk/classes.dex -o app/classes
    >baksmali d app-debug.apk/classes2.dex -o app/classes2
    >baksmali d app-debug.apk/classes3.dex -o app/classes3
    >baksmali d app-debug.apk/classes4.dex -o app/classes4

This is intentional, so that you can specify a different output folder for each dex file, so that you don't end up with all the classes in a single directory, and won't be able to easily re-assemble them into individual dex files.

**Comment by stiv-yakovenko** [comment]
@JesusFreke , why is it important to preserve dex <=> class mapping? If it is, then may be it may sence to disassemble each dex to individual subfolder by default in one run?

**Comment by JesusFreke** [comment]
Fundamentally, baksmali deals with dex files, not apks. The ability to pass an apk to baksmali is just a convenience, so you don't always have to extract the classes.dex.

If you want to extract all the dex files at once, it should be fairly trivial to write your own wrapper that calls the "list dex" command, and then invokes baksmali on each dex file in the apk.
