### ISSUE TITLE
Missing classes resolved in com.offerup.android app

### ISSUE THREAD

**Issue by frankhuhu** [JesusFreke/smali#490]
I use soot to parse the offerup app, but find that many classes can not be resolved. I double check the soot's implementation and it use dexlib2-2.2b4 to parse the dex file. So I guess there is some corner cases that dexlib2 cannot successfully resolve. 

The app I use is here: [https://play.google.com/store/apps/details?id=com.offerup&hl=en](url)
Here is a sub list of the classes that cannot be resolved, but there are many more:
`
Warning: com.offerup.android.activities.ChangeLocationActivity is a phantom class!
Warning: com.offerup.android.activities.ChatActivity is a phantom class!
Warning: com.offerup.android.activities.DeeplinkRouterActivity is a phantom class!
Warning: com.offerup.android.activities.DepositMethodActivity$1 is a phantom class!
Warning: com.offerup.android.activities.DepositMethodActivity$2 is a phantom class!
Warning: com.offerup.android.activities.DepositMethodActivity$3 is a phantom class!
Warning: com.offerup.android.activities.DepositMethodActivity_MembersInjector is a phantom class!
Warning: com.offerup.android.activities.ExpandedSelectBuyerActivity is a phantom class!
Warning: com.offerup.android.activities.ExploreActivity is a phantom class!
Warning: com.offerup.android.activities.GalleryActivity is a phantom class!
`

**Comment by frankhuhu** [comment]
B.T.W, I find the dx-1.10.jar can resolved all the classes in this app.

**Comment by JesusFreke** [comment]
This is a multidex apk. The classes you list are in the secondary dex. I'm guessing soot is only loading the primary classes.dex.

**Comment by frankhuhu** [comment]
OK. I see. Thanks for your quick reply.

Regards,
-Yongjian
