### ISSUE TITLE
[Feature] Executing baksmali on an Android device

### ISSUE THREAD

**Issue by MassyB** [JesusFreke/smali#496]
Hello, 
First of all, thank you for the tool you provide, it's really useful. :+1: 
I'm last year student and the subject of my thesis is 'Android malware detection :  a solution on the device'
one of the features that the anti-malware looks for is : the API calls. In the PC, I am using baksmali (v2.2) to disassemble the apk to smali files  and than pars each smali file (excepte those under the android/* directory) to detect and store method calls.

But, on the device is there any mean to execute the baksmali.jar directly ? How can I do that ? 
there is a thread on XDA developer forum dealing with this feature 
https://forum.xda-developers.com/showthread.php?t=904548
But, I didn't understand the process for executing the baksmali jar directly on the device.
Thank you.

**Comment by JesusFreke** [comment]
The process for running baksmali on a device is basically the same as http://stackoverflow.com/questions/10199863/how-to-execute-the-dex-file-in-android-with-command, except that you don't need to compile anything of course, and you just need to pass the baksmali jar to dx, instead of the class file.

You'll need to know the name of the main class in order to perform the last step. For baksmali, that is "org.jf.baksmali.main" for pre-2.2 versions, or "org.jf.baksmali.Main" for 2.2+ versions.

That being said, instead of running baksmali and trying to parse the smali files, I would recommend looking at linking against dexlib2 and reading the dex file directly. You can use it to load a dex file and iterate over all the classes/methods/instructions.

**Comment by ale5000-git** [comment]
@MassyB: If you search an example, in [Tingle](https://github.com/ale5000-git/tingle) I use baksmali directly from a Python script and it work both on the PC and on Android.

**Comment by MassyB** [comment]
Thank you for your help
@JessusFreke: I like the idea of using the dexlib2 library.
I searched on [stackoverflow](http://stackoverflow.com/questions/19904724/parser-dex-file-for-bytecode-retrive/19914322#19914322) :
* the `DexFileFactory.loadDexFile` method doesn't allow `int` as a second parameter anymore.
* after viewing the `Instruction` class, I assume that it's is not possible (using that class) to get a more abstracted representation (i.e. smali) of the instruction.
For the purpose of malware detection, I have to satisfy two requirements :
* get all the method calls (not the method definition, in order to be robust against obfuscation) in a smali format ex: `com/example/bartman/helloworldapp/DummyCalsse;->dummyMethode1()V`.
* on the PC the baksmali files that are under `baksmali_ouput/android/*` are not analyzed because they are generated by Android.
Can I meet the aforementioned requirements using the dexlib2 library ?
if so any api documentation, code snippet, hello world exemple would be of a great help.
Thank you

**Comment by MassyB** [comment]
**@ale5000-git**: thank you for the python script. I have thinked about using python for extracting method calls of an APK. But, it's tricky to execute a python script from an android device targeting other APKs.
I prefer the Java approach, because it's usable directly by the anti-malware which is also an APK (written in java).
The anti-malware is an APK that is installed on a device. in order to classify an APK, the anti-malware must extract the API calls made by that APK. The representation must be in a smali format because most of the research work used smali to represent (suspicious API calls, mapping between API and permission). Behind the scene, the anti-malware is relying on an Machine Learning algorithme (Linear SVM) and the method calls are some of the features describing the data point ( the APK analyzed)

**Comment by JesusFreke** [comment]
@MassyB You can certainly extract any method calls using dexlib2. e.g. https://gist.github.com/JesusFreke/396458abb2145224e13773ee649f57c5

**Comment by MassyB** [comment]
When I'm trying to run the jar file for V 2.2b*, I'm getting this error
```
java.lang.NoClassDefFoundError: java.nio.file.Path
	at com.beust.jcommander.internal.DefaultConverterFactory.<clinit>(DefaultConverterFactory.java:66)
	at com.beust.jcommander.JCommander.<clinit>(JCommander.java:167)
	at org.jf.baksmali.Main.main(Main.java:78)
	at dalvik.system.NativeStart.main(Native Method)

```
but the V2.1.3 is working

**Comment by JesusFreke** [comment]
Oh, I think I'll need to take a look at that.

**Comment by MassyB** [comment]
I've tried the code snippet and i found an exception

**Comment by JesusFreke** [comment]
That's... a less than helpful description of the problem.

**Comment by ale5000-git** [comment]
@MassyB: Why closing? Is it already fixed?

**Comment by JesusFreke** [comment]
Just FYI, I know what the problem is with the missing Nio class when trying to run baksmali directly on a device. I'll make sure that that is fixed in the next release.
