### ISSUE TITLE
Deodexing Android O failed

### ISSUE THREAD

**Issue by bursoft-git** [JesusFreke/smali#498]
Hi JesusFreke!
Thanks for smali 2.2 final! But why smali and baksmali binaries not proguarded?

Google release Android O preview, and baksmali fail while i tri to deodex it.
http://storage.googleapis.com/androiddevelopers/shareables/preview/sailfish-opp1.170223.012-factory-164983f4.zip

```
C:\BatchApkTool\_system\framework\arm>java -jar baksmali-2.2.jar l d boot.oat
/system/framework/core-oj.jar

C:\BatchApkTool\_system\framework\arm>java -jar baksmali-2.2.jar x boot.oat/system/framework/core-oj.jar

Error occurred while loading class path files. Aborting.
java.lang.ArrayIndexOutOfBoundsException: 795378589
        at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:53)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:77)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:137)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:133)
        at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)
        at org.jf.dexlib2.analysis.DexClassProvider.<init>(DexClassProvider.java:48)
        at org.jf.dexlib2.analysis.ClassPathResolver.loadEntry(ClassPathResolver.java:241)
        at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalOrDeviceBootClassPathEntry(ClassPathResolver.java:210)
        at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:120)
        at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:105)
        at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:129)
        at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:86)
        at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:203)
        at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
        at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:177)
        at org.jf.baksmali.Main.main(Main.java:102)
```

**Comment by argraur** [comment]
Same here ++

**Comment by JesusFreke** [comment]
I uploaded new proguarded binaries, thanks. I haven't had a chance to take a look at O yet.

**Comment by JesusFreke** [comment]
For O, it looks like there's a new .vdex file type that contains the optimized dex files. I think I knew that was coming at one point, but I had totally forgotten about it.

**Comment by JesusFreke** [comment]
Interestingly, it looks like vdex files have all the field offsets and virtual table information needed to deodex - and are actually being deodexed (unquickened) by the system in some cases (e.g. an OTA).

Dare I believe that we'll no longer need to try to generate the field offsets and vtables in dexlib2? If that is the case, that will make deodexing much simpler and remove one of the biggest headaches in doing it correctly.

**Comment by bursoft-git** [comment]
yes, it seems vdex files contains all code from dex file + header
![2017-03-23_091904](https://cloud.githubusercontent.com/assets/7475720/24234627/6cf46f0a-0faa-11e7-9204-21febc6251e9.png)

**Comment by bursoft-git** [comment]
And, JesusFreke, maybe you implement option for deodexing files without disassemble and reassemble it? :-)
https://github.com/JesusFreke/smali/issues/445

**Comment by JesusFreke** [comment]
My answer has not changed ;)

**Comment by JesusFreke** [comment]
O deodexing should be working properly with 48cde6219d248634b7b5b30d873fd8144376ff36

**Comment by Aaahh** [comment]
Off topic again but I've been having this problem for about 2 years:
How do you deodex framework??, I deodexed the files and everything but the logcat spits out dex2art trying to make a boot.oat and failing:
`01-21 18:56:34.730   270   270 E art     : Could not create image space with image file '/system/framework/boot.art'. Attempting to fall back to imageless running. Error was: Failed to generate image '/data/dalvik-cache/arm/system@framework@boot.art': Failed execv(/system/bin/dex2oat --image=/data/dalvik-cache/arm/system@framework@boot.art --dex-file=/system/framework/core-libart.jar --dex-file=/system/framework/conscrypt.jar --dex-file=/system/framework/okhttp.jar --dex-file=/system/framework/bouncycastle.jar --dex-file=/system/framework/ext.jar --dex-file=/system/framework/framework.jar --dex-file=/system/framework/telephony-common.jar --dex-file=/system/framework/voip-common.jar --dex-file=/system/framework/ims-common.jar --dex-file=/system/framework/apache-xml.jar --dex-file=/system/framework/org.apache.http.legacy.boot.jar --dex-file=/system/framework/legacy-test.jar --oat-file=/data/dalvik-cache/arm/system@framework@boot.oat --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --base=0x70ef7000 --runtime-arg -Xms64m --runt`

and my newest attempt throws 
`Failed to return pre-allocated NoClassDefFoundError
01-21 18:56:39.116  1706  1706 F dex2oat : art/runtime/thread.cc:3035] Check failed: new_exception != nullptr`

**Comment by JesusFreke** [comment]
You should rebuild the various classes.dex files and add them back into their respective .jar files, and then either regenerate the art/oat files on the system partition, or delete them and let the system generate them and store them in the /data partition on first boot.

**Comment by Aaahh** [comment]
@JesusFreke I did the first part myself, then with oat2dex, then with another script so I feel confident that I got that part atleast, the second part where I let the system generate them is where it fails and I don't know why. It gives very vague errors. 

Could not create image space with image file '/system/framework/boot.art' 
that file doesn't even exist, why is it trying, and then right after it fails and I don't know why

**Comment by Aaahh** [comment]
How do I regenerate oat files for the system

**Comment by GroovinChip** [comment]
Hello, I know this has been closed, but I am trying to deodex my Pixel XL on 8.1 and I am failing, using both Fulmics and Ultimate Deodexer. Can someone please let me know exactly what I need to do?

**Comment by Funny-Bunny** [comment]
Tried to deodex 8.1 too, GroovinChip, with SuperR's Kitchen v1.1.7.8, but no luck.  8.0 deodexes without an issue, though. I suppose smali & baksmali need a bump up to resolve the issues for 8.1. We'll just have to wait and see.
