### ISSUE TITLE
smali compile problem

### ISSUE THREAD

**Issue by JesusFreke** [JesusFreke/smali#50]
Original [issue 7](https://code.google.com/p/smali/issues/detail?id=7) created by JesusFreke on 2009-10-17T14:51:42.000Z:

<b>What steps will reproduce the problem?</b>
1. use backsmali to decompile a dex from a apk
2. use smali compile it back, and put the dex back to the apk
3. adb install recompiled.apk

<b>What is the expected output? What do you see instead?</b>
I only get this message.
Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION]
<b>What version of the product are you using? On what operating system?</b>
0.94 &amp; 0.96

<b>Please provide any additional information below.</b>

**Comment by francis-git** [comment]
**Project "smali" has moved to another location on the Internet.**

up link can not click to correct site ,please give me the right site,thx

**Comment by JesusFreke** [comment]
This (github) *is* the correct site.
