### ISSUE TITLE
Invalid debug offset,disassemble fail

### ISSUE THREAD

**Issue by zhengoogle** [JesusFreke/smali#502]
i use baksmali-2.2.0 to disassemble a dex file(classes2.dex),but failed.
the dex file and crash log i upload here:https://pan.baidu.com/s/1o7EhzPC
the crash log: 
Ljcifs/smb/TransPeekNamedPipeResponse;->toString()Ljava/lang/String;: Invalid de
bug offset
Ljcifs/smb/SmbFile;->setLastModified(J)V: Invalid debug offset
Ljcifs/smb/SmbFile;->setPathInformation(IJJ)V: Invalid debug offset
Ljcifs/smb/SmbFile;->setPathInformation(IJJ)V: Invalid debug offset
Ljcifs/smb/SmbFile;->setReadOnly()V: Invalid debug offset
Ljcifs/smb/SmbFile;->setReadWrite()V: Invalid debug offset
Ljcifs/smb/SmbFile;->toString()Ljava/lang/String;: Invalid debug offset

D:\WIN7x64\Android\Decompile\ApkUtils\pro>

**Comment by JesusFreke** [comment]
That isn't a crash, and disassembly hasn't failed. That's a warning message, and disassembly continues with no debug information.
