### ISSUE TITLE
Building smali/backsmali using Java 8

### ISSUE THREAD

**Issue by inessa-aks** [JesusFreke/smali#525]
I can't build smali/baksmali using Java 8.

Is there any way to share these builds in Downloads?

I can't use smali/backsmali Java 7 builds in my project.

Thanks.

**Comment by JesusFreke** [comment]
Replying to your offline email:

It sounds like you're using the wrong versions of the guava library and likely jcommander as well.

If you use maven or gradle to build your project, you can simply reference the smali or baksmali library from maven central, and the correct versions of all the other dependencies should be automatically added to the project.

**Comment by inessa-aks** [comment]
Using maven helped to solve this issue.
