### ISSUE TITLE
[INFO] multidexlib2: multi-dex extensions for dexlib2

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#536]
long time!

i forked multidexlib2 to a subproject and i'm providing binary builds from now on.

info here, in case you want to reference it somewhere:
https://github.com/DexPatcher/multidexlib2

thanks!

**Comment by JesusFreke** [comment]
Nice! I'll keep it in mind :)

**Comment by ale5000-git** [comment]
Is it possible to integrate it in smali / baksmali?

**Comment by JesusFreke** [comment]
My stance is still that the dex file is the "base unit" that smali/baksmali work on. multi-dex is purely an apk concept, and smali/baksmali don't deal with apks, other than being able to read a dex file from them, for convenience.

**Comment by ale5000-git** [comment]
@Lanchon @JesusFreke

And what about doing multidexlib2 as wrapper of official smali / baksmali?

It would be nice if the officially compiled multidexlib2 would work with officially compiled smali / baksmali as separate files.
I mean that when a new version of smali / baksmali get released one could just switch the binaries without recompile multidexlib2.
It would be nice.

**Comment by Lanchon** [comment]
@ale5000-git,

d2 and md2 are different things and JF is totally right to keep them as separate concepts.
d2 does the heavy lifting, with md2 providing an extended interface for multi-dex.
plus, they use different and incompatible free software licenses.

if you use d2 you get updates straight from JF.
if you use md2 you depend on me to upgrade the library.

@JesusFreke,

the need to upgrade multidexlib2 with each dexlib2 upgrade would be greatly reduced if dexlib2 provided the ridiculously small functionality that is missing for a client to be able to auto-detect opcodes based on dex file version. what's needed is moving [DexVersionMap](https://github.com/DexPatcher/dexpatcher-tool/blob/master/multidexlib2/src/main/java/lanchon/multidexlib2/DexVersionMap.java)'s functionality to dexlib2.

btw, i give you permission to modify and re-license DexVersionMap.java in whatever way you want without any kind of attribution.

in reality, md2 can most of the time be used with a newer d2, but this is unsupported.
even opcode auto-detect will work if [Build.VERSION_CODES.CUR_DEVELOPMENT](https://github.com/DexPatcher/dexpatcher-tool/blob/ebec95e44005c3b070a5998f5c1f7e05430a68e7/multidexlib2/src/main/java/lanchon/multidexlib2/DexVersionMap.java#L42) is accepted by dexlib2 as a synonym for the highest API level supported by each version of dexlib2 (and i think this might be the case).

**Comment by JesusFreke** [comment]
Unfortunately, it's not possible to map a dex version to a unique set of opcodes. Take for example, a dex file that's wrapped in an odex that was generated on api version 13 vs 14. Both the dex and the odex versions are the same, but the 0xf0 opcode maps to different opcodes in each (INVOKE_DIRECT_EMPTY vs. INVOKE_OBJECT_INIT_RANGE)

**Comment by Lanchon** [comment]
right, but there is a definite set of opcodes for each dex version on propper dex files. google would only ever extend the opcode set if at all without increasing dex version (i dont think they ever will), and will never make a backwards breaking change without increasing the dex version.

dex files have universal meaning. odex files only have meaning for a particular system. and i dont care about odex, im processing apks.

dexlib should provide whats needed to interpret plain old universal dex files.

the maps i propose are not for odex files but they are needed to read dex files. the strategy is simple: for a dex file version, pass the highest api that uses that version to dexlib. rationale: for a given dex version, dex format can only ever be extended if changed at all, so the latest api will provide all opcodes.

**Comment by Lanchon** [comment]
sorry i was walking round the street when i wrote that.
not well written at all, but i hope the idea got across anyway.
