### ISSUE TITLE
dexlib2 exposes unnecessary detail of the bytecode file format

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#540]
hi JF,

dexlib2 aims, among other things, to provide an abstraction to access dex/odex/oat files, and it does so very well. however there are a couple of instances in which unnecessary detail of the bytecode file format creeps through its interface.

### a) pool overflow detection

take a look at this piece of [real-world dexlib2 client code](https://github.com/DexPatcher/multidexlib2/blob/v2.2.0/src/main/java/lanchon/multidexlib2/DexIO.java#L134-L140). these lines embody intricate knowledge of details of the dex file format:
1. that these 5 sections, and not others, could potentially cause a dex file "overflow" during write.
2. that it's not necessary to check 2 of these 5 sections, as they will never overflow if the remaining 3 don't.

all this is very much a dex format implementation detail at a level that IMHO dexlib2 tries to hide, just like it does with a million other things such as serialization format of sections, etc. in fact, overflow IS a serialization detail. dexlib2 chooses to expose its interface at a level where overflow can't be hidden -and that is totally fine-, but that doesn't negate the value of a better abstraction within its level.

when dexlib2 gets to support dex 038, 2 new sections will need to be added to handle invoke-custom/polymorphic, and then all dexlib2 client code dealing with multi-dex will potentially have to be changed. why is it that dexlib2 clients need to be changed to support such a low level detail as adding a section to the dex format? it's not a necessity, it's just dexlib2 lacking a trivial abstraction.

what's much worse: old client code will happily build with an updated dexlib2, oblivious to the addition of sections, resulting in nasty bugs that will express themselves at runtime. the problem with the current API is that adding sections is in reality a backwards breaking change due to semantics. and the addition won't even trigger compile errors. good library design would call for you now renaming all DexPool.xxxSection entries when transitioning to 038, so at least clients that care cease to compile, but i guess that's too much to ask. but i would like to ask for a solution to prevent this from happening again for 039.

over a year ago we had a conversation that resulted in you exposing item counts of sections so i could write multi-dex, because before that i needed to fork dexlib2 (thank you for that!). at the time i asked that you added one extra thing to prepare for the future, a method such as `int DexPool.getHighestItemCountOfOverflowableSections()` or `boolean DexPool.hasOverflowed(int maxItemCount)`, and even a companion `int DexPool.getStandardMaxItemCount()` that for now returns a constant (but that could change in future dex formats).

these were never added. please consider adding them while you work on 038. updating client code for 038 is now inescapable, but you could make this upcoming update be the last one in this regard.

### b) reading standard dex files

we've talked about this very recently. android has a clear, absolute definition of what dex files are based on their dex version and nothing else. besides these files, dexlib also tries to understand odex/oat files whose meaning is inextricably linked to a particular VM implementation and the framework preloaded onto it. smali succeeds only if the VM is a standard, untouched AOSP VM, and if the framework is fed to it, ultimately because odex/oat files have no meaning outside this context.

this is all as fine and dandy as can be made, except that the most important case of all -standard dex files and their intrinsic meaning- are not fully abstracted by dexlib2. to read such a file, clients have to know how to map dex versions to opcodes, which is a trivially hideable implementation detail for standard dex files, and again it's a moving target that changes with versions of dexlib2. why is it that clients need to be changed to support such a low level detail as a new dex version identifier?

please consider adding something [like this](https://github.com/DexPatcher/multidexlib2/blob/v2.2.0/src/main/java/lanchon/multidexlib2/DexVersionMap.java#L39-L43) with the 038 update, so that this update may be the last dex file version bump to mess with dexlib2 client code.

thank you for your work!!! and definitely looking forward to 038.

**Comment by ale5000-git** [comment]
What of this is still missing?

**Comment by Lanchon** [comment]
#622 is missing

**Comment by Lanchon** [comment]
all done here, thanks!

**Comment by ale5000-git** [comment]
@Lanchon
Re-reading the issue I see that maybe it still miss: DexPool.getStandardMaxItemCount()

Maybe it isn't useful now but it may be useful for debugging if the limit change in the future.

**Comment by Lanchon** [comment]
but there is a public constant instead.

if the limit changes, it will depend on dex version so it wont be a simple
getter. so if such a thing ever happens (unlikely) my idea is removing the
constant at that time to break clients at compile time.

precompiled clients will not break, but use the old value instead, which is
probably for the better.
