### ISSUE TITLE
[Q] invoke-polymorphic and dex version 038

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#543]
hi JF, @narayank,

what is the point of smali [supporting 'invoke-polymorphic'](https://github.com/JesusFreke/smali/commit/afc1f1593936326e1c99f8328bbce8b495865000) if it [supposedly can't read dex 038](https://github.com/JesusFreke/smali/blob/v2.2.1/dexlib2/src/main/java/org/jf/dexlib2/dexbacked/raw/HeaderItem.java#L46)?
aren't 'invoke-polymorphic' and 'invoke-custom' only present in 038?

thanks!

**Comment by Lanchon** [comment]
thanks @ohodson,

woo this is a surprise! i didn't know a parallel version of smali was being hacked at googlesource.com at v2.2.0.

good to know someone's on 038. i see you were working top down and actual interning of the new pool items is not yet implemented.

but anyway, my question was what was the point of supporting 'invoke-polymorphic' opcodes if smali can't read 038. i guess i know the answer now: the opcode commit comes from googlesource and 038 I/O support exists there as well...
https://android-review.googlesource.com/#/c/platform/external/smali/+/368069/

**Comment by ale5000-git** [comment]
Dex version 38 and 39 should be supported now (seen fromthe recent commits).
