### ISSUE TITLE
Support deodex Oreo?

### ISSUE THREAD

**Issue by ale8530** [JesusFreke/smali#555]
I just wanted to know with extreme kindness, if you are working OREO, I do not care about timing, but I wanted to know if there will be new news soon

**Comment by JesusFreke** [comment]
It's on my radar :)

**Comment by ale8530** [comment]
Thanks for your reply

**Comment by lcweik** [comment]
you can use this repo to deodex android o's vdex file.

**Comment by lcweik** [comment]
https://github.com/lcweik/smali

**Comment by ale5000-git** [comment]
@lcweik
Hi,
could you please also post somewhere compiled jar files?
