### ISSUE TITLE
baksmali then smali not reproducing original dex

### ISSUE THREAD

**Issue by kalemeister** [JesusFreke/smali#572]
Hello.

I have been having troubles using apktool to disassemble and reassemble an apk I'm trying to work on. I believe the issue is with baksmali/smali (2.2.2). When I disassemble and reassemble (making no edits to smali source) with apktool (2.3.0), sign, align - the final apk is not the same in size as the original, also it crashes immediately on start.
So I tried extracting the classes.dex and doing baksmali and smali on it. The reassembled dex is not equal in size as the original.
Also if I baksmali/smali the 'unoriginal, unequal size' dex, the 3rd round-produced dex is equal to the 2nd round dex.

I've tried also just resigning, realigning the original apk (no disassemble, reassemble) and it runs okay.
Also I've tried doing this on a randomly downloaded game. It disassembled and reassembled fine with apktool and  #baksmali/smali.

Here is the apk in question:
https://apkpure.com/%E3%81%B2%E3%81%8B%E3%82%8A%EF%BD%94%EF%BD%96%E3%81%A9%E3%81%93%E3%81%A7%E3%82%82/jp.co.plala.Dokodemo/download/333-APK?from=details%2Fversion

**Comment by JesusFreke** [comment]
A baksmali->smali round trip should always produce an equivalent - but not bytewise identical - dex file. It's expected that the dex file will differ in contents and size slightly.

**Comment by kalemeister** [comment]
Thanks for the quick response. So are you trying to say the issue is not with baksmali/smali?

What you're saying doesn't match with my findings.

1. baksmali->smali on a randomly picked apk produced an equivalent and bytewise identical dex.
2. If a baksmali->smali round trip does not produce bytewise identical dex files, you should be able to in theory do X rounds of baksmali->smali and produce different dex files each time. This didn't happen with me.

If the issue is not with baksmali/smali do you have any theories/suggestions what it is?

**Comment by JesusFreke** [comment]
There are different ways to "build" a dex file. e.g. different item orderings, etc. A dex file built by smali will always be different than a dex file build by dx. But doing a round trip on a dex file that was originally produced by smali could result in a dex file that's bytewise identical to the original - although it's not guaranteed.

I'm not saying it is or isn't a problem with smali/baksmali - just that the fact that the dex file isn't bytewise identical isn't an issue.

I would recommend investigating the crash you mentioned, and try to understand why it's crashing.

**Comment by Lanchon** [comment]
a smali round-trip should produce a semantically-equivalent dex (or else it's a bug), but *not* a bit-wise copy.

this is by design. there are trade-offs to be made in the design of a program like smali, and these are the chosen trade-offs. you need to look elsewhere if the design of smali does not fit your needs.

i suggest you test apktool round-trips: disable the processing of both code and resources first, and check if it produces a working apk. next, enable them independently. it would be interesting if your app fails only when code processing is enabled and not otherwise.

**Comment by kalemeister** [comment]
Thanks for the suggestions.

I tried the following...
`apktool d -rfs test.apk`
and
`apktool d -rf test.apk`

Both when reassembled crash.

I found the app writes stack traces to a log. Here is the log

>  java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/jp.co.plala.Dokodemo-1/lib/arm/libtwonky-jni.so"
>     at java.lang.Runtime.loadLibrary(Runtime.java:372)
>     at java.lang.System.loadLibrary(System.java:1076)
>     at com.pv.twonky.mediacontrol.MediaControlImpl.loadLibrary(MediaControlImpl.java:173)
>     at com.pv.twonky.mediacontrol.MediaControlImpl.init(MediaControlImpl.java:282)
>     at com.pv.twonky.mediacontrol.MediaControl.init(MediaControl.java:539)
>     at jp.co.plala.Dokodemo.DokodemoApp.a(DokodemoApp.java:579)
>     at jp.co.plala.Dokodemo.DokodemoApp.N(DokodemoApp.java:772)
>     at jp.co.plala.Dokodemo.DokodemoApp.b(DokodemoApp.java:71)
>     at jp.co.plala.Dokodemo.o.run(DokodemoApp.java:293)
>     at java.lang.Thread.run(Thread.java:818)

This error doesn't happen with the original apk. The .so library exists in that path.
Is it possible apktool is messing up a reference somewhere? I'm not familiar with this. Or maybe this requires patching this .so library to not return JNI_ERR in that referenced method.

**Comment by JesusFreke** [comment]
It's most likely some form of copy protection implemented in JNI

**Comment by kalemeister** [comment]
Understood. Thank you very much for the responses.

**Comment by Lanchon** [comment]
yep, some form of anti-tampering. one way around it might be the xposed framework. (of course some apps detect it and refuse to run, but that is easy to check.)

**Comment by hacker1024** [comment]
Does anyone know how to reproduce a bit-perfect dex? I'm trying to make a binary patch.

**Comment by dclaudiud** [comment]
Before concluding that baksmali/smali procedures are the issue, try not to use apktool, and not even unzip the apk, baksmali the dex file you want to patch, do your modifications, and assemble it back with smali, update the apk file (the zip), delete the initial signatures located in the META-INF/ directory, sign with v1 and v2 enabled, and try installing. apktool does way more than what baksmali/smali does, and crashes can occur because of other operations.
