### ISSUE TITLE
[not a bug] org.jf.util.ExceptionWithContext: Multiple definitions for method <method>

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#573]
hi,

writing a dex that has a class with two methods of equal name and signature, one direct and one virtual, produces this exception:
```
org.jf.util.ExceptionWithContext: Multiple definitions for method <method>
```

and writing a dex that has a class with two fields of equal name and type, one static and one instance, produces this exception:
```
org.jf.util.ExceptionWithContext: Multiple definitions for field <field>
```

however, because these items are accessed via different opcodes (eg: sput vs iput, or invoke-direct vs invoke-virtual), it would be possible to have functional classes with these kinds of name clashes.

**the question here is whether ART supports these name clashes or rejects them.** [the spec](https://source.android.com/devices/tech/dalvik/dex-format) seems to disallow method name clashes by saying "The method_idx of a virtual method must not be the same as any direct method". however, there is no equivalent phrasing pertaining to fields.

**have you actually tested that both of these name clashes are rejected by ART, or did you assume it?**

thank you!

**Comment by JesusFreke** [comment]
Right, virtual + direct methods with the same signature are not allowed. I don't remember if I tested the case of instance + static fields with same signature.

**Comment by Lanchon** [comment]
thank you!

BTW, i've tested [this](https://android.googlesource.com/platform/art/+/master/test/097-duplicate-method/) (see [history](https://android.googlesource.com/platform/art/+/b9131b191567e984a5f3a1d125b36014b67b47b6)).
(it is not the case stated in this issue: the duplicate methods in this test are both direct.)

i found:

- running on MM ART does produce "Success!" of course.
- baksmali correctly chooses the first method of the dex:
```
.class LTest;
.super Ljava/lang/Object;
.source "Test.j"


# direct methods
.method public static run()Ljava/lang/Object;
    .registers 1

    new-instance v0, Ljava/lang/Object;

    invoke-direct {v0}, Ljava/lang/Object;-><init>()V

    return-object v0
.end method

# duplicate method ignored
# .method public static run()Ljava/lang/Object;
#     .registers 1

#     const/4 v0, 0x0

#     return-object v0
# .end method
```
- dexlib2 only passes the correct method to its clients, as evidenced by doing a dex read/write cycle:
```
$ dexpatcher classes.dex -o classes-dexpatcher.dex
0 error(s), 0 warning(s)
$ baksmali d classes-dexpatcher.dex 
$ cat out/Test.smali
.class LTest;
.super Ljava/lang/Object;
.source "Test.j"


# direct methods
.method public static run()Ljava/lang/Object;
    .registers 1

    new-instance v0, Ljava/lang/Object;

    invoke-direct {v0}, Ljava/lang/Object;-><init>()V

    return-object v0
.end method
```
- and master dex2jar also handles this fine, keeping the right method:
```
dex2jar classes.dex -> ./classes-dex2jar.jar
GLITCH: duplicated method LTest;.run()Ljava/lang/Object; @000002f1
WARN: skip method LTest;.run()Ljava/lang/Object; @000002f1
```

i still don't have a definitive answer for methods and fields as described in this issue. i'll update later. thanks!

**Comment by Lanchon** [comment]
it seems the only way to properly test this is to patch dexlib2 to construct test cases.

i just did something else: i tried to invoke a private non-static method (which is direct) with INVOKE_VIRTUAL on MM ART. if the direct and virtual method pools were handled independently, it would be expected that ART threw an error saying that the method was not found, as it should only look in the virtual pool. however, it found the method in the direct pool and threw this:
```
java.lang.VerifyError: Verifier rejected class test.Main$B due to bad method void test.Main$B.wrapTestMethod(java.lang.String) (declaration of 'test.Main$B' appears in /sdcard/run-via-adb.zip)
	at test.Main.main(Main.java:26)
```

this is a strong hint that this kind of method overloading across the direct/virtual barrier is rejected by ART,

**Comment by JesusFreke** [comment]
Also, see https://github.com/JesusFreke/smali/issues/164 for more context. (This was an old bug that was migrated from googlecode)

**Comment by Lanchon** [comment]
thanks!

i see this:
> smali will ignore any duplicate methods/fields with a warning, when it is safe to do so. If there is a duplicate non-static direct and virtual method, it is not safe to ignore one of them, so it errors out.

why is a static/virtual method pair "safe to ignore" and a non-static direct/virtual pair isn't?

what does "safe to ignore" means in this context? shouldn't smali never ignore and always error, and backsmali ignore or error mimicking what ART does?

BTW, the reason i'm fiddling with this stuff is that i implemented the changes discussed [here](https://github.com/DexPatcher/dexpatcher-tool/issues/19), but i'm reluctant to publish the new version until i'm certain that ART rejects these duplications. if it doesn't, then i need to roll back all that work.

**Comment by JesusFreke** [comment]
I'm pretty sure that "not safe" statement was referring to the fact that it would fail dalvik's verification.

**Comment by Lanchon** [comment]
ok!

so i disabled the duplicate member tests in [a dexlib2 fork](https://github.com/DexPatcher/smali/commits/barrier). then i rolled back dexpatcher to where it supports pairs of matching direct/virtual methods and static/instance fields and built [a version with the forked dexlib2](https://github.com/DexPatcher/dexpatcher-tool/commits/barrier). i'll post the build here in case anybody wants to experiment. this dexpatcher build can be used to build test cases from regular javac output (remove the .txt extension): [dexpatcher-1.5.1-barrier.jar](https://github.com/JesusFreke/smali/files/1490123/dexpatcher-1.5.1-barrier.jar.txt).

next i built test cases. i start with [these classes](https://github.com/DexPatcher/dexpatcher-tool/blob/barrier/test/source/src/main/java/test/Main.java), then patch them to include duplicate fields or methods using [this patch](https://github.com/DexPatcher/dexpatcher-tool/blob/barrier/test/patch/src/main/java/test/Main.java). the result is this dex: [patched.dex](https://github.com/JesusFreke/smali/files/1490137/patched.dex.txt). it contains several tests that are run in sequence. here is the baksmali of one such test: [Main$FieldUseBoth.smali](https://github.com/JesusFreke/smali/files/1490155/Main.FieldUseBoth.smali.txt).

running the dex on MM ART produces this output:
```
FieldPresence:
main

FieldUseOne:
main
instance f: 42

FieldUseBoth:
java.lang.IncompatibleClassChangeError: Expected 'int test.Main$FieldUseBoth.f' to be a static field rather than a instance field (declaration of 'test.Main$FieldUseBoth' appears in /sdcard/run-via-adb.zip)
	at test.Main$FieldUseBoth.<clinit>(Main.java:51)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:324)
	at java.lang.Class.forName(Class.java:285)
	at test.Main.main(Main.java:27)

MethodStaticPresence:
main

MethodPrivatePresence:
main

MethodStaticUseOne:
static m
main

MethodPrivateUseOne:
private m
main

MethodStaticUseBoth:
static m
java.lang.IncompatibleClassChangeError: The method 'void test.Main$MethodStaticUseBoth.m()' was expected to be of type virtual but instead was found to be of type static (declaration of 'test.Main$MethodStaticUseBoth' appears in /sdcard/run-via-adb.zip)
	at test.Main$MethodStaticUseBoth.main__$appendPatch(Main.java:73)
	at test.Main$MethodStaticUseBoth.main(Main.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at test.Main.main(Main.java:28)

MethodPrivateUseBoth:
java.lang.VerifyError: Verifier rejected class test.Main$MethodPrivateUseBoth due to bad method void test.Main$MethodPrivateUseBoth.main__$appendPatch(java.lang.String[]) (declaration of 'test.Main$MethodPrivateUseBoth' appears in /sdcard/run-via-adb.zip)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:324)
	at java.lang.Class.forName(Class.java:285)
	at test.Main.main(Main.java:27)

```

it seems like ART loads only one of the duplicate fields or methods (presumably the first on the file, but that is irrelevant to me), exactly as if they were full duplicates, but these are in fact on different sides of the static/instance or direct/virtual barriers. next, with only one of the members loaded:
1) if only that member is accessed, all is well.
2) if the missing field is accessed, ART throws:
```
java.lang.IncompatibleClassChangeError: Expected '<field>' to be a static field rather than a instance field
```
3) if the missing method is accessed when one is static and the other is not, ART throws:
```
java.lang.IncompatibleClassChangeError: The method '<method>' was expected to be of type virtual but instead was found to be of type static
```
4) if a non-static method is accessed with the wrong choice of invoke-virtual vs invoke-direct, ART verification fails:
```
java.lang.VerifyError: Verifier rejected class <class> due to bad method <method>
```

**in any case, this proves that ART does not support duplicated fields or methods as described in the original post of this issue, and dexlib2 is thus correct in refusing to build such a dex.**

for completeness: dex2jar master translates the duplicate members correctly into java bytecode. here is the translation: [patched-dex2jar.jar](https://github.com/JesusFreke/smali/files/1490184/patched-dex2jar.jar.txt). java 7 VM fails earlier than ART and refuses to load any class where fields or methods are duplicated. here is [the output](https://github.com/DexPatcher/dexpatcher-tool/blob/ec15743cf2f6930f62f04d0981c7b8059177e60b/test/shell-test-ref.txt#L127-L288) of running the converted dex.
