### ISSUE TITLE
Failed to import .jar file into inteliJ Idea 2017.2.5

### ISSUE THREAD

**Issue by allandereal** [JesusFreke/smali#578]
Fail to load plugin descriptor from file smali-2.2.2.jar
While installing plugin from disk

**Comment by JesusFreke** [comment]
I think you might be using the wrong file. smalidea-0.05.zip is the one you want :)

**Comment by allandereal** [comment]
@JesusFreke Ive managed to download and import smalidea-0.05.zip into inteliJ but the text for .smali files is still plain white!. what could be wrong?

**Comment by JesusFreke** [comment]
Did you install it as a plugin? Is the plugin disabled or anything?

**Comment by allandereal** [comment]
It has worked. i had to restart intelij thanx.
