### ISSUE TITLE
Samsung Oreo core-oj.jar issue

### ISSUE THREAD

**Issue by BlackMesa123** [JesusFreke/smali#596]
Seems like latest baksmali can't decode 1 line in java/lang/invoke/MethodHandle class and it replaces the invoke with "nop", this causes bootloop issue in Samsung Oreo, hope someone can help me.
Here's the faulty method:

> .method public varargs invokeWithArguments([Ljava/lang/Object;)Ljava/lang/Object;
>     .locals 3
>     .annotation system Ldalvik/annotation/Throws;
>         value = {
>             Ljava/lang/Throwable;
>         }
>     .end annotation
> 
>     const/4 v0, 0x0
> 
>     monitor-enter p0
> 
>     :try_start_0
>     iget-object v1, p0, Ljava/lang/invoke/MethodHandle;->cachedSpreadInvoker:Ljava/lang/invoke/MethodHandle;
> 
>     if-nez v1, :cond_0
> 
>     invoke-virtual {p0}, Ljava/lang/invoke/MethodHandle;->type()Ljava/lang/invoke/MethodType;
> 
>     move-result-object v1
> 
>     const/4 v2, 0x0
> 
>     invoke-static {v1, v2}, Ljava/lang/invoke/MethodHandles;->spreadInvoker(Ljava/lang/invoke/MethodType;I)Ljava/lang/invoke/MethodHandle;
> 
>     move-result-object v1
> 
>     iput-object v1, p0, Ljava/lang/invoke/MethodHandle;->cachedSpreadInvoker:Ljava/lang/invoke/MethodHandle;
> 
>     :cond_0
>     iget-object v0, p0, Ljava/lang/invoke/MethodHandle;->cachedSpreadInvoker:Ljava/lang/invoke/MethodHandle;
>     :try_end_0
>     .catchall {:try_start_0 .. :try_end_0} :catchall_0
> 
>     monitor-exit p0
> 
>     #disallowed odex opcode
>     #invoke-super-quick {v0, p0, p1}, vtable@3970
>     nop
> 
>     and-int/2addr p0, v0
> 
>     move-result-object v1
> 
>     return-object v1
> 
>     :catchall_0
>     move-exception v1
> 
>     monitor-exit p0
> 
>     throw v1
> .end method

**Comment by JesusFreke** [comment]
the "disallowed odex opcode" warning should never be generated when deodexing - only when disassembling normally.

Please share the exact command you are using

**Comment by BlackMesa123** [comment]
Yeah that's what I'm trying to do. Deodex was fine and system booted, the cmd I used is this

> **java -jar baksmali.jar d classes.dex -l --di false --sl**

**Comment by JesusFreke** [comment]
Yes, you are just disassembling an oat file. If you want to be able to re-assemble it, you must deodex it, to convert the optimized opcodes like "invoke-super-quick" back to their unoptimized equivalent

**Comment by BlackMesa123** [comment]
So I managed to deodex successfully the core-oj with this cmd:
> **java -jar baksmali.jar x boot.oat/core-oj.jar -a 26 --di false -l -o out --sl -d framework/arm64**
Now the faulty part changed from this
`    #disallowed odex opcode
    #invoke-super-quick {v0, p0, p1}, vtable@3970
    nop

    and-int/2addr p0, v0`
to this:
`    #Proto index out of bounds: 12303
    #invoke-polymorphic {v0, p0, p1}, Ljava/lang/invoke/MethodHandle;->invoke([Ljava/lang/Object;)Ljava/lang/Object;, method_proto@12303
    nop`
Should I try to assemble the dex by changing that part to this?
`    invoke-super-quick {v0, p0, p1}, Ljava/lang/invoke/MethodHandle;->invoke([Ljava/lang/Object;)Ljava/lang/Object;

    and-int/2addr p0, v0`

**Comment by JesusFreke** [comment]
The invoke-super-quick/invoke-polymorphic mix up is because invoke-super-quick is no longer a valid opcode, but back when it was, it used the same opcode value as the new invoke-polymorphic opcode.

The "proto index out of bounds" makes it sound like something is wrong with the oat file itself.

Can you try:

    baksmali d -a 26 classes.dex

And paste the relevant code.

Also, please include the output of:

    baksmali dump classes.dex | grep proto_ids_size

**Comment by BlackMesa123** [comment]
With the disassembling cmd the faulty line is the same, except ofc for the registers/debug info, here's the whole method

> .method public varargs invokeWithArguments([Ljava/lang/Object;)Ljava/lang/Object;
>     .registers 5
>     .param p1, "arguments"    # [Ljava/lang/Object;
>     .annotation system Ldalvik/annotation/Throws;
>         value = {
>             Ljava/lang/Throwable;
>         }
>     .end annotation
> 
>     .prologue
>     .line 636
>     const/4 v0, 0x0
> 
>     .line 637
>     .local v0, "invoker":Ljava/lang/invoke/MethodHandle;
>     monitor-enter p0
> 
>     .line 638
>     :try_start_2
>     iget-object v1, p0, Ljava/lang/invoke/MethodHandle;->cachedSpreadInvoker:Ljava/lang/invoke/MethodHandle;
> 
>     if-nez v1, :cond_11
> 
>     .line 639
>     invoke-virtual {p0}, Ljava/lang/invoke/MethodHandle;->type()Ljava/lang/invoke/MethodType;
> 
>     move-result-object v1
> 
>     const/4 v2, 0x0
> 
>     invoke-static {v1, v2}, Ljava/lang/invoke/MethodHandles;->spreadInvoker(Ljava/lang/invoke/MethodType;I)Ljava/lang/invoke/MethodHandle;
> 
>     move-result-object v1
> 
>     iput-object v1, p0, Ljava/lang/invoke/MethodHandle;->cachedSpreadInvoker:Ljava/lang/invoke/MethodHandle;
> 
>     .line 642
>     :cond_11
>     iget-object v0, p0, Ljava/lang/invoke/MethodHandle;->cachedSpreadInvoker:Ljava/lang/invoke/MethodHandle;
>     :try_end_13
>     .catchall {:try_start_2 .. :try_end_13} :catchall_1a
> 
>     .local v0, "invoker":Ljava/lang/invoke/MethodHandle;
>     monitor-exit p0
> 
>     .line 645
>     #Proto index out of bounds: 12303
>     #invoke-polymorphic {v0, p0, p1}, Ljava/lang/invoke/MethodHandle;->invoke([Ljava/lang/Object;)Ljava/lang/Object;, method_proto@12303
>     nop
> 
>     move-result-object v1
> 
>     return-object v1
> 
>     .line 637
>     .local v0, "invoker":Ljava/lang/invoke/MethodHandle;
>     :catchall_1a
>     move-exception v1
> 
>     monitor-exit p0
> 
>     throw v1
> .end method

The dump cmd throws errors:

> org.jf.dexlib2.dexbacked.DexBackedDexFile$InvalidItemIndex: Field index out of bounds: 33876
>         at org.jf.dexlib2.dexbacked.DexBackedDexFile.getFieldIdItemOffset(DexBackedDexFile.java:163)
>         at org.jf.dexlib2.dexbacked.reference.DexBackedFieldReference.<init>(DexBackedFieldReference.java:46)
>         at org.jf.dexlib2.dexbacked.reference.DexBackedReference.makeReference(DexBackedReference.java:51)
>         at org.jf.dexlib2.dexbacked.instruction.DexBackedInstruction21c.getReference(DexBackedInstruction21c.java:54)
>         at org.jf.dexlib2.dexbacked.raw.CodeItem$1.annotateDefaultInstruction(CodeItem.java:316)
>         at org.jf.dexlib2.dexbacked.raw.CodeItem$1.annotateItem(CodeItem.java:148)
>         at org.jf.dexlib2.dexbacked.raw.SectionAnnotator.annotateSectionInner(SectionAnnotator.java:94)
>         at org.jf.dexlib2.dexbacked.raw.SectionAnnotator.annotateSection(SectionAnnotator.java:71)
>         at org.jf.dexlib2.dexbacked.raw.CodeItem$1.annotateSection(CodeItem.java:75)
>         at org.jf.dexlib2.dexbacked.raw.util.DexAnnotator.writeAnnotations(DexAnnotator.java:166)
>         at org.jf.baksmali.DumpCommand.dump(DumpCommand.java:104)
>         at org.jf.baksmali.DumpCommand.run(DumpCommand.java:77)
>         at org.jf.baksmali.Main.main(Main.java:102)
> 
> org.jf.dexlib2.dexbacked.DexBackedDexFile$InvalidItemIndex: Field index out of bounds: 29780
>         at org.jf.dexlib2.dexbacked.DexBackedDexFile.getFieldIdItemOffset(DexBackedDexFile.java:163)
>         at org.jf.dexlib2.dexbacked.reference.DexBackedFieldReference.<init>(DexBackedFieldReference.java:46)
>         at org.jf.dexlib2.dexbacked.reference.DexBackedReference.makeReference(DexBackedReference.java:51)
>         at org.jf.dexlib2.dexbacked.instruction.DexBackedInstruction21c.getReference(DexBackedInstruction21c.java:54)
>         at org.jf.dexlib2.dexbacked.raw.CodeItem$1.annotateDefaultInstruction(CodeItem.java:316)
>         at org.jf.dexlib2.dexbacked.raw.CodeItem$1.annotateItem(CodeItem.java:148)
>         at org.jf.dexlib2.dexbacked.raw.SectionAnnotator.annotateSectionInner(SectionAnnotator.java:94)
>         at org.jf.dexlib2.dexbacked.raw.SectionAnnotator.annotateSection(SectionAnnotator.java:71)
>         at org.jf.dexlib2.dexbacked.raw.CodeItem$1.annotateSection(CodeItem.java:75)
>         at org.jf.dexlib2.dexbacked.raw.util.DexAnnotator.writeAnnotations(DexAnnotator.java:166)
>         at org.jf.baksmali.DumpCommand.dump(DumpCommand.java:104)
>         at org.jf.baksmali.DumpCommand.run(DumpCommand.java:77)
>         at org.jf.baksmali.Main.main(Main.java:102)
> 
> org.jf.dexlib2.dexbacked.DexBackedDexFile$InvalidItemIndex: Field index out of bounds: 63784
>         at org.jf.dexlib2.dexbacked.DexBackedDexFile.getFieldIdItemOffset(DexBackedDexFile.java:163)
>         at org.jf.dexlib2.dexbacked.reference.DexBackedFieldReference.<init>(DexBackedFieldReference.java:46)
>         at org.jf.dexlib2.dexbacked.reference.DexBackedReference.makeReference(DexBackedReference.java:51)
>         at org.jf.dexlib2.dexbacked.instruction.DexBackedInstruction21c.getReference(DexBackedInstruction21c.java:54)
>         at org.jf.dexlib2.dexbacked.raw.CodeItem$1.annotateDefaultInstruction(CodeItem.java:316)
>         at org.jf.dexlib2.dexbacked.raw.CodeItem$1.annotateItem(CodeItem.java:148)
>         at org.jf.dexlib2.dexbacked.raw.SectionAnnotator.annotateSectionInner(SectionAnnotator.java:94)
>         at org.jf.dexlib2.dexbacked.raw.SectionAnnotator.annotateSection(SectionAnnotator.java:71)
>         at org.jf.dexlib2.dexbacked.raw.CodeItem$1.annotateSection(CodeItem.java:75)
>         at org.jf.dexlib2.dexbacked.raw.util.DexAnnotator.writeAnnotations(DexAnnotator.java:166)
>         at org.jf.baksmali.DumpCommand.dump(DumpCommand.java:104)
>         at org.jf.baksmali.DumpCommand.run(DumpCommand.java:77)
>         at org.jf.baksmali.Main.main(Main.java:102)
> 
> Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
>         at org.jf.dexlib2.util.AnnotatedBytes.writeAnnotations(AnnotatedBytes.java:292)
>         at org.jf.dexlib2.dexbacked.raw.RawDexFile.writeAnnotations(RawDexFile.java:98)
>         at org.jf.dexlib2.dexbacked.raw.util.DexAnnotator.writeAnnotations(DexAnnotator.java:169)
>         at org.jf.baksmali.DumpCommand.dump(DumpCommand.java:104)
>         at org.jf.baksmali.DumpCommand.run(DumpCommand.java:77)
>         at org.jf.baksmali.Main.main(Main.java:102)
