### ISSUE TITLE
2.2.3 downloads?

### ISSUE THREAD

**Issue by ilovezfs** [JesusFreke/smali#599]
https://bitbucket.org/JesusFreke/smali/downloads/smali-2.2.3.jar is 404

**Comment by Biggy1606** [comment]
http://www28.zippyshare.com/v/ZMSg9h4W/file.html

**Comment by ilovezfs** [comment]
@JesusFreke why are the downloads not at https://bitbucket.org/JesusFreke/smali/downloads as usual?

**Comment by ale5000-git** [comment]
Probably it was removed but now there is 2.2.4

**Comment by ilovezfs** [comment]
Thanks @ale5000-git! Voilà https://github.com/Homebrew/homebrew-core/pull/29055
