### ISSUE TITLE
Selectively choose classes for disassembly

### ISSUE THREAD

**Issue by hypersimple** [JesusFreke/smali#601]
Sorry to bother you.

Is there a way to choose which classes to disassemble, to generate Smali files?

If not, could you mention the corresponding place in the source code, so I can modify it myself?

I really appreciate your help.

**Comment by JesusFreke** [comment]
baksmali d blah.apk --classes Lsome/app/SomeClass;,Lsome/app/AnotherClass;

**Comment by hypersimple** [comment]
Thanks!

Is there a way to exclude the classes by name?

**Comment by JesusFreke** [comment]
No, not currently

**Comment by hypersimple** [comment]
When I use the command on Mac:
`java -jar ./baksmali-2.2.2.jar d XXX.apk -o output_folder --classes Lio/sqlc/SQLitePlugin`

Nothing is generated in the folder. The same happens when I remove "-o output_folder".

However, if I do not enter "--classes Lio/sqlc/SQLitePlugin", the output smali files are generated correctly.

The "Lio/sqlc/SQLitePlugin" is retrieved by the command:
`java -jar ./baksmali-2.2.2.jar list class XXX.apk`

Do you have any idea about the problem?
I tried several files with APK and DEX formats, several command formats like with ";" at the end of class name, and no "L" before the class name, and two versions of baksmali, the problem remains the same.
I searched on the Internet but cannot get any hint.

**Comment by JesusFreke** [comment]
It looks like you missed the semicolon at the end of the type name. You may have to quote the class name, if the shell interprets the semicolon (not sure if it does, off hand)

**Comment by JesusFreke** [comment]
Also, a somewhat crappy way to do what you want: (note: untested :))

baksmali list classes blah.apk | grep <some filter expression> | xargs baksmali d blah.apk --classes

**Comment by hypersimple** [comment]
Thanks for your help.

Another question:
How to output the static-encoded strings of an APK?
(NOT the class/package names, path, or similar stuff. NOT the output from the command "strings")

You can just mention the place where the related code is.

Thanks a lot again.

**Comment by JesusFreke** [comment]
The string pool contains any string that is referenced anywhere in the dex file. This includes any string constant in the code, any class names, and source files, etc.

If you want to get only the strings that are used as string constants, you would need to iterate over all the bytecode and collect any constants from const-string instructions, and likely also from static field initializers. And possibly strings referenced by annotations too, if you're interested in that.

**Comment by hypersimple** [comment]
For example, if I need to collect any constants from const-string instructions, what functions/files should I look at?
I found some hints with `CONST_STRING(0x1a, "const-string", ...` at `dexlib2/Opcode.java`. But it seems just a macro constant for reference.

**Comment by JesusFreke** [comment]
You could use dexlib2 to iterate over all instructions in all methods, looking for the instructions/constants that you're interested in.

See, e.g. DexFileFactory.loadDexFile for how to create a DexFile object. From there, you can iterate over the classes in the dex file, and the methods in each class, etc.
