### ISSUE TITLE
Android Profiler vs DDMS use

### ISSUE THREAD

**Issue by lars1298** [JesusFreke/smali#604]
Will this work with Android Studio 3.0 which has depricated DDMS, when I try and use Android Profiler, I get the following error:

Unable to open debugger port (localhost:8700): java.io.IOException "handshake failed - connection prematurally closed"

I have tried rebooting my tablet, adb, android studio, etc.  Nothing seems to fix this issue.

**Comment by JesusFreke** [comment]
I haven't used android profiler. Does it have a list of processes running on the device? You have to tell it somehow what process you want to debug. Also,  double-check what port it's assigning. I'm not sure if 8700 is/was defined by DDMS, or by the device.

**Comment by lars1298** [comment]
This page helped a bit, I did also reboot my machine, and ran AS as admin. 
 
https://crosp.net/blog/android/android-reverse-engineering-debugging-smali-using-smalidea/
