### ISSUE TITLE
Android: initialization values of static non-final fields missing in Jimple representation

### ISSUE THREAD

**Issue by jpstotz** [JesusFreke/smali#605]
I encounter a problem with static fields in the Android/DEX part of Soot. Consider the following simple class:

    public class SimpleClass {
       public static String A = "!AABBCCDD!";
    }

If I compile this class to SimpleClass.class and then generate the Jimple code from it everything is fine.
`java -cp  soot-3.1.0-20180424.084712-9-jar-with-dependencies.jar soot.Main -w -f jimple  -cp target/classes/;"%JAVA_HOME%\jre\lib\rt.jar";"%JAVA_HOME%\jre\lib\jce.jar" SimpleClass`

The generated Jimple code contains the correct `<clinit>`:
    
    static void <clinit>()
    {
         <SimpleClass: java.lang.String A> = "!AABBCCDD!";
         return;
    }

If I do the same using a DEX file containing this class the `<clinit>` misses the initial value of the field:

    static void <clinit>()
    {
        return;
    }

I did this using different versions of Soot from the [Snapshot repository](https://soot-build.cs.uni-paderborn.de/nexus/#browse/browse/components:soot-snapshot). It does not matter if I use the oldest or the newest (3.1) version the result is always the same as above.

For making sure that the variable is really present in the dex code I also decompiled the APK using different versions of `apktool` and checked the Smali code - the initialization value was always present:

    # static fields
    .field public static A:Ljava/lang/String; = "!AABBCCDD!"

**Comment by Lanchon** [comment]
the compiler/code generator can choose to put simple static field
initialization values in the field definitions themselves or in the code of
the class constructor <clinit>.

(i suspect this has to do with early javas that might not have had <clinit>
and only accepted simple init literals instead.)

experiment: try a runtime-computed init expression instead of a literal
value to force usage of <clinit> for field initialization.

>

**Comment by jpstotz** [comment]
@Lanchon: Oh I just realized that I accidentally exchanged the GitHub project in the web browser when creating this issue. Originally I wanted to create this issue in https://github.com/Sable/soot/issues 

Sorry for the inconvenience.
