### ISSUE TITLE
Smali tool v 2.2.2 does not support dex file version 038 (introduced in Android SDK 26)

### ISSUE THREAD

**Issue by kunalv0902** [JesusFreke/smali#614]
Hi, 
I get following exception when i try to baksmali a dex file build for minimumSDK version = 26.
Exception in thread "main" org.jf.dexlib2.util.DexUtil$UnsupportedFile: Dex version 038 is not supported
        at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:94)
        at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:71)
I found that dex file version for Android SDK 25 (Android 7.1.1) was 037. So, there must be some changes in latest dex file version. 
Is there anybody aware of roadmap/plan to add support of dex file version 038 in smali/baksmali tool?
Thanks,
Kunalv0902

**Comment by ale5000-git** [comment]
It is already supported in the code, you can built it from GitHub yourself now or wait the new release.

**Comment by kunalv0902** [comment]
Thanks @ale5000-git . Yes, i also noticed the version 2.2.4 tag applied that includes changes for support of dex file version 38 & 39.
Thanks again.
