### ISSUE TITLE
msfvenom -x [Problem with the most famous and used APPS]

### ISSUE THREAD

**Issue by Vinicius379** [JesusFreke/smali#631]
the template works normally with many applications, but the most famous of big companies, like f4c3b00k, 1n5t4gr4m, g00gl3 dr1v3, t1nd3r, Wh4tsup, sp0t1fy and others.
Does anyone know if it is because the code has something that does not allow the injection of the payload with meterpreter or if I should install and confuse something?
I have already installed the default-jre programs,
default-jdk, apktool, zipalign, android-sdk, openjdk-9-jdk

**Comment by JesusFreke** [comment]
What does this have to do with smali/baksmali?

Also, "f4c3b00k"? Really? :p

**Comment by Vinicius379** [comment]
facebook instagram whatsapp tinder crsh royale, candy crush uber e etc.
What does this have to do with smali/baksmali?
