### ISSUE TITLE
Cannot recompile after editing manifest file.

### ISSUE THREAD

**Issue by VikramKharvi** [JesusFreke/smali#634]
Hello sir,
            I have decompiled a apk without using -s or -r in command so that I can edit manifest but I am unable to recompile it as it show me following error.
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/aapt/linux/aapt (defaulting to $PATH binary) W: A/ ( 8230): First type is not attr! brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [aapt, p, --min-sdk-version, 14, --target-sdk-version, 21, --version-code, 116648316, --version-name, 102.0.0.11.163, --no-version-vectors, -F, /tmp/APKTOOL6036305568256649376.tmp, -0, xzs, -0, assets/secondary-program-dex-jars/secondary.dex.jar.xzs, -0, png, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/original3/res, -M, /root/original3/AndroidManifest.xml]

The apk compiles if I use -r in my decompilation command but I am unable to edit my manifest as it is encoded.
Do help me solve this.
Thanking you

**Comment by JesusFreke** [comment]
I would recommend you report issues on the repository for the tool you are using :). See, https://github.com/iBotPeaches/Apktool
