### ISSUE TITLE
 Unsupported oat version: 45

### ISSUE THREAD

**Issue by cang** [JesusFreke/smali#644]
java -jar baksmali-2.2.4.jar deodex -c boot.oat -d framework OppoGuardElf.odex -o framework
Exception in thread "main" org.jf.dexlib2.DexFileFactory$UnsupportedOatVersionException: Unsupported oat version: 45
        at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:120)
        at org.jf.baksmali.DexInputCommand.loadDexFile(DexInputCommand.java:149)
        at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:161)
        at org.jf.baksmali.Main.main(Main.java:102)

**Comment by JesusFreke** [comment]
yep, it's unsupported :)

The older oat files have certain features that were not well specified/defined, and could potentially vary depending on the compiler/native libraries used.

**Comment by rauliordache** [comment]
And what solution do you have for this case?

For example, I have a Lollipop FusedLocation.odex. I want to get the smali files from it, but I have no luck...

**Comment by JesusFreke** [comment]
I don't have a solution.

**Comment by rauliordache** [comment]
I have solved the problem using this thread:
[https://github.com/testwhat/SmaliEx]

Everything is okay, but the new apk does not load (after some modifications):

12-05 19:54:41.555   547   650 I PackageManager: /system/priv-app/FusedLocation changed; collecting certs
12-05 19:54:41.591   547   650 W PackageManager: Failed to parse /system/priv-app/FusedLocation: Signature mismatch for shared user: SharedUserSetting{6a8659b android.uid.system/1000}

**Comment by JesusFreke** [comment]
When an apk uses a shared user id, all apks associated with that shared user id must use the same signature. If you change the signature of one of them, you have to change the signature of all of them.

**Comment by rauliordache** [comment]
And in my case, what do you recommnend ?
I have changed a little just the FusedLocation.apk (the smali code after de-compiling)

**Comment by JesusFreke** [comment]
"If you change the signature of one of them, you have to change the signature of all of them."

**Comment by amit343** [comment]
i  facing same problem .

**Comment by amit343** [comment]
Exception in thread "main" org.jf.dexlib2.DexFileFactory$UnsupportedOatVersionException: Unsupported oat version: 45
        at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:120)
        at org.jf.baksmali.DexInputCommand.loadDexFile(DexInputCommand.java:149)
        at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:162)
        at org.jf.baksmali.Main.main(Main.java:102)

**Comment by ronmazor** [comment]
i have no issue to change all the system signature

We have many files to modify , if someone can help please contact me private

**Comment by xuuhaoo** [comment]
> I have solved the problem using this thread:
> [https://github.com/testwhat/SmaliEx]
> 
> Everything is "okay", but the new apk does not load (after some modifications):
> 
> 12-05 19:54:41.555 547 650 I PackageManager: /system/priv-app/FusedLocation changed; collecting certs
> 12-05 19:54:41.591 547 650 W PackageManager: Failed to parse /system/priv-app/FusedLocation: Signature mismatch for shared user: SharedUserSetting{6a8659b android.uid.system/1000}

Is good to hear Thanks
