### ISSUE TITLE
How to get the line number of source code

### ISSUE THREAD

**Issue by lhf777111** [JesusFreke/smali#666]
If I have a debug version apk,  how to get the source line number corresponding to the org.jf.dexlib2.iface.instruction.Instruction

**Comment by JesusFreke** [comment]
As you iterate through the instructions in the method, you have to keep track of the code address. For every instruction, you should increment the address by instruction.getCodeUnits().

Once you've found the code address for the instruction, you loop through the debug items for that method (see MethodImplementation.getDebugItems()), and find the LineNumber debug item for the largest code address that's less than or equal to the code address of the instruction. The debug items will be returned in order by code address.
