### ISSUE TITLE
invoke-virtual-quick and iput-object-quick opcode error

### ISSUE THREAD

**Issue by vvMalko** [JesusFreke/smali#689]
baksmali-2.2.6
JDK 11.0.2

Get  #unknown opcode: 0xf8 and #unknown opcode: 0xf7

[libsgmain_315446400000.zip](https://github.com/JesusFreke/smali/files/2897766/libsgmain_315446400000.zip)

**Comment by JesusFreke** [comment]
invoke-virtual-quick and iput-object-quick are not valid dex opcodes. They are used in odex files. If you look at the header of your file, it starts with "dey", which is the magic value for an odex file.

You need to deodex it. See, e.g. https://github.com/JesusFreke/smali/wiki/DeodexInstructions and `baksmali help deodex`
