### ISSUE TITLE
How to make changes to a /system/framework files in API > 25 (Oreo)?

### ISSUE THREAD

**Issue by vovinio** [JesusFreke/smali#695]
I'm using an android _SDK emulator (API 26, Oreo)_ and trying to make a few slight modifications to some `/system/framework` files, and want to make changes in the `boot-framework.vdex` file (comes with `boot-framework.oat`, `boot-framework.art`)

I could'nt find the way to make the needed extraction via smali and therefore used vdexExtractor (```https://github.com/anestisb/vdexExtractor```) and managed
- extract the dex file (```boot-framework_classes2.dex```)
- extract the smali code from ```boot-framework_classes2.dex```

Though, from making some reading I understood that _vdexExtractor_  is not recommended and won't succeed a round trip, and moreover, I can't find the way to recompile it back to ```.dex``` and than back to ```.vdex```, and I'm not sure that my previous steps were even correct.

I'm trying to figure out what are the exact steps and tools I should use and do to decompile and than compile back the `boot-framework.vdex` file. 
It seems that the smali is able the do the job, it's just that I don't understand how exactly to use it.

Thanks.

**Comment by Lanchon** [comment]
this does not answer your question, but are things to keep in mind:

- odex oat vdex, all these pre-processed files are for the most part unspecified. they make sense only to the particular VM that is running in your device or emulator. smali understands files from some specific versions (most AOSP releases of the VM) with the aim of recovering an equivalent dex. it does not go the other way around; for that you got the tools already present on your device that are part of the VM.

- there is no guarantee that you can recover one dex and re-odex/re-compile it. depending on the VM version, the optimization step is global: if you are making changes to any file you need to recover ALL dex files and re-optimize everything (in the general case at least; there might be some android versions that don't need this, IDK for sure).

- in most cases you don't need to re-optimize: the VM will do that on demand if it has the dex files. so to patch code people typically deodex the (complete) rom, change some dex files, and leave it at that.
