### ISSUE TITLE
Can i to increment registers than 16

### ISSUE THREAD

**Issue by lebanggit** [JesusFreke/smali#700]
As title.

Can it increment  registers

Ex:

.registers 18
.registers 20

When i have change
.registers 15 to .registers 18

I have get errror:
 Invalid register: v17. Must be between v0 and v15, inclusive.

**Comment by xpirt** [comment]
You can not increase the maximum number of registers (16 bits) within a method. More info: https://source.android.com/devices/tech/dalvik/dalvik-bytecode

**Comment by JesusFreke** [comment]
The maximum number of registers is 2^16, not 16.

Some instructions can only reference a smaller subset of registers. "Invalid register: v17. Must be between v0 and v15, inclusive." implies it's using such an instruction. If you increase the number of registers, the parameter registers at the end of the range can get shifted out of the v0-v15 sweet spot, and you'll have to move register values around to get them back in the v0-v15 range.

One approach is to change all of the pNN registers to their equivalent vNN register (or just use --parameter-registers=false when disassembling), and then at the beginning of the method, insert a series of move instructions to move all of the parameter registers down to their original location. And then the new, free registers will be at the end of the register range. You may need to move them back down to a <=v15 register before use of course, depending on what instructions you use.
