### ISSUE TITLE
Samsung oreo deodex core-oj.jar

### ISSUE THREAD

**Issue by abrala** [JesusFreke/smali#701]
I wanted to mod core-oj.jar. I deodexed it from boot.oat
`java -jar baksmali-2.2.7.jar l d framework/arm64/boot.oat`
Got
`/system/framework/core-oj.jar`

`java -jar baksmali-2.2.7.jar x -a 26 -l framework/arm64/boot.oat/system/framework/core-oj.jar -d framework/arm64/`
Modded, assembled and putted it in /system/framework/. Wiped dalvik/cache and there's no in /data/dalvik-cache core-oj dex file, so the mod isn't working.

**Comment by JesusFreke** [comment]
I recommend looking in logcat for any errors from art. One possibility is that it's failing dex verification due to some invalid change you made. In which case, the logs from art will tell you exactly what is failing verification, which should let you pinpoint the problem and fix it.
