### ISSUE TITLE
Can not get the list of jar files in oat file (android Q)

### ISSUE THREAD

**Issue by bursoft-git** [JesusFreke/smali#706]
Hello, JF!
baksmali 2.3 returns nothing from oat file (android Q), but baksmali 2.2.7 works well

```
c:\BatchApkTool\_system\framework\arm64>java -jar baksmali-2.2.7.jar l d boot-ext.oat
/system/framework/ext.jar
```
```
c:\BatchApkTool\_system\framework\arm64>java -jar baksmali-2.3.jar l d boot-ext.oat

```
[boot-ext.zip](https://github.com/JesusFreke/smali/files/3481970/boot-ext.zip)

Thanks!

**Comment by JesusFreke** [comment]
The dex files are stored in the vdex file. You have to have a vdex file with the same base name as the oat file in the same directory*

(* or one directory up. see 1ac14a1082b8f5a016ee74d3f3d5a6f0521d0558)

**Comment by bursoft-git** [comment]
i mean baksmali 2.3 not return LIST of jar files from oat file
