### ISSUE TITLE
usages of field are not found

### ISSUE THREAD

**Issue by maiermic** [JesusFreke/smali#711]
This [field declaration][field-declaration] has 4 usages ([1][usage-1], [2][usage-2], [3][usage-3], [4][usage-4]). None of them is found.

You should be able to reproduce this by

```bash
git clone https://github.com/maiermic/panasonic-image-app.git
cd panasonic-image-app
git checkout 0c50c814b448dca7e64de0bdde13318d08f2fb25
```

Open the Android project in the (sub-) directory `panasonic-image-app_1.10.14`. Open the file `smali/com/panasonic/avc/cng/view/parts/LiveViewLumixZoomView.smali`. Move the cursor to the symbol `j` of the declaration statement of field `j` (line 40, column 16). Run `Edit -> Find -> Find Usages`. You should get the result `No usages found in All Places`.

[field-declaration]: https://github.com/maiermic/panasonic-image-app/blob/0c50c814b448dca7e64de0bdde13318d08f2fb25/panasonic-image-app_1.10.14/smali/com/panasonic/avc/cng/view/parts/LiveViewLumixZoomView.smali#L40

[usage-1]: https://github.com/maiermic/panasonic-image-app/blob/0c50c814b448dca7e64de0bdde13318d08f2fb25/panasonic-image-app_1.10.14/smali/com/panasonic/avc/cng/view/parts/LiveViewLumixZoomView.smali#L1621

[usage-2]: https://github.com/maiermic/panasonic-image-app/blob/0c50c814b448dca7e64de0bdde13318d08f2fb25/panasonic-image-app_1.10.14/smali/com/panasonic/avc/cng/view/parts/LiveViewLumixZoomView.smali#L1033

[usage-3]: https://github.com/maiermic/panasonic-image-app/blob/0c50c814b448dca7e64de0bdde13318d08f2fb25/panasonic-image-app_1.10.14/smali/com/panasonic/avc/cng/view/parts/LiveViewLumixZoomView.smali#L1128

[usage-4]: https://github.com/maiermic/panasonic-image-app/blob/0c50c814b448dca7e64de0bdde13318d08f2fb25/panasonic-image-app_1.10.14/smali/com/panasonic/avc/cng/view/parts/LiveViewLumixZoomView.smali#L1223

---

IntelliJ IDEA 2019.2.1
org.jf.smalidea 0.05

**Comment by JesusFreke** [comment]
Thanks for the great bug report :). It definitely looks like those usages should be found, I'm not sure why they're not.

**Comment by JesusFreke** [comment]
This was due to the duplicate java and smali versions of the LiveViewLumixZoomView class. After deleting the java copy, it was able to find the usages in the smali copy.

One possibility to get around this problem might be to define 2 modules in the project, one with the java sources, and another with the smali sources.

**Comment by maiermic** [comment]
Thanks for looking into this. I will try to define 2 modules.
