### ISSUE TITLE
smali failure when using lambda functions

### ISSUE THREAD

**Issue by ajwfrost** [JesusFreke/smali#713]
Hi

We have a dex file that's created from code that uses a lambda function:
`mMainView.setOnClickListener((View view) -> Toast.makeText(mMainActivity, "Java 8 lambda feature test", Toast.LENGTH_LONG).show());`

When we run this through the baksmali disassembler, the resulting smali file has the line:
`    invoke-custom {p0}, call_site_0("onClick", (Lcom/test/ane/Java8ANE;)Landroid/view/View$OnClickListener;, (Landroid/view/View;)V, invoke-direct@Lcom/test/ane/Java8ANE;->lambda$init$0(Landroid/view/View;)V, (Landroid/view/View;)V)@Ljava/lang/invoke/LambdaMetafactory;->metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
`

But when we then use smali to re-assemble it, we get an error:
`out\com\test\ane\Java8ANE.smali[116,4] null`

Attached is the classes.dex file: commands used are just:
```
java -jar baksmali-2.3.1.jar d -o out classes.dex
java -jar smali-2.3.1.jar a -o out\classes.dex out

```

thanks

**Comment by JesusFreke** [comment]
Yeah, I really need to improve the error message there. Try throwing in a -a 26 on the command line :)

**Comment by ajwfrost** [comment]
Ah - API level 26 .. yes that makes sense! And works... many thanks!
