### ISSUE TITLE
Can't install plugin on android stuido 3.5

### ISSUE THREAD

**Issue by s97712** [JesusFreke/smali#718]
![image](https://user-images.githubusercontent.com/13390001/64601450-898eea80-d3ef-11e9-87e1-289f1d5466be.png)
I follow the document to install it , but occurr the error above.

**Comment by JesusFreke** [comment]
What is the size and sha256 of JesusFreke-smali-f8d6f1576854.zip?

**Comment by s97712** [comment]
2065Kib
sha256 3E37B27925113316E9A7B651BE42510129A0352B8D0A4589DE04749D00553BA8

**Comment by JesusFreke** [comment]
I don't know what that is, but it's definitely not the smalidea plugin.

```
$ sha256sum smalidea-0.05.zip 
9ca4fc6c1ab131019bb70d1ed101c0011346bea2cfa9bfeda020d0102587001a smalidea-0.05.zip
$ ls -l smalidea-0.05.zip 
-rw-r--r-- 1 user primarygroup 12525202 Sep 10 10:15 smalidea-0.05.zip
```

The naming scheme of the zip file looks like you might have downloaded a zip archive of the github repository.

The downloads are hosted at https://bitbucket.org/JesusFreke/smali/downloads/
