### ISSUE TITLE
Can't install smalidea plugin

### ISSUE THREAD

**Issue by deepaksrinivasa** [JesusFreke/smali#720]
Following instructions from here - https://github.com/JesusFreke/smali/wiki/smalidea
I have downloaded smalidea-0.05.zip from here - https://bitbucket.org/JesusFreke/smali/downloads/

When I go to Android Studio > Preferences > Plugins > Install Plugin From Disk and select the downloaded zip file, I get an error message that says:
"Failed to load plugin descriptor from file smalidea-0.05.zip"

Any help is appreciated. Thanks.
- Deepak.

**Comment by deepaksrinivasa** [comment]
I'm using Android Studio 3.3.2

**Comment by JesusFreke** [comment]
Sounds like the download got corrupted. What is the sha256 of your copy of smalidea-0.05.zip?

**Comment by dw881220** [comment]
I faced the same problem. I downloaded sever versions smali-2.3.1.jar, smali2.0.jar,  baksmali-2.3.1.jar. But they all can not installed in androidstudio. The popup window said "Failed to load plugin descriptor from file *****.jar". I am using android studio 3.5.

**Comment by dw881220** [comment]
I tried smalidea-0.03.zip. And it worked. It is the only zip file in the list.  All the .jar file can not be installed. but the only .zip file worked. I don't know why.

**Comment by deepaksrinivasa** [comment]
In my case, when I downloaded the zip file from Safari browser on Mac, it unzipped the file by default. So, I zipped it back and tried to install. That's how I ran into the corrupted file problem (with a different sha256). 

When I switched off the 'Open safe files' option in Safari, it just downloaded the zip file. I was able to install this file - smalidea-0.05.zip - without any problem.

Thanks @JesusFreke for pointing me in the right direction.

**Comment by Tjossul** [comment]
Hello,

sadly this doesn't work for me. I downloaded different versions (0.05, v2.3 and latest) from https://bitbucket.org/JesusFreke/smali/downloads/?tab=tags without opening, just saving, but running into this error every time. At least I tried v2.3 - sha256 is 3cccf68502b6b36c01b517b34892d63a2d7308d8. I have Android Studio 3.5.3. What can I do?

Regards.

**Comment by JesusFreke** [comment]
Those are source tarballs/zips. Download the smalidea zip file on the downloads tab.

**Comment by Tjossul** [comment]
O no, I'm blind - saw the jar files only... Thanks man.

**Comment by Ishaantheguy** [comment]
I have downloaded the entire zip file but android studio is failing to load the plugin , any idea what it might be
