### ISSUE TITLE
No registers in debugger

### ISSUE THREAD

**Issue by PATAPOsha** [JesusFreke/smali#721]
I use smalidea v0.05 + Android Studio 3.5
Decompiled apk with latest apktool.
In debugger window I can see only variables values, but not registers.

![image](https://user-images.githubusercontent.com/14761219/64691495-6faae180-d49b-11e9-9ebc-2885c621753e.png)

When decompiling with baksmali it skips most of classes (probably a topic for another issue). No errors or warnings in output. I can see those classes in dex2jar and apktool outputs but not in baksmali's output. According to my observations, baksmali skips classes that have length of obfuscated name > 3 characters (e.x. aaaq.class, aaar.class, aaas.class ...). I checked baksmali output dir and didn't find any class that have 4 characters in its name.

**Comment by JesusFreke** [comment]
Raw registers are not added to the "Variable" pane. If you want to look at a register, you have to add a watch for it in the watch pane.

Feel free to file an issue for the other problem. My initial guess is that the apk contains multiple dex files, and you're only disassembling one of them.
