### ISSUE TITLE
How to modify dex method Implementation use dexlib2 ?

### ISSUE THREAD

**Issue by Youlor** [JesusFreke/smali#724]
My Code:
```
          protected class MyRewrittenMethodImplementation extends RewrittenMethodImplementation{
       @Override public Iterable<? extends Instruction> getInstructions()
        {
            List<Instruction> instructions = Lists.newArrayList(super.getInstructions());
            instructions.add(0, new ImmutableInstruction31c(Opcode.CONST_STRING_JUMBO, 0,
                    new ImmutableStringReference("hello")));
            return instructions;
        }}
```
but method which has try catch will wrong!
So, how to modify dex method Implementation  correctly?
Thanks!

**Comment by JesusFreke** [comment]
You should create a MutableMethodImplementation from the existing MethodImplementation, and use, e.g. MutableMethodImplementation.addInstruction, etc. to modify it.

**Comment by Youlor** [comment]
Thanks!
```
//class MyMethodRewriter.MyRewrittenMethod
@Override public MethodImplementation getImplementation()
        {
            if (method.getImplementation() != null)
            {
                MutableMethodImplementation implementation = new MutableMethodImplementation(method.getImplementation());
                implementation.addInstruction(0,
                        new BuilderInstruction31c(Opcode.CONST_STRING_JUMBO, 0, new ImmutableStringReference("hello")));
                return implementation;
            }
            return super.getImplementation();
        }
```
I found it seems ok! if I want to modify registerCount, shoud I extends RewrittenMethodImplementation and override getRegisterCount?
Where is dexlib2 documents or examples?

**Comment by JesusFreke** [comment]
Changing the register count opens up a whole new can of worms, particularly for methods that have a few more than 16 registers. The typical problem is when there is a parameter register mapped to v15. When you increase the register count by 1, that parameter register is now v16, and a lot of instructions can no longer access it.

The best approach I've seen for dealing with this is to add some code at the beginning of the modified method to move all of the parameter registers back down by however many registers you added. But you need to be careful with register types and use the appropriate move variant (move/move-wide/move-object).

You're much better off if you can avoid modifying the method count. e.g. by creating a new static method just and inserting a call into it with whatever info you need from the method being modified.

**Comment by Youlor** [comment]
Thanks, I'll close it!

**Comment by sriteja777** [comment]
Hey @JesusFreke @Youlor, can one of you tell how to increase the register count?

I am aware of consequences of increasing register count, and I want to do it only when there are less than 4 registers.

I am using MutableMethodImplementation class to modify instructions.
