### ISSUE TITLE
The baksmali program has some problems.

### ISSUE THREAD

**Issue by 760644586** [JesusFreke/smali#726]
1.After decompiling the DEX file, I put in a SmalI file and repackaged it. The following error is prompted. But my new SmalI file has nothing to do with where the error is indicated.

2.The following DEX file is the original file. SmalI is the file I want to add. The path to join is / out / Android / os

[dome.zip](https://github.com/JesusFreke/smali/files/3631580/dome.zip)

**Comment by 760644586** [comment]
![456](https://user-images.githubusercontent.com/41118619/65250621-6f0fec00-db28-11e9-8f64-1d8b82513020.png)
![123](https://user-images.githubusercontent.com/41118619/65250630-720adc80-db28-11e9-8eff-7fc20c834454.png)

**Comment by 760644586** [comment]
@JesusFreke

**Comment by JesusFreke** [comment]
It looks to me like the new class you added added enough method references to push the dex file over the 64k method reference limit.

**Comment by 760644586** [comment]
That's true. Thank you.
@JesusFreke
