### ISSUE TITLE
Q: How to make method native?

### ISSUE THREAD

**Issue by Youlor** [JesusFreke/smali#728]
My implements:
```
return new ImmutableMethod(
                method.getDefiningClass(),
                method.getName(),
                method.getParameters(),
                method.getReturnType(),
                method.getAccessFlags() | AccessFlags.NATIVE.getValue(),
                method.getAnnotations(),
                null);
```
But the generated method have codeitem: register_size = 0, ins = 2(if the method has two params), I don't thinke the native method should have codeitem!
So, How to solution? Thanks!

**Comment by JesusFreke** [comment]
This works for me:


    ImmutableClassDef class1 = new ImmutableClassDef("Lcls1;", AccessFlags.PUBLIC.getValue(), "Ljava/lang/Object;",
            null, null, null, null,
            Lists.<Method>newArrayList(
                    new ImmutableMethod("Lcls1", "method1",
                            Lists.<MethodParameter>newArrayList(
                                    new ImmutableMethodParameter("I", null, null),
                                    new ImmutableMethodParameter("I", null, null)), "V",
                            AccessFlags.PUBLIC.getValue() | AccessFlags.NATIVE.getValue(), null, null, null))
            );

    ImmutableDexFile dexFile = new ImmutableDexFile(Opcodes.getDefault(), Lists.newArrayList(class1));
    DexFileFactory.writeDexFile("/tmp/test.dex", dexFile);

After dumping the test dex file, the method has no code item associated with it

	                           |-----------------------------
	                           |class_data_item section
	                           |-----------------------------
	                           |
	                           |[0] class_data_item: Lcls1;
	000114: 00                 |  static_fields_size = 0
	000115: 00                 |  instance_fields_size = 0
	000116: 00                 |  direct_methods_size = 0
	000117: 01                 |  virtual_methods_size = 1
	                           |  virtual_methods:
	                           |    virtual_method[0]
	000118: 00                 |      method_idx_diff = 0: method_id_item[0]: Lcls1->method1(II)V
	000119: 8102               |      access_flags = 0x101: public|native
	00011b: 00                 |      code_off = code_item[NO_OFFSET]
	00011c: 0a00 0000          |size = 10


My best guess is that the code item is being added for you due to the parameter names, which live in the debug info item, which is referenced from the code item. You might try making copies of the parameters for the method and nulling out the parameter names.
