### ISSUE TITLE
Smali & Back-Smali Duplicate Classes

### ISSUE THREAD

**Issue by SumanKhanra** [JesusFreke/smali#729]
I'm Trying To Make A Android App With Smali And BakSmali Function. Its Working Fine With Individul Smali And Baksmali.jar Files. But When Trying To Compile With Both Its Giving Error...

One Sample Code : 
`Duplicate class com.beust.jcommander.DynamicParameter found in modules baksmali.jar (baksmali.jar) and smali.jar (smali.jar)`

Can You Make A Jar With Smali & BakSmali In It.
Or Tell Me How To Do MySelf
Sorry For My Bad English.

**Comment by Lanchon** [comment]
baksmali.jar and smali.jar are fat minified jars for running the apps.

you SHOULD NOT use them to develop. smali is also published in maven. to develop, use the maven artifacts exclusively.

**Comment by SumanKhanra** [comment]
Thanks Its Working Great
