### ISSUE TITLE
Oversight in VersionMap

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#730]
`case 28: return 138;` should be added [here](https://github.com/JesusFreke/smali/blob/bf65e575a0fd7f03c41aa56d7a49bf0cda1da06a/dexlib2/src/main/java/org/jf/dexlib2/VersionMap.java#L112).

you may also want to revisit `144` [here](https://github.com/JesusFreke/smali/blob/bf65e575a0fd7f03c41aa56d7a49bf0cda1da06a/dexlib2/src/main/java/org/jf/dexlib2/VersionMap.java#L113-L114).

thanks!

**Comment by JesusFreke** [comment]
Thanks, fixed in 210e36dc1902ac5e8dbe1a020feff181abdaff75
