### ISSUE TITLE
Support for 'hiddenapi_class_data_item'

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#731]
Some contex casual readers:

Android 9 introduced dex version 039. Android 10 continues to use same dex version identifier.

But contrary to expectations, Android 10 did extend the dex format anyway. The catch is, the extensions are meant to be used only by framework code. This means that dex files of apps for Android 10 will never contain these extensions, and so they will load without errors in Android 9. Hence, no new dex version was deemed necessary by the Android devs.

However, Android 10 framework bytecode does include these extensions, and I guess a round-trip though smali -if it works, i have not tried- will filter these out.

@JesusFreke, do you plan to support [`hiddenapi_class_data_item`](https://source.android.com/devices/tech/dalvik/dex-format#hiddenapi-class-data-item)?

Thanks!

**Comment by JesusFreke** [comment]
This is now supported as of c3bbc771f544eab300149b999fc7ecc8abe9fadb

**Comment by Lanchon** [comment]
thanks!
