### ISSUE TITLE
InstructionRewriter (very minor)

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#736]
this line:

https://github.com/JesusFreke/smali/blob/bf65e575a0fd7f03c41aa56d7a49bf0cda1da06a/dexlib2/src/main/java/org/jf/dexlib2/rewriter/InstructionRewriter.java#L84

should really be:

```
switch (instruction.getReferenceType()) {
```

in case someone overrides getReferenceType().

**Comment by JesusFreke** [comment]
Fixed by 5a900e22e068b8e6bb3dd6e9f65d198b5bd5d566
