### ISSUE TITLE
[Q] backtick quoting of names

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#739]
@JesusFreke,

re: https://github.com/JesusFreke/smali/commit/586ec594e2efd35dfe8d31cc221208fc886851dd

why backticks? are backticks not allowed in dex bytecode names?

they are certainly valid in jvm type names. if backticks are allowed in dex bytecode, then this commit is breaking compatibility with old smali files. if true this would it be very bad and IMHO should be fixed ASAP before the new format gains any traction.

the characters that cannot be part of JVM names ever are `;` and `[` (see JVM spec, class file format, names). to retain compatibility with old smali they could be put to use, and better for escaping than quoting, maybe like this:
- `com.example.My[20]Crap`
- or `[u20]` or `[u0020]`
- or `[space]` or `[s]`
- or even `[ ]` (but that complicates some parser implementations and i recommend against it)

 (btw, backticks are a bit impractical because they are a deadkeys on most international keyboard layouts, a thing english users tend to overlook.)

**Comment by Lanchon** [comment]
i use dexlib2 but not smali. i think there isn't any escaping in smali, right? i remember there was a smali fork that added precisely that, but i didn't look at it or whether any escaping was ever mainlined.

**Comment by JesusFreke** [comment]
Backticks are not an allowable character in the dex format. See https://source.android.com/devices/tech/dalvik/dex-format#simplename

Backticks seems like a reasonable choice to me. e.g. somewhat similar to code block escaping in markdown, or more directly to kotlin's identifier escaping with a backtick.

**Comment by Lanchon** [comment]
ok, thanks!

(btw, personally i've always worried that the dex format will expand it's valid character set to the whole JVM set in the future. so when i choose something like this, i make sure it's an ok choice for both.)

and is any char escaping there in smali? you could consider a solution like [NNNN] (would make ticks redundant, but that doesn't mean they shouldn't stay).
