### ISSUE TITLE
Android 9.0 about  boot-framework.art file type

### ISSUE THREAD

**Issue by 767972675** [JesusFreke/smali#740]
I modified framework.jar, removed the arm/arm64 in the framework folder and booted it successfully.
But it started up very slowly, I think because the system didn't find boot-framework.art, and then dex2oat executed
As a result, the startup speed is very slow. I ask you to help me framework.jar can produce boot-framework.art, boot-framework.art.rel, and other *.art files. I don't know how to use dex2oat to create a single jar

**Comment by JesusFreke** [comment]
Your best bet is to investigate the android build system, and see how it does it.

**Comment by VisionR1** [comment]
> I modified framework.jar, removed the arm/arm64 in the framework folder and booted it successfully. But it started up very slowly, I think because the system didn't find boot-framework.art, and then dex2oat executed As a result, the startup speed is very slow. I ask you to help me framework.jar can produce boot-framework.art, boot-framework.art.rel, and other *.art files. I don't know how to use dex2oat to create a single jar

I have exactly the same on my A11, you found any solution ?

**Comment by hanwenhao77** [comment]
In Android 9, framework.jar and boot-framework.art is build by framework-minus-apex.
The framework.jar build file is in system/framework/Android.bp,  named framework-minus-apex stem for framework.
The boot-framework.art build file is in build/make/targe/product/base_system.mk named PRODUCT_BOOT_JARS.

if you don't use framework.jar , you should modify this two files
