### ISSUE TITLE
[Q] hooking instance constructor calls

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#742]
hi @JesusFreke,

i'm trying to hook existing calls to instance constructors and replace them with calls to static methods that return a newly constructed instance of the right type of object.

the problem is: when new-instance is executed, the arguments to the constructor call are not known, so i can't call the hook method there. and when the call to `<init>` is executed, the constructor arguments are known and i can call the hook. but the pointer to the supposed new object has already been accessible to the rest of the code since new-instance executed. can code use it in any way before `<init>`?

it seems i have 2 options:
1. replace `new-instance v0,xxx` with `const v0,#1` so that if v0 is used by interleaving code it will trigger a verification error. and then replace the call to `<init>` with the call to the hook, which will return the real value for v0.
2. or just give up and simply provide an "after constructor" hook, which will get an already constructed object and hopefully can modify it. but it can't modify the constructor call itself.

so my question is: would option 1 work? what can happen to the pointer returned by new-instance before the constructor is called? can anything actually happen to it? it seems that even allowing a store of the pointer is unsafe: what happens if an exception is thrown after the store but before `<init>` succeeds? an uninitialized object would be reachable in the heap, which is unacceptable.

what is your opinion on option 1?

thank you very much!

**Comment by Lanchon** [comment]
@JesusFreke , would really appreciate your help with this one.

**Comment by JesusFreke** [comment]
I'm pretty sure the bytecode verifier will reject any instruction that attempts to call a method/access a field/pass as an argument an uninitialized object. Although iirc, things like null checks (if-eqz, etc.) and copy/move instructions will still work.

So I think you would need to track all registers that refer to the uninitialized object, remove the new-instance instruction and deal with any instructions referencing the uninitialized object, and then call your static helper, and copy its result to any of the registers that used to contain a reference to the uninitialized object.

**Comment by JesusFreke** [comment]
that being said, in the vast majority of cases, the construction invocation should occur immediately after the new-instance instruction :)

**Comment by Lanchon** [comment]
thank you!

i guess when the time comes to try this i'll just ignore the intermediate bytecode and let the verifier fail if the register is used somehow. we'll see if obfuscators ever trigger this.

thanks again!
