### ISSUE TITLE
Fail to load plugin descriptor from file smali-2.3.4.jar

### ISSUE THREAD

**Issue by BurrowsWang** [JesusFreke/smali#747]
The jar is downloaded from [https://bitbucket.org/JesusFreke/smali/downloads/](url)

Android Studio:
![image](https://user-images.githubusercontent.com/478717/72679402-c67b9400-3ae9-11ea-95f4-62f618443a21.png)

![image](https://user-images.githubusercontent.com/478717/72679369-83b9bc00-3ae9-11ea-9001-bfacdfcb183c.png)

**Comment by vadimTovstik** [comment]
How did you solve the problem?
