### ISSUE TITLE
gradle build error

### ISSUE THREAD

**Issue by dillrich** [JesusFreke/smali#754]
Initialized native services in: /home/user/.gradle/native
The client will now receive all logging from the daemon (pid: 3756). The daemon log file: /home/user/.gradle/daemon/5.1/daemon-3756.out.log
Starting 8th build in daemon [uptime: 2 hrs 7 mins 35.866 secs, performance: 99%]
Using 4 worker leases.
Starting Build
Settings evaluated using settings file '/home/user/Development/tools/smali/settings.gradle'.
Projects loaded. Root project using build file '/home/user/Development/tools/smali/build.gradle'.
Included projects: [root project 'smali', project ':baksmali', project ':dexlib2', project ':smali', project ':smalidea', project ':util', project ':dexlib2:accessorTestGenerator']

> Configure project :
Evaluating root project 'smali' using build file '/home/user/Development/tools/smali/build.gradle'.

> Configure project :baksmali
Evaluating project ':baksmali' using build file '/home/user/Development/tools/smali/baksmali/build.gradle'.

> Configure project :dexlib2
Evaluating project ':dexlib2' using build file '/home/user/Development/tools/smali/dexlib2/build.gradle'.

> Configure project :smali
Evaluating project ':smali' using build file '/home/user/Development/tools/smali/smali/build.gradle'.

> Configure project :util
Evaluating project ':util' using build file '/home/user/Development/tools/smali/util/build.gradle'.

> Configure project :dexlib2:accessorTestGenerator
Evaluating project ':dexlib2:accessorTestGenerator' using build file '/home/user/Development/tools/smali/dexlib2/accessorTestGenerator/build.gradle'.

> Configure project :smalidea
Evaluating project ':smalidea' using build file '/home/user/Development/tools/smali/smalidea/build.gradle'.
Configuring IntelliJ IDEA gradle plugin
Configuring IntelliJ IDEA dependency

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':smalidea'.
> Failed to notify project evaluation listener.
   > org/gradle/api/publish/ivy/internal/artifact/DefaultIvyArtifact
   > Cannot get property 'classes' on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by JesusFreke** [comment]
It looks like you're trying to build the smalidea plugin? I have some in-progress changes for smalidea to fix up the build, and will probably end up splitting it out into a separate project. I'll see if I can go ahead and get what I have pushed to github this weekend.

**Comment by dillrich** [comment]
Yes I was trying to build the smalidea plugin. Thanks for the response!
Will wait for you changes.

**Comment by JesusFreke** [comment]
The smalidea plugin has been split out into https://github.com/JesusFreke/smalidea It should build now, but feel free to file an issue over there if you run into any issues
