### ISSUE TITLE
Where is the dexlib2  doc? I can't find it.

### ISSUE THREAD

**Issue by HandsomeXi** [JesusFreke/smali#756]

**Comment by Lanchon** [comment]
project wiki and dexlib2 source.

btw if your nick ended in L instead of i i'd swear we were on a dating app lol

**Comment by HandsomeXi** [comment]
the source code is difficult😭

**Comment by Lanchon** [comment]
javadoc is here:

https://repo1.maven.org/maven2/org/smali/dexlib2/2.4.0/dexlib2-2.4.0-javadoc.jar

**Comment by HandsomeXi** [comment]
@Lanchon thx!
