### ISSUE TITLE
How do I turn a smali file into a ClassDef instance？

### ISSUE THREAD

**Issue by HandsomeXi** [JesusFreke/smali#757]

**Comment by auermich93** [comment]
@JesusFreke: Is this possible? Any utility class that supports this?

**Comment by JesusFreke** [comment]
See [SmaliTestUtils.compileSmali](https://github.com/JesusFreke/smali/blob/c3bbc771f544eab300149b999fc7ecc8abe9fadb/smali/src/main/java/org/jf/smali/SmaliTestUtils.java#L56)

**Comment by auermich93** [comment]
Thanks.
