### ISSUE TITLE
Any official docs about all of the directives such as ".local" ?

### ISSUE THREAD

**Issue by fjh1997** [JesusFreke/smali#762]
I can only find official docs about  dalvik bytecode  by google,But can't find any official docs about directives, all I can find is unoffical post and incomplete.

**Comment by fjh1997** [comment]
Someone say it is based on jasmin‘s syntax，but autually it is different,any docs to explain difference?

**Comment by JesusFreke** [comment]
The .locals directive and the differences from .registers is documented at https://github.com/JesusFreke/smali/wiki/Registers

**Comment by fjh1997** [comment]
No，it is about ".locals",but I need for '.local'

**Comment by fjh1997** [comment]
> The .locals directive and the differences from .registers is documented at https://github.com/JesusFreke/smali/wiki/Registers




> No，it is about ".locals",but I need for '.local'



> The .locals directive and the differences from .registers is documented at https://github.com/JesusFreke/smali/wiki/Registers

No，it is about ".locals",but I need for '.local'

**Comment by fjh1997** [comment]
> The .locals directive and the differences from .registers is documented at https://github.com/JesusFreke/smali/wiki/Registers

No，it is about ".locals",but I need for '.local'

**Comment by JesusFreke** [comment]
Oh, sorry :). The debug directives are pretty straightforward analogues of the corresponding debug information in the dex file. See, e.g. https://source.android.com/devices/tech/dalvik/dex-format#debug-info-item.

**Comment by fjh1997** [comment]
> Oh, sorry :). The debug directives are pretty straightforward analogues of the corresponding debug information in the dex file. See, e.g. https://source.android.com/devices/tech/dalvik/dex-format#debug-info-item.

Thanks a lot! And I hope there is a complete documentaion to explain these things in smali,It's really helpful for someone who know nothing about it  like me .
