### ISSUE TITLE
When there are multiple dex files, the decompilation fails,$NotADexFile: Not a valid dex

### ISSUE THREAD

**Issue by smalli** [JesusFreke/smali#765]
In my apk file，we have three dex files.

the root path,classes.dex classes2.dex
the root/assets/ path ,39285EFA.dex

when i decompilation this file,  i got these errors below 

Output>I: Baksmaling classes.dex...
Output>I: Baksmaling classes2.dex...
Output>I: Baksmaling assets/39285EFA.dex...
Error>Exception in thread "main" org.jf.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Not a valid dex magic value: cf 77 4c c7 9b 21 01 cd
Error>	at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:93)
Error>	at org.jf.dexlib2.dexbacked.DexBackedDexFile.getVersion(DexBackedDexFile.java:111)
Error>	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:78)
Error>	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:138)
Error>	at org.jf.dexlib2.dexbacked.ZipDexContainer$1.getDexFile(ZipDexContainer.java:181)
Error>	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:90)
Error>	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:39)
Error>	at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:96)
Error>	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:164)
Error>	at brut.apktool.Main.cmdDecode(Main.java:170)
Error>	at brut.apktool.Main.main(Main.java:76)

**Comment by smalli** [comment]
can the apktool  only decompilation the  dex file in the root path

**Comment by JesusFreke** [comment]
baksmali only disassembles the main classes.dex in the root of the apk by default. Any other dex file must be explicitly specified. This is WAI from the point of view of baksmali.

If you think apktool's dex iteration logic needs to be changed, I would recommend filing an issue in apktool's repository :)

**Comment by leoslamas** [comment]
Actually I'm pretty sure this is not an issue with non root dexes since I've already decompiled apks with dexes in assets/ folder.
It seems to be an issue with that 39285EFA.dex ("Not a valid dex magic value: cf 77 4c c7 9b 21 01 cd"). I found the same dex contained in an app i had to decompile, that's how I got here.

**Comment by strazzere** [comment]
The file is not a dex file, that is why it isn't able to baksmali it. The error message you've pasted explains this;
` 39285EFA.dex ("Not a valid dex magic value: cf 77 4c c7 9b 21 01 cd")`.

You're likely dealing with either
 - not an actual dex file
 - it's packed by something making it "not a dex file" until the unpacker does it's magic

Regardless, like @JesusFreke mentions, this is not baksmali's issue.

If you scan the apk with `apkid` or something similar, it might give you an indication of what packer is being used. Then you might find a way to get around it.

**Comment by leoslamas** [comment]
@smalli  I found this, maybe it can help you: You can use apktool d --only-main-classes or decoder.setDecodeAssets(ApkDecoder.DECODE_ASSETS_NONE) from code.
