### ISSUE TITLE
Make label constructor visible

### ISSUE THREAD

**Issue by GraxCode** [JesusFreke/smali#768]
It would be much easier to write code if we could do something like this:
```java
    MutableMethodImplementation mmi = new MutableMethodImplementation(2);
    mmi.addInstruction(new BuilderInstruction31i(Opcode.CONST, 0, 0));
    Label label = new Label();
    mmi.addInstruction(new BuilderInstruction21t(Opcode.IF_EQZ, 0, label));
    mmi.addInstruction(new BuilderInstruction31i(Opcode.CONST, 1, 1637));
    mmi.addInstruction(new BuilderInstruction11x(Opcode.RETURN, 1));
    mmi.addInstruction(new BuilderInstruction31i(Opcode.CONST, 1, 832).withLabels(label)); // withLabels(Label... labels); adds labels and returns itself
    mmi.addInstruction(new BuilderInstruction11x(Opcode.RETURN, 1));
```

**Comment by JesusFreke** [comment]
What about the current implementation doesn't work for you?

**Comment by GraxCode** [comment]
It is pretty annoying to create labels like this:
```java
    MutableMethodImplementation mmi = new MutableMethodImplementation(2);
    mmi.addInstruction(new BuilderInstruction31i(Opcode.CONST, 0, 0)); // either Object null or int 0
    // * jump here
    mmi.addInstruction(new BuilderInstruction31i(Opcode.CONST, 1, 1637));
    mmi.addInstruction(new BuilderInstruction11x(Opcode.RETURN, 1));
    BuilderInstruction31i target;
    mmi.addInstruction(target = new BuilderInstruction31i(Opcode.CONST, 1, 832));
    mmi.addInstruction(new BuilderInstruction11x(Opcode.RETURN, 1));

    Label label = target.getLocation().addNewLabel();

    // *
    mmi.addInstruction(1, new BuilderInstruction21t(Opcode.IF_EQZ, 0, label));
```
If there were multiple jumps i would probably lose the overview.

**Comment by JesusFreke** [comment]
I would recommend using the MutableMethodBuilder instead. MutableMethodImplementation is tailored a bit more towards modifying an existing method, while MutableMethodBuilder is more for building one from scratch.

e.g. 

    MethodImplementationBuilder mmb = new MethodImplementationBuilder(2);
    mmb.addInstruction(new BuilderInstruction31i(Opcode.CONST, 0, 0));
    mmb.addInstruction(new BuilderInstruction21t(Opcode.IF_EQZ, 0, mmb.getLabel("label1")));
    mmb.addInstruction(new BuilderInstruction31i(Opcode.CONST, 1, 1637));
    mmb.addInstruction(new BuilderInstruction11x(Opcode.RETURN, 1));
    mmb.addLabel("label1");
    mmb.addInstruction(new BuilderInstruction31i(Opcode.CONST, 1, 832));
    mmb.addInstruction(new BuilderInstruction11x(Opcode.RETURN, 1));

**Comment by GraxCode** [comment]
Oh, didn't know that existed, thanks!
