### ISSUE TITLE
Problem with baksmali's option "--classes"

### ISSUE THREAD

**Issue by Zchengwu** [JesusFreke/smali#777]
Hi, I want to know the input format of the option "--classes" in baksmali.

First of all, I listed all the classes related to "BluetoothDevice"(if this is the class I want) in this dex file:
```
$ java -jar baksmali-2.4.0.jar list classes ./classes.dex | grep BluetoothDevice  
Landroid/bluetooth/BluetoothDevicePicker;
Landroid/companion/BluetoothDeviceFilterUtils;
Landroid/bluetooth/BluetoothDevice$2;
Landroid/bluetooth/BluetoothDevice;
Landroid/companion/BluetoothDeviceFilter$1;
Landroid/companion/BluetoothDeviceFilter$Builder;
Landroid/companion/BluetoothDeviceFilter;
Landroid/bluetooth/BluetoothDevice$1;
```
then I tried:
```
$ java -jar baksmali-2.4.0.jar dis -o ./res --classes BluetoothDevice ./classes.dex

$ java -jar baksmali-2.4.0.jar dis -o ./res --classes Landroid/bluetooth/BluetoothDevice ./framework/classes.dex

$ java -jar baksmali-2.4.0.jar dis -o ./res --classes Landroid/bluetooth/BluetoothDevice, ./framework/classes.dex
```

All of them didn't work. So any advice? thanks ;)

[Uploading classes.zip…](dex file)

**Comment by Zchengwu** [comment]
[dex file](https://github.com/JesusFreke/smali/files/4987175/classes.zip)

**Comment by Lanchon** [comment]
it'd be easy to look at the source code and see. but have you tried `La/B;`? the long name ends with a semicolon, not a comma which seems to be what you tried.

also i'd try `a.B` and a java style regexp.

your shell may require quoting for stuff like semicolons and asterisks.

**Comment by JesusFreke** [comment]
It should be

    java -jar baksmali-2.4.0.jar dis -o ./res --classes "Landroid/bluetooth/BluetoothDevice;" ./framework/classes.dex

**Comment by Zchengwu** [comment]
tks，very enlightening！

> it'd be easy to look at the source code and see. but have you tried `La/B;`? the long name ends with a semicolon, not a comma which seems to be what you tried.
> 
> also i'd try `a.B` and a java style regexp.
> 
> your shell may require quoting for stuff like semicolons and asterisks.

**Comment by Zchengwu** [comment]
Another problem:
Here I want to dump BluetoothDevice$1.smali and tried:
```
java -jar baksmali-2.4.0.jar dis -o ./res --classes "Landroid/bluetooth/BluetoothDevice$1;" ./framework/classes.dex
```

Nothing generated. Is that in this way(with --classes) I cannot generate `*$*.smali`

**Comment by JesusFreke** [comment]
https://stackoverflow.com/questions/37876778/escape-dollar-sign-in-string-by-shell-script

**Comment by Lanchon** [comment]
your shell is interfering and passing the wrong argument. it requires quoting. try using quotes instead of double quotes or escaping the dollar with a backslash.
