### ISSUE TITLE
 Error for input ''$': Unterminated character literal

### ISSUE THREAD

**Issue by VinadiakT** [JesusFreke/smali#812]
I use baksmali to deodex odex ，can you tell me why it tell me this ?
Thank you
`
smali[35,51] Error for input ''~': Unterminated character literal
smali[37,0] no viable alternative at input '.field'
smali[49,52] Error for input ''$': Unterminated character literal
mali[51,0] no viable alternative at input '.field'
`

**Comment by JesusFreke** [comment]
Not without more information than that.
