### ISSUE TITLE
hiddenapi: smali creates invalid dex file

### ISSUE THREAD

**Issue by robertsmd** [JesusFreke/smali#815]
running the following command:

```bash
java -jar ~/Downloads/smali-2.5.2.jar a -a 29 -o classes.dex classes_dex
```

results in 
```bash
>>> dexdump classes.dex
Processing 'classes.dex'...
dexdump E 05-11 19:28:27 28058 4030355 dexdump.cc:1884] Failure to verify dex file 'classes.dex': Non-zero padding 7f before section of type 61440 at offset 0x8998be
```

or from dex2oat:
```bash
05-11 20:07:58.018 22289 22289 E dex2oat : Failed to open dex file for layout: Failure to verify dex file: Non-zero padding 7f before section of type 61440 at offset 0x899892
```

I am running on an api 29 emulator.

any help is appreciated!

**Comment by JesusFreke** [comment]
Interesting. It sounds like the hiddenapi section has an undocumented alignment requirement.

**Comment by robertsmd** [comment]
> Interesting. It sounds like the hiddenapi section has an undocumented alignment requirement.

Might be a hint here: https://android.googlesource.com/platform/art/+/master/tools/hiddenapi/hiddenapi.cc#621

**Comment by robertsmd** [comment]
@JesusFreke looks like I'll need your help here. Adding `getItemAlignment()` to the class `HiddenApiClassDataItem` didn't work the trick for me.

**Comment by robertsmd** [comment]
@Lanchon @iBotPeaches any help here would be appreciated so we can fix this, since you all have more experience with the dex format.

**Comment by robertsmd** [comment]
Adding line `offsetWriter.align();`  just before [this](https://github.com/JesusFreke/smali/blob/cbd41d36ccde221ccc4ec2aa0c15ca2fa4491a62/dexlib2/src/main/java/org/jf/dexlib2/writer/DexWriter.java#L506) line fixes the error above, but results in additional errors when verifying:

```bash
dexdump E 05-12 22:59:12 80234 5118856 dexdump.cc:1884] Failure to verify dex file 'classes.dex': Hiddenapi class data unexpected offset (27508 != 27506) for class def 42
```

**Comment by robertsmd** [comment]
appears to be an issue where the [sorting](https://github.com/JesusFreke/smali/blob/cbd41d36ccde221ccc4ec2aa0c15ca2fa4491a62/dexlib2/src/main/java/org/jf/dexlib2/writer/DexWriter.java#L495) isn't matching what is expected

**Comment by robertsmd** [comment]
Issue solved. `writeClass` needs to be called on the classes in order sorted by key (class name), but `writerestriction` (for hiddenapi restrictions) needs to be called on the classes in order sorted by the value (numerically ordered by `class_idx` (more info on `class_idx` can be found [here](https://source.android.com/devices/tech/dalvik/dex-format). PR #816 to fix it is submitted. @JesusFreke
