### ISSUE TITLE
ERROR BACKSMALI A DEX FILE 

### ISSUE THREAD

**Issue by tahooo39** [JesusFreke/smali#830]
i used this command : java -jar baksmali-2.5.2.jar d classes.dex
i get this output :
```
Lcom/ano/gshell/AnoApplication;-><clinit>()V: Invalid debug offset
Lcom/ano/gshell/AnoApplication;-><init>()V: Invalid debug offset
Lcom/ano/gshell/AnoApplication;->dec(Ljava/lang/String;)Ljava/lang/String;: Invalid debug offset
Lcom/ano/gshell/AnoApplication;->dec(Ljava/lang/String;)Ljava/lang/String;: Invalid debug offset
Lcom/ano/gshell/AnoApplication;->attachBaseContext(Landroid/content/Context;)V: Invalid debug offset
Lcom/ano/gshell/AnoApplication;->attachBaseContext(Landroid/content/Context;)V: Invalid debug offset
```

the file decompiled but when i compile the file again and replace it inside the app root folder (replace with original smali.dex)
and build with apktool and resign the  installed but then the app exit

and gives this logcat :

> 10-16 20:43:30.742 22936 22936 W dex2oat : /system/bin/dex2oat --runtime-arg -classpath --runtime-arg & --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2,-lock_add,-popcnt --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/user/0/com.dts.example/cache/app_resources_lib.jar --oat-fd=120 --oat-location=/data/user/0/com.dts.example/code_cache/app_resources_lib.dex --compiler-filter=speed
> 10-16 20:43:31.680 22936 22936 I dex2oat : /system/bin/dex2oat --dex-file=/data/user/0/com.dts.example/cache/app_resources_lib.jar --oat-fd=120 --oat-location=/data/user/0/com.dts.example/code_cache/app_resources_lib.dex --compiler-filter=speed
> 10-16 20:43:36.492 22998 22998 W dex2oat : /system/bin/dex2oat --runtime-arg -classpath --runtime-arg & --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2,-lock_add,-popcnt --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/user/0/com.dts.example/cache/google_api_resources_lib.jar --oat-fd=73 --oat-location=/data/user/0/com.dts.example/code_cache/google_api_resources_lib.dex --compiler-filter=speed
> 10-16 20:43:36.492 22998 22998 I dex2oat : /system/bin/dex2oat --dex-file=/data/user/0/com.dts.example/cache/google_api_resources_lib.jar --oat-fd=73 --oat-location=/data/user/0/com.dts.example/code_cache/google_api_resources_lib.dex --compiler-filter=speed
> 10-16 20:43:52.799 22540 23202 E cr_VariationsUtils: Failed reading seed file "/data/user/0/com.dts.example/app_webview/variations_seed_new": /data/user/0/com.dts.example/app_webview/variations_seed_new (No such file or directory)
> 10-16 20:43:52.804 22540 23202 E cr_VariationsUtils: Failed reading seed file "/data/user/0/com.dts.example/app_webview/variations_seed": /data/user/0/com.dts.example/app_webview/variations_seed (No such file or directory)
> 10-16 20:44:03.272 22540 22609 I YOUME   : Φ░âτö¿init σç╜µò░ σ╝Çσºï∩╝îτ¢«σ╜ò:/data/user/0/com.dts.example/app_libs
> 10-16 20:44:04.473 22540 22609 D houdini : [22609] Added shared library /data/app/com.dts.example-1/lib/arm/libyoume_voice_engine.so for ClassLoader by Native Bridge.
> 10-16 20:44:07.246 22540 22609 I YOUME   :         package:com.dts.example
> 10-16 20:44:16.214 22540 22609 D houdini : [22609] Added shared library /data/app/com.dts.example-1/lib/arm/libGGP.so for ClassLoader by Native Bridge.
> 10-16 20:44:25.647   586  1120 I WindowManager: WIN DEATH: Window{91e48a9 u0 com.dts.example/com.dts.example.FFMainActivity}
> 10-16 20:44:25.648   586  1120 W WindowManager: Force-removing child win Window{3caeb7 u0 SurfaceView - com.dts.example/com.dts.example.FFMainActivity} from container Window{91e48a9 u0 com.dts.example/com.dts.example.FFMainActivity}
> 10-16 20:44:25.648   586   661 I ActivityManager: Process com.dts.example (pid 22540) has died
> 10-16 20:44:25.675   586   661 W ActivityManager: Force removing ActivityRecord{98405cd u0 com.dts.example/.FFMainActivity t187}: app died, no saved state

the application runs without error when compile with original classes.dex .
but exit with the one that decompiled and recompiled with backsmali.

**Comment by JesusFreke** [comment]
Sounds like some form of copy/modification protection.
