### ISSUE TITLE
error file path when buliding resources

### ISSUE THREAD

**Issue by jhunee9090** [JesusFreke/smali#832]
**I tried to decompile the file and then immediately tried to compile the APK without changing anything but the process failed and got an error like this**

W: error: invalid file path  

\res\arm\arm_path.xml'.

W: \res\values\public.xml:4070: error: invalid resource type 'arm' in <public>.

W; \res\values\public.xml: error: file failed to compile.

brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1):

**Comment by Lanchon** [comment]
wrong project. close this and read docs for apktool.

**Comment by jhunee9090** [comment]
Thanks for info
