### ISSUE TITLE
Github 'Releases' no longer used, but still confusing

### ISSUE THREAD

**Issue by mefistotelis** [JesusFreke/smali#849]
My firs experience with this project was that I visited it, clicked 'Releases' on the right bar, and downloaded a version from 2013.
And that worked. But it would be better to warn users who click on the right, instead of scrolling down to README.

If only there was a new release added, which has no files attached to it, just an information like:
```
Since 2013, releases of this project are no longer hosted on Github.
See README of the project for a link to newer binaries.
```

**Comment by JesusFreke** [comment]
Thanks, deleted that old release.

There is info prominently on the main readme about where they can be found.
