### ISSUE TITLE
comment syntax?

### ISSUE THREAD

**Issue by jakenvac** [JesusFreke/smali#855]
Sorry to raise an issue, but it seems discussions are disabled for this project.

Is there a way to leave comments in smali code? I'm currently reverse engineering several packages and it would be extremely useful. Right now I'm using a custom syntax and using `sed` to strip it at build time.

**Comment by strazzere** [comment]
Unless something has changed in recent years, the proper comment syntax is to place things after a `#`;

```smali
const-string v0, "testing" # this is a comment
```

**Comment by jakenvac** [comment]
Thanks! I tried this before and was getting errors, must have been something else I did wrong as it's working fine now.

Thanks again!
